import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const BASE = "https://kits.intermark-business.com";

const KITS_PRODUCTS = [
  // â”€â”€ Innovation, IA & MultimÃ©dia â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-inno-001",
    name: "Pack IA & Automatisation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-001`,
    description: "Kit numÃ©rique â€” IA & Automatisation. Ressources, prompts, workflows et modÃ¨les prÃªts Ã  l'emploi pour intÃ©grer l'intelligence artificielle dans vos processus quotidiens. IdÃ©al pour professionnels, entrepreneurs et consultants souhaitant gagner en productivitÃ© grÃ¢ce aux outils IA. Livraison numÃ©rique immÃ©diate. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-002",
    name: "Pack Crypto & Blockchain",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-002`,
    description: "Kit numÃ©rique â€” Crypto & Blockchain. Ressources pÃ©dagogiques et outils pour comprendre et utiliser les cryptomonnaies et la technologie blockchain. Pour investisseurs, curieux du Web3 et professionnels de la finance souhaitant maÃ®triser les actifs numÃ©riques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-003",
    name: "Pack Crypto & Blockchain â€“ ModÃ¨les & Outils",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-003`,
    description: "Kit numÃ©rique â€” ModÃ¨les & Outils Crypto/Blockchain. Templates, tableaux de suivi et documents opÃ©rationnels pour gÃ©rer et analyser vos investissements en cryptomonnaies et projets blockchain. PrÃªts Ã  l'emploi et adaptables. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-004",
    name: "Pack Crypto, Blockchain & FinTech",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-004`,
    description: "Kit numÃ©rique â€” Crypto, Blockchain & FinTech. Pack complet combinant ressources IA, workflows et outils applicables aux secteurs de la finance technologique : DeFi, paiements numÃ©riques, tokenisation. Pour professionnels de la finance et entrepreneurs du secteur FinTech. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-005",
    name: "Pack Digital Business â€“ Outils & ModÃ¨les",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-005`,
    description: "Kit numÃ©rique â€” Digital Business. Ressources IA, prompts et workflows pour moderniser vos mÃ©thodes de travail. ModÃ¨les adaptables pour piloter une activitÃ© digitale, automatiser des tÃ¢ches et accÃ©lÃ©rer votre transformation numÃ©rique. â˜… 4,7 â€” 86 achats. 5 000 FCFA.",
  },

  // â”€â”€ Informatique & Logiciels â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-inf-001",
    name: "Pack Informatique & Outils Digitaux",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-001`,
    description: "Kit numÃ©rique â€” Informatique & Outils Digitaux. Ressources, guides et modÃ¨les pour maÃ®triser les outils informatiques professionnels. Pour techniciens, assistants administratifs et toute personne souhaitant renforcer ses compÃ©tences numÃ©riques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-002",
    name: "Pack CybersÃ©curitÃ© â€“ Protection & Gestion des Risques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-002`,
    description: "Kit numÃ©rique â€” CybersÃ©curitÃ©. Politiques, procÃ©dures et modÃ¨les pour protÃ©ger votre entreprise contre les cybermenaces. Guides de sensibilisation, checklists de sÃ©curitÃ© et plans de rÃ©ponse aux incidents. Pour DSI, responsables IT et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-003",
    name: "Pack DÃ©veloppeur â€“ ModÃ¨les Tech & Documentation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-003`,
    description: "Kit numÃ©rique â€” Documentation DÃ©veloppeur. Templates techniques, modÃ¨les de cahier des charges, documentation API et guides de bonnes pratiques. Pour dÃ©veloppeurs, chefs de projet technique et startups souhaitant structurer leurs livrables. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-004",
    name: "Pack IT â€“ Gestion Infrastructure & Support Technique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-004`,
    description: "Kit numÃ©rique â€” Gestion IT. ModÃ¨les de tickets, procÃ©dures de support, plans de maintenance et tableaux de bord infrastructure. Pour responsables IT, techniciens systÃ¨mes et administrateurs rÃ©seau. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-005",
    name: "Pack Digital â€“ Automatisation & ProductivitÃ©",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-005`,
    description: "Kit numÃ©rique â€” Automatisation & ProductivitÃ©. Workflows, modÃ¨les et outils pour automatiser vos tÃ¢ches rÃ©pÃ©titives et booster votre productivitÃ© digitale. IntÃ©grations no-code, scripts prÃªts Ã  l'emploi et guides pratiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-006",
    name: "Pack CrÃ©ation Digitale â€“ Ressources & Templates Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-006`,
    description: "Kit numÃ©rique â€” CrÃ©ation Digitale. Templates professionnels pour la crÃ©ation de contenus digitaux : visuels, prÃ©sentations, mockups et ressources graphiques. Pour crÃ©ateurs de contenu, community managers et agences digitales. 5 000 FCFA.",
  },

  // â”€â”€ Commercial & Relation Client â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-comr-001",
    name: "Pack Commercial & Prospection",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-001`,
    description: "Kit numÃ©rique â€” Commercial & Prospection. Scripts de vente, modÃ¨les d'emails de prospection, tableaux de suivi des leads et fiches de dÃ©couverte client. Pour commerciaux, responsables des ventes et entrepreneurs souhaitant structurer leur dÃ©marche commerciale. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-002",
    name: "Pack CRM & Gestion Client",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-002`,
    description: "Kit numÃ©rique â€” CRM & Gestion Client. ModÃ¨les de fiches clients, tableaux de suivi, processus de fidÃ©lisation et outils de gestion de la relation client. Pour TPE, PME et Ã©quipes commerciales souhaitant professionnaliser leur suivi client. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-003",
    name: "Pack Vente â€“ Techniques & Documents Commerciaux",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-003`,
    description: "Kit numÃ©rique â€” Techniques de Vente. Documents commerciaux prÃªts Ã  adapter : devis, propositions commerciales, contrats de vente, argumentaires et objections. Pour toute Ã©quipe commerciale souhaitant accÃ©lÃ©rer son cycle de vente. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-004",
    name: "Pack Marketing & PublicitÃ©",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-004`,
    description: "Kit numÃ©rique â€” Marketing & PublicitÃ©. Plans marketing, briefs publicitaires, modÃ¨les de campagnes et outils de mesure de performance. Pour responsables marketing, agences et entrepreneurs souhaitant structurer leur stratÃ©gie de communication payante. â˜… 4,7 â€” 64 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-005",
    name: "Pack RÃ©seaux Sociaux â€“ Contenus & Gestion",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-005`,
    description: "Kit numÃ©rique â€” RÃ©seaux Sociaux. Calendriers Ã©ditoriaux, modÃ¨les de posts, stratÃ©gies de contenu et outils de gestion des rÃ©seaux sociaux. Pour community managers, entrepreneurs et marques souhaitant dÃ©velopper leur prÃ©sence digitale. â˜… 4,8 â€” 73 achats. 5 000 FCFA.",
  },

  // â”€â”€ Communication & Marketing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-com-001",
    name: "Pack Pro MÃ©dias & Communication Visuelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-001`,
    description: "Kit numÃ©rique â€” MÃ©dias & Communication Visuelle. Ressources et templates pour produire des contenus visuels professionnels : chartes graphiques, modÃ¨les de prÃ©sentations, supports de communication. Pour communicants, chargÃ©s de communication et Ã©quipes marketing. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-002",
    name: "Kit StratÃ©gies Marketing & Communication 360Â°",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-002`,
    description: "Kit numÃ©rique â€” Marketing & Communication 360Â°. StratÃ©gies complÃ¨tes couvrant communication digitale, offline et intÃ©grÃ©e. Plans de communication, matrices de positionnement et outils de pilotage de la marque. Pour directeurs marketing et consultants en communication. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-003",
    name: "Essentiel Communication â€“ Les Meilleures Ressources",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-003`,
    description: "Kit numÃ©rique â€” Essentiel Communication. SÃ©lection des meilleures ressources en communication professionnelle : guides, templates et outils incontournables pour amÃ©liorer sa communication en entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-004",
    name: "Pack Digital â€“ Communication & Marketing en Ligne",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-004`,
    description: "Kit numÃ©rique â€” Communication & Marketing en Ligne. Outils et modÃ¨les pour piloter sa prÃ©sence digitale : SEO, email marketing, publicitÃ© en ligne et analytics. Pour Ã©quipes marketing et entrepreneurs souhaitant dÃ©velopper leur acquisition digitale. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-005",
    name: "Pack Pro â€“ Techniques de Communication en Milieu Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-005`,
    description: "Kit numÃ©rique â€” Communication Professionnelle. Techniques et outils pour amÃ©liorer sa communication interne et externe en entreprise : prise de parole, rÃ©daction professionnelle, conduite de rÃ©unions. â˜… 4,9 â€” 44 achats. 5 000 FCFA.",
  },

  // â”€â”€ Entrepreneuriat & Leadership â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-bus-001",
    name: "Pack Startup â€“ 150 OpportunitÃ©s en Afrique Francophone",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-001`,
    description: "Kit numÃ©rique â€” 150 OpportunitÃ©s Business en Afrique Francophone. RÃ©pertoire de 150 idÃ©es d'affaires viables et rentables adaptÃ©es au contexte africain, avec analyses de marchÃ© et modÃ¨les Ã©conomiques. Pour entrepreneurs et porteurs de projets en Afrique. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-002",
    name: "Pack Business Plan Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-002`,
    description: "Kit numÃ©rique â€” Business Plan Pro. ModÃ¨les complets de business plans, Ã©tudes de marchÃ©, projections financiÃ¨res et prÃ©sentations investisseurs. Pour entrepreneurs, porteurs de projets et Ã©tudiants en gestion souhaitant structurer leur projet d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-003",
    name: "Pack Entrepreneur â€“ 50 Documents Essentiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-003`,
    description: "Kit numÃ©rique â€” 50 Documents Essentiels de l'Entrepreneur. Collection de documents indispensables pour crÃ©er et gÃ©rer son entreprise : statuts, contrats, modÃ¨les administratifs, outils de gestion. Pour tout entrepreneur souhaitant dÃ©marrer sur des bases solides. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-004",
    name: "BibliothÃ¨que Entrepreneuriale â€“ 100 Livres Incontournables",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-004`,
    description: "Kit numÃ©rique â€” 100 Livres de l'Entrepreneur. SÃ©lection de 100 rÃ©sumÃ©s de livres incontournables en entrepreneuriat, management, stratÃ©gie et finance. Pour leaders, dirigeants et entrepreneurs souhaitant se former rapidement sur les meilleures pratiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-005",
    name: "Super Pack â€“ 64 ModÃ¨les de Plans d'Affaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-005`,
    description: "Kit numÃ©rique â€” 64 ModÃ¨les de Plans d'Affaires. Collection de 64 plans d'affaires sectoriels prÃªts Ã  personnaliser : commerce, services, agriculture, technologie, restauration, santÃ©â€¦ Pour entrepreneurs, banquiers et consultants en crÃ©ation d'entreprise. 5 000 FCFA.",
  },

  // â”€â”€ DÃ©veloppement Personnel â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-pers-001",
    name: "Kit DÃ©veloppement Personnel â€“ Mindset & Performance",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-001`,
    description: "Kit numÃ©rique â€” Mindset & Performance. Outils et exercices pour dÃ©velopper un Ã©tat d'esprit gagnant, fixer ses objectifs et atteindre ses ambitions personnelles et professionnelles. Pour toute personne souhaitant progresser et se surpasser. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-002",
    name: "Pack Coaching â€“ Outils & Exercices de Transformation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-002`,
    description: "Kit numÃ©rique â€” Coaching & Transformation. Exercices pratiques, outils de coaching et plans d'action pour accompagner une transformation personnelle ou professionnelle profonde. Pour coachs, formateurs et particuliers en dÃ©marche de dÃ©veloppement. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-003",
    name: "Pack Motivation â€“ 50 Livres RÃ©sumÃ©s + Outils",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-003`,
    description: "Kit numÃ©rique â€” Motivation & RÃ©ussite. 50 rÃ©sumÃ©s de livres de motivation et dÃ©veloppement personnel accompagnÃ©s d'outils pratiques pour passer Ã  l'action. Pour toute personne souhaitant s'inspirer des meilleurs auteurs et appliquer leurs enseignements. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-004",
    name: "Pack CarriÃ¨re â€“ CV, Lettres & PrÃ©paration Entretien",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-004`,
    description: "Kit numÃ©rique â€” CarriÃ¨re & Emploi. ModÃ¨les de CV professionnels, lettres de motivation percutantes et guides de prÃ©paration aux entretiens d'embauche. Pour Ã©tudiants, demandeurs d'emploi et professionnels en reconversion souhaitant dÃ©crocher leur prochain poste. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-005",
    name: "Kit Confiance en Soi â€“ Exercices & Outils Psychologiques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-005`,
    description: "Kit numÃ©rique â€” Confiance en Soi. Exercices psychologiques, techniques d'affirmation de soi et plans d'action pour dÃ©velopper une confiance solide dans la vie personnelle et professionnelle. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-006",
    name: "Pack Bien-Ãªtre & Gestion du Stress",
    pricingType: "PRODUCT",
    price: 2000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-006`,
    description: "Kit numÃ©rique â€” Bien-Ãªtre & Gestion du Stress. Techniques de relaxation, routines anti-stress et outils pour mieux gÃ©rer la pression au quotidien. Pour toute personne souhaitant amÃ©liorer son Ã©quilibre de vie. 2 000 FCFA.",
  },

  // â”€â”€ Excel & Tableaux â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-exc-001",
    name: "Pack Excel Premium â€“ 50 Tableaux AutomatisÃ©s",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-001`,
    description: "Kit numÃ©rique â€” Excel Premium. 50 tableaux Excel automatisÃ©s prÃªts Ã  l'emploi couvrant : suivi des ventes, gestion de stock, plannings, tableaux de bord et indicateurs de performance. Pour toute entreprise souhaitant gagner du temps sur ses reportings. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-002",
    name: "Pack Excel RH & Paie",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-002`,
    description: "Kit numÃ©rique â€” Excel RH & Paie. Fichiers Excel automatisÃ©s pour la gestion RH : calcul des salaires, suivi des congÃ©s, plannings du personnel, indicateurs RH et dÃ©clarations sociales. Pour gestionnaires RH, DRH et comptables de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-003",
    name: "Pack Excel Finance & Budgets",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-003`,
    description: "Kit numÃ©rique â€” Excel Finance & Budgets. ModÃ¨les Excel pour la gestion financiÃ¨re : budget prÃ©visionnel, plan de trÃ©sorerie, analyse des Ã©carts, bilans simplifiÃ©s et tableaux de bord financiers. Pour directeurs financiers, comptables et entrepreneurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-004",
    name: "Pack Data & Reporting â€“ Tableaux Intelligents",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-004`,
    description: "Kit numÃ©rique â€” Data & Reporting. Tableaux de bord intelligents et fichiers de reporting automatisÃ©s pour piloter votre activitÃ© avec des indicateurs clÃ©s. Pour analystes, contrÃ´leurs de gestion et managers souhaitant visualiser leurs donnÃ©es efficacement. 5 000 FCFA.",
  },

  // â”€â”€ Finance, Audit & ComptabilitÃ© â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-fin-001",
    name: "Pack ComptabilitÃ© GÃ©nÃ©rale Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-001`,
    description: "Kit numÃ©rique â€” ComptabilitÃ© GÃ©nÃ©rale. Documents, modÃ¨les et guides pratiques pour la comptabilitÃ© gÃ©nÃ©rale conforme SYSCOHADA : journaux, grands livres, Ã©tats financiers et procÃ©dures de clÃ´ture. Pour comptables et gestionnaires d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-002",
    name: "Pack Audit & ContrÃ´le Interne",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-002`,
    description: "Kit numÃ©rique â€” Audit & ContrÃ´le Interne. Programmes d'audit, questionnaires de contrÃ´le interne, matrices des risques et modÃ¨les de rapports d'audit. Pour auditeurs internes, contrÃ´leurs de gestion et responsables qualitÃ©. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-003",
    name: "Pack Finance & Gestion BudgÃ©taire",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-003`,
    description: "Kit numÃ©rique â€” Finance & Gestion BudgÃ©taire. Outils complets pour la gestion financiÃ¨re et budgÃ©taire : prÃ©visions, analyses de rentabilitÃ©, tableaux de bord financiers et modÃ¨les de reporting. Pour responsables financiers et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-004",
    name: "Pack Microfinance â€“ Gestion & ConformitÃ©",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-004`,
    description: "Kit numÃ©rique â€” Microfinance. Politiques, procÃ©dures et outils de gestion pour institutions de microfinance : gestion du crÃ©dit, Ã©pargne, conformitÃ© rÃ©glementaire et reporting. Pour gÃ©rants d'IMF, coopÃ©ratives et mutuelles d'Ã©pargne. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-005",
    name: "Pack Gestion BudgÃ©taire & PrÃ©visionnelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-005`,
    description: "Kit numÃ©rique â€” Budget & PrÃ©visions. ModÃ¨les et mÃ©thodologies pour Ã©laborer, suivre et analyser les budgets d'entreprise. Inclut budget de trÃ©sorerie, analyse des Ã©carts et plans de financement. Pour contrÃ´leurs de gestion et directeurs financiers. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-006",
    name: "Pack TrÃ©sorerie & LiquiditÃ©",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-006`,
    description: "Kit numÃ©rique â€” TrÃ©sorerie & LiquiditÃ©. Outils de gestion de trÃ©sorerie : tableaux de flux, prÃ©visions de liquiditÃ©, rapprochements bancaires et procÃ©dures de gestion du cash. Pour trÃ©soriers, responsables financiers et gÃ©rants de PME. 5 000 FCFA.",
  },

  // â”€â”€ Gestion & Administration â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-gest-001",
    name: "Pack Manager â€“ Leadership & Organisation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-001`,
    description: "Kit numÃ©rique â€” Leadership & Organisation. Outils pour managers : dÃ©lÃ©gation, conduite du changement, animation d'Ã©quipe, gestion des prioritÃ©s et dÃ©veloppement du leadership. Pour managers, chefs d'Ã©quipe et directeurs souhaitant renforcer leur posture de leader. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-002",
    name: "Pack Manager â€“ Ressources & Outils de Pilotage",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-002`,
    description: "Kit numÃ©rique â€” Pilotage ManagÃ©rial. Tableaux de bord, indicateurs de performance et outils opÃ©rationnels pour piloter une Ã©quipe et atteindre ses objectifs. Pour responsables d'Ã©quipe et directeurs de dÃ©partement. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-003",
    name: "Pack Pro â€“ Gestion des Stocks et Inventaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-003`,
    description: "Kit numÃ©rique â€” Gestion des Stocks. ModÃ¨les de suivi des stocks, fiches d'inventaire, procÃ©dures de rÃ©approvisionnement et tableaux de bord logistiques. Pour gestionnaires de stocks, magasiniers et responsables supply chain. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-004",
    name: "Kit Finances â€“ ComptabilitÃ© & Outils de Gestion",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-004`,
    description: "Kit numÃ©rique â€” ComptabilitÃ© & Gestion. Collection d'outils financiers et comptables pour la gestion quotidienne d'une entreprise : suivi des dÃ©penses, facturation, rapprochements et Ã©tats financiers simplifiÃ©s. Pour TPE, PME et entrepreneurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-005",
    name: "Kit RH â€“ Gestion des Ressources Humaines",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-005`,
    description: "Kit numÃ©rique â€” Gestion RH. Documents et outils complets pour la gestion des ressources humaines : contrats de travail, fiches de poste, procÃ©dures disciplinaires, Ã©valuations et politiques RH. Pour DRH, gestionnaires RH et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-006",
    name: "Kit Gestion de Projet â€“ Planification & Ã‰valuation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-006`,
    description: "Kit numÃ©rique â€” Gestion de Projet. Outils de planification, suivi et Ã©valuation de projets : cadres logiques, diagrammes de Gantt, matrices de risques et rapports d'avancement. Pour chefs de projet, coordinateurs et consultants. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-007",
    name: "Pack Chef de Projet â€“ MÃ©thodologie & Outils Essentiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-007`,
    description: "Kit numÃ©rique â€” Chef de Projet. MÃ©thodologies et outils essentiels pour mener des projets de A Ã  Z : charte projet, WBS, planning, gestion des risques et clÃ´ture. Pour chefs de projet certifiÃ©s ou en cours de certification. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-008",
    name: "Pack Risk Manager â€“ Anticipation & Pilotage des Risques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-008`,
    description: "Kit numÃ©rique â€” Risk Management. Outils d'identification, d'Ã©valuation et de pilotage des risques : cartographies, matrices de criticitÃ©, plans de continuitÃ© et procÃ©dures ISO 31000. Pour risk managers, auditeurs et dirigeants d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-009",
    name: "Mini Pack â€“ BudgÃ©tisation & Gestion PrÃ©visionnelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-009`,
    description: "Kit numÃ©rique â€” BudgÃ©tisation. ModÃ¨les simplifiÃ©s et guides pratiques pour construire un budget prÃ©visionnel et suivre ses rÃ©alisations. Accessible aux non-financiers. Pour chefs de service et responsables opÃ©rationnels. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-010",
    name: "Kit Pro â€“ Protection Sociale & Droit du Travail",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-010`,
    description: "Kit numÃ©rique â€” Protection Sociale & Droit du Travail. Documents de rÃ©fÃ©rence sur la lÃ©gislation du travail, les obligations sociales et les droits des employÃ©s en Afrique francophone. Pour DRH, juristes d'entreprise et gestionnaires du personnel. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-011",
    name: "Pack CarriÃ¨re â€“ Emploi, RÃ©daction & Insertion Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-011`,
    description: "Kit numÃ©rique â€” Emploi & Insertion Professionnelle. Outils complets pour la recherche d'emploi : CV, lettres de motivation, prÃ©paration aux entretiens et stratÃ©gies de rÃ©seautage. Pour Ã©tudiants et jeunes professionnels en insertion. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-012",
    name: "Pack Assistant Pro â€“ SecrÃ©tariat & Bureautique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-012`,
    description: "Kit numÃ©rique â€” SecrÃ©tariat & Bureautique. ModÃ¨les de correspondance professionnelle, procÃ©dures d'accueil, gestion du courrier et outils bureautiques. Pour assistantes de direction, secrÃ©taires et office managers. 5 000 FCFA.",
  },

  // â”€â”€ Juridique & ConformitÃ© â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-jur-001",
    name: "Pack Juridique & Gestion Administrative de l'Entreprise",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-001`,
    description: "Kit numÃ©rique â€” Juridique & Administration. Documents juridiques et administratifs essentiels pour la gestion d'entreprise : statuts, procÃ¨s-verbaux, dÃ©libÃ©rations, modÃ¨les de contrats courants. Pour dirigeants de PME et juristes d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-002",
    name: "Pack Droit des Affaires & ModÃ¨les Juridiques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-002`,
    description: "Kit numÃ©rique â€” Droit des Affaires. ModÃ¨les juridiques pour les activitÃ©s commerciales : contrats commerciaux, CGV, baux professionnels, protocoles d'accord OHADA. Pour avocats, juristes et chefs d'entreprise en Afrique. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-003",
    name: "Pack Legal Pro â€“ 200 Contrats Banque & Assurance",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-003`,
    description: "Kit numÃ©rique â€” 200 Contrats Banque & Assurance. Collection de 200 modÃ¨les de contrats et documents juridiques du secteur bancaire et assurantiel. Pour juristes de banques, compagnies d'assurance et Ã©tablissements financiers. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-004",
    name: "Pack LÃ©gal â€“ 125 Contrats Immobiliers",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-004`,
    description: "Kit numÃ©rique â€” 125 Contrats Immobiliers. Collection de 125 modÃ¨les de contrats pour les transactions immobiliÃ¨res : vente, location, bail commercial, mandat de gestion, promesse de vente. Pour agents immobiliers, notaires et promoteurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-005",
    name: "Pack LÃ©gal Express â€“ 100 Contrats BTP",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-005`,
    description: "Kit numÃ©rique â€” 100 Contrats BTP. Collection de 100 modÃ¨les de contrats pour le secteur du bÃ¢timent et des travaux publics : contrats de construction, sous-traitance, marchÃ©s de travaux, rÃ©ceptions et garanties. Pour entrepreneurs BTP et maÃ®tres d'ouvrage. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-006",
    name: "Pack Avocat & Conseiller Juridique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-006`,
    description: "Kit numÃ©rique â€” Avocat & Conseil Juridique. Outils et modÃ¨les pour la pratique juridique : consultations, conclusions, conventions honoraires, modÃ¨les de plaidoiries et lettres juridiques. Pour avocats, juristes et conseillers juridiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-007",
    name: "Pack PME â€“ Droit, ConformitÃ© & RÃ©glementation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-007`,
    description: "Kit numÃ©rique â€” PME & ConformitÃ©. Outils de conformitÃ© rÃ©glementaire pour PME : politique de conformitÃ©, registres lÃ©gaux obligatoires, procÃ©dures RGPD et obligations fiscales. Pour dirigeants de PME soucieux de leur conformitÃ©. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-008",
    name: "Pack Juridique â€“ Contrats Professionnels & Documents Officiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-008`,
    description: "Kit numÃ©rique â€” Contrats Professionnels. Grande collection de contrats professionnels et documents officiels tous secteurs confondus. Pour toute entreprise souhaitant disposer d'une base documentaire juridique solide. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-009",
    name: "Pack Droit Social & Gestion du Personnel",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-009`,
    description: "Kit numÃ©rique â€” Droit Social. Documents et procÃ©dures relatifs au droit du travail et Ã  la gestion du personnel : rÃ¨glement intÃ©rieur, sanctions disciplinaires, licenciements et contrats de travail. Pour DRH, juristes et dirigeants d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-010",
    name: "Pack ConformitÃ© â€“ Risques, Audit & RÃ©glementation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-010`,
    description: "Kit numÃ©rique â€” ConformitÃ© & RÃ©glementation. Outils complets pour la conformitÃ© : politiques anticorruption, procÃ©dures KYC, plans de continuitÃ© d'activitÃ© et audit de conformitÃ©. Pour compliance officers et directions gÃ©nÃ©rales. 5 000 FCFA.",
  },

  // â”€â”€ Projets & Appels d'Offres â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-prj-001",
    name: "Pack Projets â€“ ModÃ¨les de Gestion & Suivi",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-001`,
    description: "Kit numÃ©rique â€” Gestion & Suivi de Projets. ModÃ¨les opÃ©rationnels pour planifier, exÃ©cuter et clore des projets : tableaux de bord, rapports d'avancement, plans d'action et bilans. Pour chefs de projet et coordinateurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-002",
    name: "Pack Appels d'Offres â€“ Dossiers & ModÃ¨les",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-002`,
    description: "Kit numÃ©rique â€” Appels d'Offres. Dossiers types et modÃ¨les pour rÃ©pondre aux appels d'offres publics et privÃ©s : offre technique, offre financiÃ¨re, note mÃ©thodologique et rÃ©fÃ©rences. Pour entreprises soumissionnaires et consultants. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-003",
    name: "Pack ONG â€“ Gestion de Projets Humanitaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-003`,
    description: "Kit numÃ©rique â€” ONG & Humanitaire. Outils de gestion de projets pour ONG : proposition de projet, cadre logique, rapports bailleurs, suivi-Ã©valuation et procÃ©dures de passation de marchÃ©s. Pour coordinateurs et chargÃ©s de projets humanitaires. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-004",
    name: "Pack ONG & Projets Humanitaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-004`,
    description: "Kit numÃ©rique â€” ONG & Projets Humanitaires. Collection complÃ¨te d'outils pour la gestion et le financement des projets humanitaires et de dÃ©veloppement. Inclut politiques organisationnelles, outils de collecte de fonds et modÃ¨les de rapports. â˜… 4,8 â€” 109 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-005",
    name: "Pack Gestion des Risques & ConformitÃ©",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-005`,
    description: "Kit numÃ©rique â€” Gestion des Risques & ConformitÃ©. Outils pour identifier, Ã©valuer et maÃ®triser les risques en entreprise et assurer la conformitÃ© rÃ©glementaire. Cartographies, registres de risques et plans de traitement. â˜… 4,9 â€” 32 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-006",
    name: "Pack Management & Leadership OpÃ©rationnel",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-006`,
    description: "Kit numÃ©rique â€” Management OpÃ©rationnel. Outils pour passer plus vite de l'idÃ©e Ã  l'exÃ©cution : plans d'action, matrices de dÃ©cision, outils de pilotage et techniques de management d'Ã©quipe. Pour managers et directeurs opÃ©rationnels. â˜… 4,6 â€” 41 achats. 5 000 FCFA.",
  },

  // â”€â”€ Secteurs Professionnels â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-pro-001",
    name: "Pack QHSE Premium",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-001`,
    description: "Kit numÃ©rique â€” QHSE Premium. Documents et procÃ©dures pour les systÃ¨mes de management QualitÃ©, HygiÃ¨ne, SÃ©curitÃ© et Environnement : politique QHSE, plans d'inspection, fiches de sÃ©curitÃ© et rapports d'accidents. Pour responsables QHSE et auditeurs ISO. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-002",
    name: "Pack Logistique & Supply Chain",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-002`,
    description: "Kit numÃ©rique â€” Logistique & Supply Chain. ProcÃ©dures, modÃ¨les et tableaux de bord pour la gestion de la chaÃ®ne logistique : rÃ©ception, stockage, expÃ©dition, transport et suivi des fournisseurs. Pour logisticiens et responsables supply chain. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-003",
    name: "Pack BTP & Chantier",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-003`,
    description: "Kit numÃ©rique â€” BTP & Chantier. Documents opÃ©rationnels pour la gestion de chantier : plans d'installation, rapports de chantier, fiches de pointage, suivi des travaux et rÃ©ception provisoire. Pour conducteurs de travaux et chefs de chantier. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-004",
    name: "Pack Immobilier â€“ Gestion & Location",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-004`,
    description: "Kit numÃ©rique â€” Immobilier. Documents pour la gestion immobiliÃ¨re et locative : baux d'habitation, contrats de location, Ã©tats des lieux, quittances et modÃ¨les de vente. Pour agents immobiliers, propriÃ©taires bailleurs et gestionnaires de biens. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-005",
    name: "Pack HÃ´tel â€“ Tourisme & HÃ©bergement",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-005`,
    description: "Kit numÃ©rique â€” HÃ´tellerie & Tourisme. ProcÃ©dures opÃ©rationnelles, fiches de poste, check-lists et outils de gestion pour Ã©tablissements hÃ´teliers et touristiques. Pour directeurs d'hÃ´tels, managers de rÃ©ception et responsables de la restauration. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-006",
    name: "Pack Commerce â€“ Gestion & Outils OpÃ©rationnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-006`,
    description: "Kit numÃ©rique â€” Commerce & Gestion OpÃ©rationnelle. Outils et procÃ©dures pour gÃ©rer une activitÃ© commerciale : gestion des ventes, suivi des commandes, contrÃ´le des marges et relation fournisseurs. Pour commerÃ§ants, gÃ©rants de boutique et responsables commerciaux. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-007",
    name: "Pack ONG & Associations â€“ ModÃ¨les Professionnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-007`,
    description: "Kit numÃ©rique â€” ONG & Associations. ModÃ¨les professionnels pour la gestion administrative et financiÃ¨re des ONG et associations : statuts, PV d'AG, rapports d'activitÃ©s, rapports financiers et dossiers de demande de financement. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-008",
    name: "Pack Ã‰ducation â€“ Gestion Ã‰cole & Documents Administratifs",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-008`,
    description: "Kit numÃ©rique â€” Gestion Scolaire. Documents administratifs pour Ã©tablissements d'enseignement : rÃ¨glement intÃ©rieur, bulletins de notes, contrats de scolaritÃ©, emplois du temps et rapports pÃ©dagogiques. Pour directeurs d'Ã©cole et responsables administratifs. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-009",
    name: "Pack SantÃ© â€“ Gestion & ProcÃ©dures MÃ©dicales",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-009`,
    description: "Kit numÃ©rique â€” SantÃ© & ProcÃ©dures MÃ©dicales. Documents et procÃ©dures pour Ã©tablissements de santÃ© : protocoles mÃ©dicaux, fiches patients, procÃ©dures d'hygiÃ¨ne et gestion administrative des structures sanitaires. Pour directeurs de clinique et responsables mÃ©dicaux. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-010",
    name: "Pack SÃ©curitÃ© & QHSE â€“ Documents Professionnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-010`,
    description: "Kit numÃ©rique â€” SÃ©curitÃ© & QHSE. Documents professionnels pour la sÃ©curitÃ© au travail et les systÃ¨mes QHSE : plans de prÃ©vention, permis de travaux, analyses de risques et procÃ©dures d'urgence. Pour agents de sÃ©curitÃ© et responsables HSE. 5 000 FCFA.",
  },

  // â”€â”€ Bundles â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "dkits-bundle-croissance-finance",
    name: "Bundle Pack Croissance & Finance",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium â€” Croissance & Finance. Combinaison de plusieurs kits finance et business pour maximiser la croissance de votre entreprise. Inclut des ressources sur la gestion financiÃ¨re, la budgÃ©tisation, l'analyse et le dÃ©veloppement commercial. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
  {
    slug: "dkits-bundle-entreprise-securisee",
    name: "Bundle Pack Entreprise SÃ©curisÃ©e",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium â€” Entreprise SÃ©curisÃ©e. Pack combinÃ© couvrant la cybersÃ©curitÃ©, la conformitÃ© juridique, la gestion des risques et la protection des donnÃ©es. Pour dirigeants souhaitant sÃ©curiser leur entreprise sur tous les plans. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
  {
    slug: "dkits-bundle-vente-communication",
    name: "Bundle Pack Vente & Communication",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium â€” Vente & Communication. Combinaison des meilleurs kits commerciaux et marketing pour booster vos ventes et votre communication. Inclut prospection, CRM, marketing digital et rÃ©seaux sociaux. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
];

export async function POST() {
  const user = await getCurrentUser();
  if (!user || (user.role !== "ADMIN" && user.role !== "SUPERADMIN")) {
    return NextResponse.json({ error: "Non autorisÃ©" }, { status: 403 });
  }

  const branch = await prisma.branch.findUnique({ where: { slug: "ibig-digital-kits" } });
  if (!branch) {
    return NextResponse.json(
      { error: "Branche IBIG DIGITAL KITS introuvable. Synchronisez d'abord les branches." },
      { status: 404 }
    );
  }

  const knownSlugs = KITS_PRODUCTS.map((p) => p.slug);

  // Supprimer les doublons/anciens produits sans ventes
  const deleted = await prisma.product.deleteMany({
    where: {
      branchId: branch.id,
      slug: { notIn: knownSlugs },
      sales: { none: {} },
        links: { none: {} },
    },
  });

  let upserted = 0;
  for (const p of KITS_PRODUCTS) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        pricingType: p.pricingType,
        price: p.price,
        rate: p.rate,
        siteUrl: p.siteUrl,
        description: p.description,
        branchId: branch.id,
        active: true,
      },
      create: {
        slug: p.slug,
        name: p.name,
        pricingType: p.pricingType,
        price: p.price,
        rate: p.rate,
        siteUrl: p.siteUrl,
        description: p.description,
        branchId: branch.id,
        active: true,
      },
    });
    upserted++;
  }

  return NextResponse.json({
    ok: true,
    upserted,
    deleted: deleted.count,
    message: `${upserted} produits IBIG DIGITAL KITS synchronisÃ©s, ${deleted.count} doublon(s) supprimÃ©(s).`,
  });
}

