import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

const BASE = "https://kits.intermark-business.com";

const KITS_PRODUCTS = [
  // ── Innovation, IA & Multimédia ──────────────────────────────────────
  {
    slug: "dkits-inno-001",
    name: "Pack IA & Automatisation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-001`,
    description: "Kit numérique — IA & Automatisation. Ressources, prompts, workflows et modèles prêts à l'emploi pour intégrer l'intelligence artificielle dans vos processus quotidiens. Idéal pour professionnels, entrepreneurs et consultants souhaitant gagner en productivité grâce aux outils IA. Livraison numérique immédiate. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-002",
    name: "Pack Crypto & Blockchain",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-002`,
    description: "Kit numérique — Crypto & Blockchain. Ressources pédagogiques et outils pour comprendre et utiliser les cryptomonnaies et la technologie blockchain. Pour investisseurs, curieux du Web3 et professionnels de la finance souhaitant maîtriser les actifs numériques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-003",
    name: "Pack Crypto & Blockchain – Modèles & Outils",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-003`,
    description: "Kit numérique — Modèles & Outils Crypto/Blockchain. Templates, tableaux de suivi et documents opérationnels pour gérer et analyser vos investissements en cryptomonnaies et projets blockchain. Prêts à l'emploi et adaptables. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-004",
    name: "Pack Crypto, Blockchain & FinTech",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-004`,
    description: "Kit numérique — Crypto, Blockchain & FinTech. Pack complet combinant ressources IA, workflows et outils applicables aux secteurs de la finance technologique : DeFi, paiements numériques, tokenisation. Pour professionnels de la finance et entrepreneurs du secteur FinTech. 5 000 FCFA.",
  },
  {
    slug: "dkits-inno-005",
    name: "Pack Digital Business – Outils & Modèles",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INNO-005`,
    description: "Kit numérique — Digital Business. Ressources IA, prompts et workflows pour moderniser vos méthodes de travail. Modèles adaptables pour piloter une activité digitale, automatiser des tâches et accélérer votre transformation numérique. ★ 4,7 — 86 achats. 5 000 FCFA.",
  },

  // ── Informatique & Logiciels ──────────────────────────────────────────
  {
    slug: "dkits-inf-001",
    name: "Pack Informatique & Outils Digitaux",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-001`,
    description: "Kit numérique — Informatique & Outils Digitaux. Ressources, guides et modèles pour maîtriser les outils informatiques professionnels. Pour techniciens, assistants administratifs et toute personne souhaitant renforcer ses compétences numériques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-002",
    name: "Pack Cybersécurité – Protection & Gestion des Risques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-002`,
    description: "Kit numérique — Cybersécurité. Politiques, procédures et modèles pour protéger votre entreprise contre les cybermenaces. Guides de sensibilisation, checklists de sécurité et plans de réponse aux incidents. Pour DSI, responsables IT et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-003",
    name: "Pack Développeur – Modèles Tech & Documentation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-003`,
    description: "Kit numérique — Documentation Développeur. Templates techniques, modèles de cahier des charges, documentation API et guides de bonnes pratiques. Pour développeurs, chefs de projet technique et startups souhaitant structurer leurs livrables. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-004",
    name: "Pack IT – Gestion Infrastructure & Support Technique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-004`,
    description: "Kit numérique — Gestion IT. Modèles de tickets, procédures de support, plans de maintenance et tableaux de bord infrastructure. Pour responsables IT, techniciens systèmes et administrateurs réseau. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-005",
    name: "Pack Digital – Automatisation & Productivité",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-005`,
    description: "Kit numérique — Automatisation & Productivité. Workflows, modèles et outils pour automatiser vos tâches répétitives et booster votre productivité digitale. Intégrations no-code, scripts prêts à l'emploi et guides pratiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-inf-006",
    name: "Pack Création Digitale – Ressources & Templates Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=INF-006`,
    description: "Kit numérique — Création Digitale. Templates professionnels pour la création de contenus digitaux : visuels, présentations, mockups et ressources graphiques. Pour créateurs de contenu, community managers et agences digitales. 5 000 FCFA.",
  },

  // ── Commercial & Relation Client ──────────────────────────────────────
  {
    slug: "dkits-comr-001",
    name: "Pack Commercial & Prospection",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-001`,
    description: "Kit numérique — Commercial & Prospection. Scripts de vente, modèles d'emails de prospection, tableaux de suivi des leads et fiches de découverte client. Pour commerciaux, responsables des ventes et entrepreneurs souhaitant structurer leur démarche commerciale. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-002",
    name: "Pack CRM & Gestion Client",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-002`,
    description: "Kit numérique — CRM & Gestion Client. Modèles de fiches clients, tableaux de suivi, processus de fidélisation et outils de gestion de la relation client. Pour TPE, PME et équipes commerciales souhaitant professionnaliser leur suivi client. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-003",
    name: "Pack Vente – Techniques & Documents Commerciaux",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-003`,
    description: "Kit numérique — Techniques de Vente. Documents commerciaux prêts à adapter : devis, propositions commerciales, contrats de vente, argumentaires et objections. Pour toute équipe commerciale souhaitant accélérer son cycle de vente. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-004",
    name: "Pack Marketing & Publicité",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-004`,
    description: "Kit numérique — Marketing & Publicité. Plans marketing, briefs publicitaires, modèles de campagnes et outils de mesure de performance. Pour responsables marketing, agences et entrepreneurs souhaitant structurer leur stratégie de communication payante. ★ 4,7 — 64 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-comr-005",
    name: "Pack Réseaux Sociaux – Contenus & Gestion",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COMR-005`,
    description: "Kit numérique — Réseaux Sociaux. Calendriers éditoriaux, modèles de posts, stratégies de contenu et outils de gestion des réseaux sociaux. Pour community managers, entrepreneurs et marques souhaitant développer leur présence digitale. ★ 4,8 — 73 achats. 5 000 FCFA.",
  },

  // ── Communication & Marketing ─────────────────────────────────────────
  {
    slug: "dkits-com-001",
    name: "Pack Pro Médias & Communication Visuelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-001`,
    description: "Kit numérique — Médias & Communication Visuelle. Ressources et templates pour produire des contenus visuels professionnels : chartes graphiques, modèles de présentations, supports de communication. Pour communicants, chargés de communication et équipes marketing. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-002",
    name: "Kit Stratégies Marketing & Communication 360°",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-002`,
    description: "Kit numérique — Marketing & Communication 360°. Stratégies complètes couvrant communication digitale, offline et intégrée. Plans de communication, matrices de positionnement et outils de pilotage de la marque. Pour directeurs marketing et consultants en communication. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-003",
    name: "Essentiel Communication – Les Meilleures Ressources",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-003`,
    description: "Kit numérique — Essentiel Communication. Sélection des meilleures ressources en communication professionnelle : guides, templates et outils incontournables pour améliorer sa communication en entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-004",
    name: "Pack Digital – Communication & Marketing en Ligne",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-004`,
    description: "Kit numérique — Communication & Marketing en Ligne. Outils et modèles pour piloter sa présence digitale : SEO, email marketing, publicité en ligne et analytics. Pour équipes marketing et entrepreneurs souhaitant développer leur acquisition digitale. 5 000 FCFA.",
  },
  {
    slug: "dkits-com-005",
    name: "Pack Pro – Techniques de Communication en Milieu Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=COM-005`,
    description: "Kit numérique — Communication Professionnelle. Techniques et outils pour améliorer sa communication interne et externe en entreprise : prise de parole, rédaction professionnelle, conduite de réunions. ★ 4,9 — 44 achats. 5 000 FCFA.",
  },

  // ── Entrepreneuriat & Leadership ──────────────────────────────────────
  {
    slug: "dkits-bus-001",
    name: "Pack Startup – 150 Opportunités en Afrique Francophone",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-001`,
    description: "Kit numérique — 150 Opportunités Business en Afrique Francophone. Répertoire de 150 idées d'affaires viables et rentables adaptées au contexte africain, avec analyses de marché et modèles économiques. Pour entrepreneurs et porteurs de projets en Afrique. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-002",
    name: "Pack Business Plan Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-002`,
    description: "Kit numérique — Business Plan Pro. Modèles complets de business plans, études de marché, projections financières et présentations investisseurs. Pour entrepreneurs, porteurs de projets et étudiants en gestion souhaitant structurer leur projet d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-003",
    name: "Pack Entrepreneur – 50 Documents Essentiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-003`,
    description: "Kit numérique — 50 Documents Essentiels de l'Entrepreneur. Collection de documents indispensables pour créer et gérer son entreprise : statuts, contrats, modèles administratifs, outils de gestion. Pour tout entrepreneur souhaitant démarrer sur des bases solides. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-004",
    name: "Bibliothèque Entrepreneuriale – 100 Livres Incontournables",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-004`,
    description: "Kit numérique — 100 Livres de l'Entrepreneur. Sélection de 100 résumés de livres incontournables en entrepreneuriat, management, stratégie et finance. Pour leaders, dirigeants et entrepreneurs souhaitant se former rapidement sur les meilleures pratiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-bus-005",
    name: "Super Pack – 64 Modèles de Plans d'Affaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=BUS-005`,
    description: "Kit numérique — 64 Modèles de Plans d'Affaires. Collection de 64 plans d'affaires sectoriels prêts à personnaliser : commerce, services, agriculture, technologie, restauration, santé… Pour entrepreneurs, banquiers et consultants en création d'entreprise. 5 000 FCFA.",
  },

  // ── Développement Personnel ───────────────────────────────────────────
  {
    slug: "dkits-pers-001",
    name: "Kit Développement Personnel – Mindset & Performance",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-001`,
    description: "Kit numérique — Mindset & Performance. Outils et exercices pour développer un état d'esprit gagnant, fixer ses objectifs et atteindre ses ambitions personnelles et professionnelles. Pour toute personne souhaitant progresser et se surpasser. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-002",
    name: "Pack Coaching – Outils & Exercices de Transformation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-002`,
    description: "Kit numérique — Coaching & Transformation. Exercices pratiques, outils de coaching et plans d'action pour accompagner une transformation personnelle ou professionnelle profonde. Pour coachs, formateurs et particuliers en démarche de développement. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-003",
    name: "Pack Motivation – 50 Livres Résumés + Outils",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-003`,
    description: "Kit numérique — Motivation & Réussite. 50 résumés de livres de motivation et développement personnel accompagnés d'outils pratiques pour passer à l'action. Pour toute personne souhaitant s'inspirer des meilleurs auteurs et appliquer leurs enseignements. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-004",
    name: "Pack Carrière – CV, Lettres & Préparation Entretien",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-004`,
    description: "Kit numérique — Carrière & Emploi. Modèles de CV professionnels, lettres de motivation percutantes et guides de préparation aux entretiens d'embauche. Pour étudiants, demandeurs d'emploi et professionnels en reconversion souhaitant décrocher leur prochain poste. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-005",
    name: "Kit Confiance en Soi – Exercices & Outils Psychologiques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-005`,
    description: "Kit numérique — Confiance en Soi. Exercices psychologiques, techniques d'affirmation de soi et plans d'action pour développer une confiance solide dans la vie personnelle et professionnelle. 5 000 FCFA.",
  },
  {
    slug: "dkits-pers-006",
    name: "Pack Bien-être & Gestion du Stress",
    pricingType: "PRODUCT",
    price: 2000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PERS-006`,
    description: "Kit numérique — Bien-être & Gestion du Stress. Techniques de relaxation, routines anti-stress et outils pour mieux gérer la pression au quotidien. Pour toute personne souhaitant améliorer son équilibre de vie. 2 000 FCFA.",
  },

  // ── Excel & Tableaux ──────────────────────────────────────────────────
  {
    slug: "dkits-exc-001",
    name: "Pack Excel Premium – 50 Tableaux Automatisés",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-001`,
    description: "Kit numérique — Excel Premium. 50 tableaux Excel automatisés prêts à l'emploi couvrant : suivi des ventes, gestion de stock, plannings, tableaux de bord et indicateurs de performance. Pour toute entreprise souhaitant gagner du temps sur ses reportings. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-002",
    name: "Pack Excel RH & Paie",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-002`,
    description: "Kit numérique — Excel RH & Paie. Fichiers Excel automatisés pour la gestion RH : calcul des salaires, suivi des congés, plannings du personnel, indicateurs RH et déclarations sociales. Pour gestionnaires RH, DRH et comptables de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-003",
    name: "Pack Excel Finance & Budgets",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-003`,
    description: "Kit numérique — Excel Finance & Budgets. Modèles Excel pour la gestion financière : budget prévisionnel, plan de trésorerie, analyse des écarts, bilans simplifiés et tableaux de bord financiers. Pour directeurs financiers, comptables et entrepreneurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-exc-004",
    name: "Pack Data & Reporting – Tableaux Intelligents",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=EXC-004`,
    description: "Kit numérique — Data & Reporting. Tableaux de bord intelligents et fichiers de reporting automatisés pour piloter votre activité avec des indicateurs clés. Pour analystes, contrôleurs de gestion et managers souhaitant visualiser leurs données efficacement. 5 000 FCFA.",
  },

  // ── Finance, Audit & Comptabilité ─────────────────────────────────────
  {
    slug: "dkits-fin-001",
    name: "Pack Comptabilité Générale Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-001`,
    description: "Kit numérique — Comptabilité Générale. Documents, modèles et guides pratiques pour la comptabilité générale conforme SYSCOHADA : journaux, grands livres, états financiers et procédures de clôture. Pour comptables et gestionnaires d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-002",
    name: "Pack Audit & Contrôle Interne",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-002`,
    description: "Kit numérique — Audit & Contrôle Interne. Programmes d'audit, questionnaires de contrôle interne, matrices des risques et modèles de rapports d'audit. Pour auditeurs internes, contrôleurs de gestion et responsables qualité. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-003",
    name: "Pack Finance & Gestion Budgétaire",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-003`,
    description: "Kit numérique — Finance & Gestion Budgétaire. Outils complets pour la gestion financière et budgétaire : prévisions, analyses de rentabilité, tableaux de bord financiers et modèles de reporting. Pour responsables financiers et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-004",
    name: "Pack Microfinance – Gestion & Conformité",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-004`,
    description: "Kit numérique — Microfinance. Politiques, procédures et outils de gestion pour institutions de microfinance : gestion du crédit, épargne, conformité réglementaire et reporting. Pour gérants d'IMF, coopératives et mutuelles d'épargne. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-005",
    name: "Pack Gestion Budgétaire & Prévisionnelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-005`,
    description: "Kit numérique — Budget & Prévisions. Modèles et méthodologies pour élaborer, suivre et analyser les budgets d'entreprise. Inclut budget de trésorerie, analyse des écarts et plans de financement. Pour contrôleurs de gestion et directeurs financiers. 5 000 FCFA.",
  },
  {
    slug: "dkits-fin-006",
    name: "Pack Trésorerie & Liquidité",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=FIN-006`,
    description: "Kit numérique — Trésorerie & Liquidité. Outils de gestion de trésorerie : tableaux de flux, prévisions de liquidité, rapprochements bancaires et procédures de gestion du cash. Pour trésoriers, responsables financiers et gérants de PME. 5 000 FCFA.",
  },

  // ── Gestion & Administration ──────────────────────────────────────────
  {
    slug: "dkits-gest-001",
    name: "Pack Manager – Leadership & Organisation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-001`,
    description: "Kit numérique — Leadership & Organisation. Outils pour managers : délégation, conduite du changement, animation d'équipe, gestion des priorités et développement du leadership. Pour managers, chefs d'équipe et directeurs souhaitant renforcer leur posture de leader. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-002",
    name: "Pack Manager – Ressources & Outils de Pilotage",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-002`,
    description: "Kit numérique — Pilotage Managérial. Tableaux de bord, indicateurs de performance et outils opérationnels pour piloter une équipe et atteindre ses objectifs. Pour responsables d'équipe et directeurs de département. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-003",
    name: "Pack Pro – Gestion des Stocks et Inventaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-003`,
    description: "Kit numérique — Gestion des Stocks. Modèles de suivi des stocks, fiches d'inventaire, procédures de réapprovisionnement et tableaux de bord logistiques. Pour gestionnaires de stocks, magasiniers et responsables supply chain. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-004",
    name: "Kit Finances – Comptabilité & Outils de Gestion",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-004`,
    description: "Kit numérique — Comptabilité & Gestion. Collection d'outils financiers et comptables pour la gestion quotidienne d'une entreprise : suivi des dépenses, facturation, rapprochements et états financiers simplifiés. Pour TPE, PME et entrepreneurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-005",
    name: "Kit RH – Gestion des Ressources Humaines",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-005`,
    description: "Kit numérique — Gestion RH. Documents et outils complets pour la gestion des ressources humaines : contrats de travail, fiches de poste, procédures disciplinaires, évaluations et politiques RH. Pour DRH, gestionnaires RH et dirigeants de PME. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-006",
    name: "Kit Gestion de Projet – Planification & Évaluation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-006`,
    description: "Kit numérique — Gestion de Projet. Outils de planification, suivi et évaluation de projets : cadres logiques, diagrammes de Gantt, matrices de risques et rapports d'avancement. Pour chefs de projet, coordinateurs et consultants. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-007",
    name: "Pack Chef de Projet – Méthodologie & Outils Essentiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-007`,
    description: "Kit numérique — Chef de Projet. Méthodologies et outils essentiels pour mener des projets de A à Z : charte projet, WBS, planning, gestion des risques et clôture. Pour chefs de projet certifiés ou en cours de certification. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-008",
    name: "Pack Risk Manager – Anticipation & Pilotage des Risques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-008`,
    description: "Kit numérique — Risk Management. Outils d'identification, d'évaluation et de pilotage des risques : cartographies, matrices de criticité, plans de continuité et procédures ISO 31000. Pour risk managers, auditeurs et dirigeants d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-009",
    name: "Mini Pack – Budgétisation & Gestion Prévisionnelle",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-009`,
    description: "Kit numérique — Budgétisation. Modèles simplifiés et guides pratiques pour construire un budget prévisionnel et suivre ses réalisations. Accessible aux non-financiers. Pour chefs de service et responsables opérationnels. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-010",
    name: "Kit Pro – Protection Sociale & Droit du Travail",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-010`,
    description: "Kit numérique — Protection Sociale & Droit du Travail. Documents de référence sur la législation du travail, les obligations sociales et les droits des employés en Afrique francophone. Pour DRH, juristes d'entreprise et gestionnaires du personnel. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-011",
    name: "Pack Carrière – Emploi, Rédaction & Insertion Pro",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-011`,
    description: "Kit numérique — Emploi & Insertion Professionnelle. Outils complets pour la recherche d'emploi : CV, lettres de motivation, préparation aux entretiens et stratégies de réseautage. Pour étudiants et jeunes professionnels en insertion. 5 000 FCFA.",
  },
  {
    slug: "dkits-gest-012",
    name: "Pack Assistant Pro – Secrétariat & Bureautique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=GEST-012`,
    description: "Kit numérique — Secrétariat & Bureautique. Modèles de correspondance professionnelle, procédures d'accueil, gestion du courrier et outils bureautiques. Pour assistantes de direction, secrétaires et office managers. 5 000 FCFA.",
  },

  // ── Juridique & Conformité ────────────────────────────────────────────
  {
    slug: "dkits-jur-001",
    name: "Pack Juridique & Gestion Administrative de l'Entreprise",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-001`,
    description: "Kit numérique — Juridique & Administration. Documents juridiques et administratifs essentiels pour la gestion d'entreprise : statuts, procès-verbaux, délibérations, modèles de contrats courants. Pour dirigeants de PME et juristes d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-002",
    name: "Pack Droit des Affaires & Modèles Juridiques",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-002`,
    description: "Kit numérique — Droit des Affaires. Modèles juridiques pour les activités commerciales : contrats commerciaux, CGV, baux professionnels, protocoles d'accord OHADA. Pour avocats, juristes et chefs d'entreprise en Afrique. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-003",
    name: "Pack Legal Pro – 200 Contrats Banque & Assurance",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-003`,
    description: "Kit numérique — 200 Contrats Banque & Assurance. Collection de 200 modèles de contrats et documents juridiques du secteur bancaire et assurantiel. Pour juristes de banques, compagnies d'assurance et établissements financiers. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-004",
    name: "Pack Légal – 125 Contrats Immobiliers",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-004`,
    description: "Kit numérique — 125 Contrats Immobiliers. Collection de 125 modèles de contrats pour les transactions immobilières : vente, location, bail commercial, mandat de gestion, promesse de vente. Pour agents immobiliers, notaires et promoteurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-005",
    name: "Pack Légal Express – 100 Contrats BTP",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-005`,
    description: "Kit numérique — 100 Contrats BTP. Collection de 100 modèles de contrats pour le secteur du bâtiment et des travaux publics : contrats de construction, sous-traitance, marchés de travaux, réceptions et garanties. Pour entrepreneurs BTP et maîtres d'ouvrage. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-006",
    name: "Pack Avocat & Conseiller Juridique",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-006`,
    description: "Kit numérique — Avocat & Conseil Juridique. Outils et modèles pour la pratique juridique : consultations, conclusions, conventions honoraires, modèles de plaidoiries et lettres juridiques. Pour avocats, juristes et conseillers juridiques. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-007",
    name: "Pack PME – Droit, Conformité & Réglementation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-007`,
    description: "Kit numérique — PME & Conformité. Outils de conformité réglementaire pour PME : politique de conformité, registres légaux obligatoires, procédures RGPD et obligations fiscales. Pour dirigeants de PME soucieux de leur conformité. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-008",
    name: "Pack Juridique – Contrats Professionnels & Documents Officiels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-008`,
    description: "Kit numérique — Contrats Professionnels. Grande collection de contrats professionnels et documents officiels tous secteurs confondus. Pour toute entreprise souhaitant disposer d'une base documentaire juridique solide. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-009",
    name: "Pack Droit Social & Gestion du Personnel",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-009`,
    description: "Kit numérique — Droit Social. Documents et procédures relatifs au droit du travail et à la gestion du personnel : règlement intérieur, sanctions disciplinaires, licenciements et contrats de travail. Pour DRH, juristes et dirigeants d'entreprise. 5 000 FCFA.",
  },
  {
    slug: "dkits-jur-010",
    name: "Pack Conformité – Risques, Audit & Réglementation",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=JUR-010`,
    description: "Kit numérique — Conformité & Réglementation. Outils complets pour la conformité : politiques anticorruption, procédures KYC, plans de continuité d'activité et audit de conformité. Pour compliance officers et directions générales. 5 000 FCFA.",
  },

  // ── Projets & Appels d'Offres ─────────────────────────────────────────
  {
    slug: "dkits-prj-001",
    name: "Pack Projets – Modèles de Gestion & Suivi",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-001`,
    description: "Kit numérique — Gestion & Suivi de Projets. Modèles opérationnels pour planifier, exécuter et clore des projets : tableaux de bord, rapports d'avancement, plans d'action et bilans. Pour chefs de projet et coordinateurs. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-002",
    name: "Pack Appels d'Offres – Dossiers & Modèles",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-002`,
    description: "Kit numérique — Appels d'Offres. Dossiers types et modèles pour répondre aux appels d'offres publics et privés : offre technique, offre financière, note méthodologique et références. Pour entreprises soumissionnaires et consultants. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-003",
    name: "Pack ONG – Gestion de Projets Humanitaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-003`,
    description: "Kit numérique — ONG & Humanitaire. Outils de gestion de projets pour ONG : proposition de projet, cadre logique, rapports bailleurs, suivi-évaluation et procédures de passation de marchés. Pour coordinateurs et chargés de projets humanitaires. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-004",
    name: "Pack ONG & Projets Humanitaires",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-004`,
    description: "Kit numérique — ONG & Projets Humanitaires. Collection complète d'outils pour la gestion et le financement des projets humanitaires et de développement. Inclut politiques organisationnelles, outils de collecte de fonds et modèles de rapports. ★ 4,8 — 109 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-005",
    name: "Pack Gestion des Risques & Conformité",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-005`,
    description: "Kit numérique — Gestion des Risques & Conformité. Outils pour identifier, évaluer et maîtriser les risques en entreprise et assurer la conformité réglementaire. Cartographies, registres de risques et plans de traitement. ★ 4,9 — 32 achats. 5 000 FCFA.",
  },
  {
    slug: "dkits-prj-006",
    name: "Pack Management & Leadership Opérationnel",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRJ-006`,
    description: "Kit numérique — Management Opérationnel. Outils pour passer plus vite de l'idée à l'exécution : plans d'action, matrices de décision, outils de pilotage et techniques de management d'équipe. Pour managers et directeurs opérationnels. ★ 4,6 — 41 achats. 5 000 FCFA.",
  },

  // ── Secteurs Professionnels ───────────────────────────────────────────
  {
    slug: "dkits-pro-001",
    name: "Pack QHSE Premium",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-001`,
    description: "Kit numérique — QHSE Premium. Documents et procédures pour les systèmes de management Qualité, Hygiène, Sécurité et Environnement : politique QHSE, plans d'inspection, fiches de sécurité et rapports d'accidents. Pour responsables QHSE et auditeurs ISO. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-002",
    name: "Pack Logistique & Supply Chain",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-002`,
    description: "Kit numérique — Logistique & Supply Chain. Procédures, modèles et tableaux de bord pour la gestion de la chaîne logistique : réception, stockage, expédition, transport et suivi des fournisseurs. Pour logisticiens et responsables supply chain. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-003",
    name: "Pack BTP & Chantier",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-003`,
    description: "Kit numérique — BTP & Chantier. Documents opérationnels pour la gestion de chantier : plans d'installation, rapports de chantier, fiches de pointage, suivi des travaux et réception provisoire. Pour conducteurs de travaux et chefs de chantier. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-004",
    name: "Pack Immobilier – Gestion & Location",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-004`,
    description: "Kit numérique — Immobilier. Documents pour la gestion immobilière et locative : baux d'habitation, contrats de location, états des lieux, quittances et modèles de vente. Pour agents immobiliers, propriétaires bailleurs et gestionnaires de biens. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-005",
    name: "Pack Hôtel – Tourisme & Hébergement",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-005`,
    description: "Kit numérique — Hôtellerie & Tourisme. Procédures opérationnelles, fiches de poste, check-lists et outils de gestion pour établissements hôteliers et touristiques. Pour directeurs d'hôtels, managers de réception et responsables de la restauration. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-006",
    name: "Pack Commerce – Gestion & Outils Opérationnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-006`,
    description: "Kit numérique — Commerce & Gestion Opérationnelle. Outils et procédures pour gérer une activité commerciale : gestion des ventes, suivi des commandes, contrôle des marges et relation fournisseurs. Pour commerçants, gérants de boutique et responsables commerciaux. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-007",
    name: "Pack ONG & Associations – Modèles Professionnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-007`,
    description: "Kit numérique — ONG & Associations. Modèles professionnels pour la gestion administrative et financière des ONG et associations : statuts, PV d'AG, rapports d'activités, rapports financiers et dossiers de demande de financement. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-008",
    name: "Pack Éducation – Gestion École & Documents Administratifs",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-008`,
    description: "Kit numérique — Gestion Scolaire. Documents administratifs pour établissements d'enseignement : règlement intérieur, bulletins de notes, contrats de scolarité, emplois du temps et rapports pédagogiques. Pour directeurs d'école et responsables administratifs. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-009",
    name: "Pack Santé – Gestion & Procédures Médicales",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-009`,
    description: "Kit numérique — Santé & Procédures Médicales. Documents et procédures pour établissements de santé : protocoles médicaux, fiches patients, procédures d'hygiène et gestion administrative des structures sanitaires. Pour directeurs de clinique et responsables médicaux. 5 000 FCFA.",
  },
  {
    slug: "dkits-pro-010",
    name: "Pack Sécurité & QHSE – Documents Professionnels",
    pricingType: "PRODUCT",
    price: 5000,
    rate: 15,
    siteUrl: `${BASE}/kit.php?code=PRO-010`,
    description: "Kit numérique — Sécurité & QHSE. Documents professionnels pour la sécurité au travail et les systèmes QHSE : plans de prévention, permis de travaux, analyses de risques et procédures d'urgence. Pour agents de sécurité et responsables HSE. 5 000 FCFA.",
  },

  // ── Bundles ───────────────────────────────────────────────────────────
  {
    slug: "dkits-bundle-croissance-finance",
    name: "Bundle Pack Croissance & Finance",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium — Croissance & Finance. Combinaison de plusieurs kits finance et business pour maximiser la croissance de votre entreprise. Inclut des ressources sur la gestion financière, la budgétisation, l'analyse et le développement commercial. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
  {
    slug: "dkits-bundle-entreprise-securisee",
    name: "Bundle Pack Entreprise Sécurisée",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium — Entreprise Sécurisée. Pack combiné couvrant la cybersécurité, la conformité juridique, la gestion des risques et la protection des données. Pour dirigeants souhaitant sécuriser leur entreprise sur tous les plans. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
  {
    slug: "dkits-bundle-vente-communication",
    name: "Bundle Pack Vente & Communication",
    pricingType: "PRODUCT",
    price: 9000,
    rate: 15,
    siteUrl: `${BASE}/catalogue.php`,
    description: "Bundle Premium — Vente & Communication. Combinaison des meilleurs kits commerciaux et marketing pour booster vos ventes et votre communication. Inclut prospection, CRM, marketing digital et réseaux sociaux. Valeur : 40 000 FCFA. 9 000 FCFA.",
  },
];

export async function POST() {
  const user = await getCurrentUser();
  if (!user || (user.role !== "ADMIN" && user.role !== "SUPERADMIN")) {
    return NextResponse.json({ error: "Non autorisé" }, { status: 403 });
  }

  const branch = await prisma.branch.findUnique({ where: { slug: "ibig-digital-kits" } });
  if (!branch) {
    return NextResponse.json(
      { error: "Branche IBIG DIGITAL KITS introuvable. Synchronisez d'abord les branches." },
      { status: 404 }
    );
  }

  const knownSlugs = KITS_PRODUCTS.map((p) => p.slug);

  // Supprimer les doublons/anciens produits sans ventes
  const deleted = await prisma.product.deleteMany({
    where: {
      branchId: branch.id,
      slug: { notIn: knownSlugs },
      sales: { none: {} },
    },
  });

  let upserted = 0;
  for (const p of KITS_PRODUCTS) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        pricingType: p.pricingType,
        price: p.price,
        rate: p.rate,
        siteUrl: p.siteUrl,
        description: p.description,
        branchId: branch.id,
        active: true,
      },
      create: {
        slug: p.slug,
        name: p.name,
        pricingType: p.pricingType,
        price: p.price,
        rate: p.rate,
        siteUrl: p.siteUrl,
        description: p.description,
        branchId: branch.id,
        active: true,
      },
    });
    upserted++;
  }

  return NextResponse.json({
    ok: true,
    upserted,
    deleted: deleted.count,
    message: `${upserted} produits IBIG DIGITAL KITS synchronisés, ${deleted.count} doublon(s) supprimé(s).`,
  });
}
