import { NextResponse } from "next/server";
import { isSyncAuthorized } from "@/lib/sync-auth";
import { syncBranchWithFeed } from "@/lib/catalog-feed";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const BASE = "https://intermark-business.com/immo";

const IMMO_PRODUCTS = [
  // ── Gestion Locative ──────────────────────────────────────────────────
  {
    slug: "immo-gestion-locative",
    name: "Gestion Locative Complète",
    pricingType: "SERVICE",
    price: 30000,
    rate: 50,
    siteUrl: BASE,
    description: "Gestion locative intégrale de votre bien immobilier : recherche et sélection du locataire, rédaction du bail, état des lieux d'entrée et de sortie, encaissement des loyers, suivi des réparations et reversement mensuel au propriétaire. Pour propriétaires bailleurs souhaitant valoriser leur patrimoine sans contrainte. À partir de 30 000 FCFA/mois ou 8% du loyer. Commission affilié : 1 mois de commission d'agence.",
  },
  {
    slug: "immo-recherche-locataire",
    name: "Recherche & Sélection de Locataire",
    pricingType: "SERVICE",
    price: 50000,
    rate: 10,
    siteUrl: BASE,
    description: "Recherche et sélection rigoureuse d'un locataire solvable et sérieux : diffusion de l'annonce, visites accompagnées, vérification des dossiers (revenus, références), sélection finale et rédaction du contrat de bail. Pour propriétaires souhaitant louer rapidement et en toute sécurité. À partir de 50 000 FCFA.",
  },
  {
    slug: "immo-etat-des-lieux",
    name: "État des Lieux",
    pricingType: "SERVICE",
    price: 25000,
    rate: 10,
    siteUrl: BASE,
    description: "Réalisation d'états des lieux d'entrée et de sortie contradictoires et détaillés : constat photographique, rapport écrit signé par les deux parties, document légalement opposable en cas de litige. Pour propriétaires et locataires souhaitant protéger leurs intérêts. À partir de 25 000 FCFA.",
  },
  {
    slug: "immo-recouvrement-loyers",
    name: "Recouvrement de Loyers Impayés",
    pricingType: "SERVICE",
    price: 50000,
    rate: 10,
    siteUrl: BASE,
    description: "Assistance au recouvrement de loyers impayés : mise en demeure, négociation avec le locataire défaillant, procédures amiables et accompagnement dans les démarches juridiques si nécessaire. Pour propriétaires confrontés à des loyers en retard ou à des locataires mauvais payeurs. À partir de 50 000 FCFA.",
  },
  {
    slug: "immo-syndic-copropriete",
    name: "Syndic de Copropriété",
    pricingType: "SERVICE",
    price: 50000,
    rate: 10,
    siteUrl: BASE,
    description: "Gestion de copropriété pour immeubles collectifs : administration des parties communes, convocation et tenue des assemblées générales, exécution des décisions, suivi des travaux d'entretien, collecte des charges et comptabilité de la copropriété. Pour syndicats de copropriétaires souhaitant déléguer la gestion à un professionnel. À partir de 50 000 FCFA/mois selon le nombre de lots.",
  },
  {
    slug: "immo-gestion-parc-entreprise",
    name: "Gestion de Parc Immobilier Entreprise",
    pricingType: "SERVICE",
    price: 100000,
    rate: 8,
    siteUrl: BASE,
    description: "Gestion complète du parc immobilier d'une entreprise ou d'un investisseur multi-actifs : suivi des baux, optimisation des loyers, maintenance préventive, gestion des sinistres, reporting trimestriel et conseil en arbitrage patrimonial. Pour entreprises, groupes et investisseurs institutionnels. Sur devis à partir de 100 000 FCFA/mois.",
  },

  // ── Transactions Immobilières ─────────────────────────────────────────
  {
    slug: "immo-vente-bien",
    name: "Vente de Bien Immobilier",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement complet pour la vente de votre bien immobilier : estimation du prix de marché, diffusion de l'annonce, organisation des visites, négociation avec les acquéreurs et suivi jusqu'à la signature chez le notaire. Commission : 5% du prix de vente (minimum 200 000 FCFA). Pour propriétaires souhaitant vendre rapidement et au meilleur prix.",
  },
  {
    slug: "immo-achat-bien",
    name: "Accompagnement Achat Immobilier",
    pricingType: "SERVICE",
    price: 150000,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement personnalisé pour l'achat d'un bien immobilier : définition du cahier des charges, recherche ciblée, visites, négociation du prix, vérification des titres de propriété et suivi jusqu'à la signature. Pour acquéreurs souhaitant acheter en toute sécurité sans mauvaise surprise. À partir de 150 000 FCFA.",
  },
  {
    slug: "immo-transaction-terrain",
    name: "Transaction Foncière & Vente de Terrain",
    pricingType: "SERVICE",
    price: 150000,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement pour l'achat et la vente de terrains : vérification du statut foncier, contrôle des titres (ACD, titre foncier), bornage, négociation et formalités de transfert de propriété. Pour acheteurs et vendeurs de terrains souhaitant sécuriser leur transaction foncière en Côte d'Ivoire. À partir de 150 000 FCFA.",
  },
  {
    slug: "immo-location-commerciale",
    name: "Location de Locaux Commerciaux & Bureaux",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Recherche et mise en location de locaux commerciaux, bureaux et entrepôts : identification des locaux disponibles selon vos critères, visites, négociation des conditions du bail commercial et accompagnement jusqu'à la remise des clés. Pour entrepreneurs et entreprises cherchant des locaux professionnels. À partir de 100 000 FCFA.",
  },
  {
    slug: "immo-diagnostic-immobilier",
    name: "Diagnostic Technique de Bien Immobilier",
    pricingType: "SERVICE",
    price: 75000,
    rate: 10,
    siteUrl: BASE,
    description: "Diagnostic technique complet d'un bien avant achat ou mise en vente : inspection de la structure, toiture, électricité, plomberie, humidité et état général. Rapport écrit détaillé avec cotation des travaux à prévoir. Pour acquéreurs et vendeurs souhaitant éviter les mauvaises surprises. À partir de 75 000 FCFA.",
  },
  {
    slug: "immo-visite-virtuelle",
    name: "Visite Virtuelle 360° & Photographie Immobilière",
    pricingType: "SERVICE",
    price: 80000,
    rate: 10,
    siteUrl: BASE,
    description: "Mise en valeur professionnelle de votre bien : shooting photo haute résolution, visite virtuelle interactive à 360° consultable depuis un smartphone, diffusion sur les plateformes immobilières. Un bien bien photographié se vend ou se loue 40% plus vite. Pour agences, promoteurs et propriétaires. À partir de 80 000 FCFA.",
  },
  {
    slug: "immo-recherche-financement",
    name: "Recherche de Financement Immobilier",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement pour obtenir un financement immobilier : montage du dossier de prêt, mise en relation avec les banques partenaires (SGBCI, BNI, Orabank, microfinance), négociation des conditions et suivi jusqu'au déblocage des fonds. Pour acquéreurs et porteurs de projets immobiliers souhaitant un financement adapté. À partir de 100 000 FCFA.",
  },
  {
    slug: "immo-home-staging",
    name: "Home Staging & Valorisation du Bien",
    pricingType: "SERVICE",
    price: 75000,
    rate: 10,
    siteUrl: BASE,
    description: "Mise en valeur de votre bien avant la vente ou la mise en location : conseils de décoration, réorganisation de l'espace, petits travaux de rafraîchissement, shooting photo professionnel et visite virtuelle. Un bien bien présenté se vend plus vite et plus cher. Pour propriétaires souhaitant maximiser l'attractivité de leur bien. À partir de 75 000 FCFA.",
  },

  // ── Conseil & Investissement Immobilier ───────────────────────────────
  {
    slug: "immo-conseil-investissement",
    name: "Conseil en Investissement Immobilier",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Conseil stratégique pour vos investissements immobiliers : analyse du marché local, identification des zones à fort potentiel (Riviera, Cocody, Bingerville, zones en expansion), évaluation de la rentabilité locative et structuration du plan de financement. Pour investisseurs souhaitant placer leur argent intelligemment. À partir de 100 000 FCFA.",
  },
  {
    slug: "immo-expertise-evaluation",
    name: "Expertise & Évaluation Immobilière",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Estimation professionnelle de la valeur vénale ou locative d'un bien immobilier : visite du bien, analyse comparative du marché, rapport d'expertise détaillé et valeur certifiée. Pour propriétaires, acquéreurs, banques, successions et procédures judiciaires nécessitant une évaluation fiable. À partir de 100 000 FCFA.",
  },
  {
    slug: "immo-audit-patrimoine",
    name: "Audit de Patrimoine Immobilier",
    pricingType: "SERVICE",
    price: 175000,
    rate: 10,
    siteUrl: BASE,
    description: "Audit complet de votre patrimoine immobilier : inventaire des biens, évaluation globale, analyse de la rentabilité de chaque actif, identification des optimisations fiscales et recommandations stratégiques. Pour particuliers et entreprises souhaitant optimiser la gestion de leur parc immobilier. À partir de 175 000 FCFA.",
  },
  {
    slug: "immo-montage-projet-immobilier",
    name: "Montage de Projet Immobilier",
    pricingType: "SERVICE",
    price: 300000,
    rate: 8,
    siteUrl: BASE,
    description: "Accompagnement complet pour le montage d'un projet immobilier : étude de faisabilité, business plan immobilier, recherche de financement, coordination des intervenants (architecte, notaire, entrepreneur) et suivi de la réalisation. Pour promoteurs et investisseurs développant un projet immobilier de A à Z. Sur devis à partir de 300 000 FCFA.",
  },
  {
    slug: "immo-optimisation-fiscale",
    name: "Optimisation Fiscale Immobilière",
    pricingType: "SERVICE",
    price: 150000,
    rate: 10,
    siteUrl: BASE,
    description: "Conseil en optimisation fiscale pour propriétaires et investisseurs immobiliers : analyse de la situation fiscale, stratégies de réduction de l'imposition sur les revenus fonciers, régimes d'exonération applicables et structuration juridique adaptée (SCI, holding). Pour propriétaires souhaitant alléger leur fiscalité légalement. À partir de 150 000 FCFA.",
  },

  // ── Architecture & Plans ──────────────────────────────────────────────
  {
    slug: "immo-plans-architecture",
    name: "Plans d'Architecture & Permis de Construire",
    pricingType: "SERVICE",
    price: 250000,
    rate: 8,
    siteUrl: BASE,
    description: "Conception des plans d'architecture et constitution du dossier de permis de construire : plans de masse, coupes, façades, plans d'exécution et dossier administratif déposé auprès des services compétents. Fourchette indicative : 250 000 – 800 000 FCFA selon la surface et la complexité du projet. Pour particuliers et promoteurs souhaitant construire en conformité avec la réglementation.",
  },
  {
    slug: "immo-conception-3d",
    name: "Conception 3D & Maquette Virtuelle",
    pricingType: "SERVICE",
    price: 150000,
    rate: 10,
    siteUrl: BASE,
    description: "Modélisation 3D réaliste de votre future construction ou rénovation : rendu extérieur, intérieur, visite virtuelle du projet et plans cotés. Permet de visualiser le résultat final avant le début des travaux et de valider les choix architecturaux. Fourchette : 150 000 – 500 000 FCFA selon la taille du projet. Pour particuliers et promoteurs.",
  },
  {
    slug: "immo-dessin-technique",
    name: "Dessin Technique & Plans d'Exécution",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Réalisation de plans techniques détaillés pour l'exécution des travaux : plans de coffrage, d'armatures, de réseaux (eau, électricité, assainissement), coupes et détails constructifs. Indispensables pour la mise en œuvre sur le chantier. Fourchette : 100 000 – 400 000 FCFA selon la complexité. Pour maîtres d'ouvrage et entreprises de construction.",
  },
  {
    slug: "immo-suivi-maitrise-oeuvre",
    name: "Maîtrise d'Œuvre & Suivi de Chantier",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Direction et contrôle de l'exécution des travaux de construction ou de rénovation : coordination des corps de métiers, vérification de la conformité aux plans, contrôle des matériaux, respect du planning et des budgets, réception des travaux. Honoraires : 5% à 10% du montant des travaux selon l'envergure. Pour maîtres d'ouvrage souhaitant déléguer la gestion technique du chantier. Sur devis.",
  },
  {
    slug: "immo-etude-sol-topographie",
    name: "Étude de Sol & Topographie",
    pricingType: "SERVICE",
    price: 200000,
    rate: 8,
    siteUrl: BASE,
    description: "Étude géotechnique du sol et levé topographique de votre terrain : sondages, analyse de la portance du sol, détermination du type de fondation adapté et relevé des niveaux altimétrique. Obligatoire avant toute construction sérieuse pour éviter les désordres structurels. Fourchette : 200 000 – 600 000 FCFA selon la superficie. Sur devis.",
  },

  // ── Construction Neuve ────────────────────────────────────────────────
  {
    slug: "immo-construction-villa",
    name: "Construction de Villa & Maison Individuelle",
    pricingType: "SERVICE",
    price: 0,
    rate: 5,
    siteUrl: BASE,
    description: "Construction clé en main de votre villa ou maison individuelle : gros œuvre, second œuvre et finitions. Fourchette indicative : 80 000 à 150 000 FCFA/m² selon le standing et les matériaux choisis (soit 8 000 000 à 15 000 000 FCFA pour 100 m²). Délai moyen : 6 à 18 mois selon la taille. Inclut les plans, le permis de construire et le suivi de chantier. Sur devis après visite du terrain.",
  },
  {
    slug: "immo-construction-immeuble",
    name: "Construction d'Immeuble & Bâtiment Collectif",
    pricingType: "SERVICE",
    price: 0,
    rate: 5,
    siteUrl: BASE,
    description: "Construction d'immeuble résidentiel, de bureaux ou à usage mixte : études, fondations spéciales, structure béton armé, second œuvre et équipements techniques (ascenseur, groupe électrogène, groupe de surpression). Budget indicatif selon les niveaux et finitions — sur devis après étude de faisabilité. Pour promoteurs et investisseurs institutionnels.",
  },
  {
    slug: "immo-construction-batiment-commercial",
    name: "Construction de Bâtiment Commercial & Industriel",
    pricingType: "SERVICE",
    price: 0,
    rate: 5,
    siteUrl: BASE,
    description: "Construction de locaux commerciaux, entrepôts, usines ou infrastructures hôtelières : structure métal ou béton, bardage, dalle technique, installations spécifiques et conformité aux normes sectorielles. Fourchette très variable selon la destination et l'envergure — sur devis après cahier des charges. Pour entrepreneurs et groupes souhaitant développer leurs actifs immobiliers professionnels.",
  },
  {
    slug: "immo-construction-cloture",
    name: "Construction de Clôture & Mur de Soutènement",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Réalisation de clôtures en parpaings enduits, briques ou agglos, murs de soutènement et portails. Fourchette indicative : 35 000 à 80 000 FCFA/ml selon la hauteur et les finitions. Sécurisez votre terrain ou propriété avec une clôture solide et esthétique. Sur devis après métrés sur place.",
  },

  // ── Rénovation & Travaux ──────────────────────────────────────────────
  {
    slug: "immo-renovation-rehabilitation",
    name: "Rénovation & Réhabilitation de Bâtiment",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Travaux complets de rénovation et remise en état d'un bien immobilier : démolition partielle, reprise de structure, redistribution des espaces, remplacement des réseaux (eau, électricité), finitions et décoration. Fourchette indicative : 30 000 à 80 000 FCFA/m² selon l'état initial et le niveau de finition souhaité. Sur devis après visite.",
  },
  {
    slug: "immo-extension-batiment",
    name: "Extension & Surélévation de Bâtiment",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Agrandissement de votre maison ou bâtiment par extension horizontale ou surélévation : étude de faisabilité structurelle, plans, dossier de permis de construire modificatif et réalisation des travaux. Solution idéale pour accroître la surface habitable sans déménager. Sur devis selon la surface et la nature des travaux.",
  },
  {
    slug: "immo-amenagement-interieur",
    name: "Aménagement Intérieur & Décoration",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Conception et réalisation complète de l'aménagement intérieur de votre maison, bureau ou commerce : plans d'aménagement, choix des matériaux, coordination des artisans, pose des équipements et décoration finale. Fourchette : 15 000 à 50 000 FCFA/m² selon le standing. Pour particuliers et professionnels souhaitant un intérieur sur mesure. Sur devis.",
  },

  // ── Corps d'État Secondaires (BTP) ────────────────────────────────────
  {
    slug: "immo-peinture-batiment",
    name: "Travaux de Peinture Intérieure & Extérieure",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Travaux de peinture professionnelle pour bâtiments résidentiels et commerciaux : préparation des surfaces, application de sous-couche, peinture acrylique ou glycéro. Fourchette indicative : 3 000 à 8 000 FCFA/m² selon le type de peinture et le nombre de couches. Sur devis après métrés. Délai : selon le chantier.",
  },
  {
    slug: "immo-carrelage-revetements",
    name: "Pose de Carrelage & Revêtements de Sol",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Pose de carrelage, faïence, mosaïque ou parquet pour sols et murs : préparation du support, pose, jointoiement et finitions. Fourchette indicative : 5 000 à 15 000 FCFA/m² main-d'œuvre selon le type de revêtement, hors fourniture des matériaux. Sur devis après visite et métrés.",
  },
  {
    slug: "immo-plomberie-sanitaires",
    name: "Plomberie & Installation Sanitaires",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Installation, remplacement ou réparation de réseaux de plomberie et d'équipements sanitaires : canalisations eau froide/chaude, évacuations, douches, lavabos, WC, ballons d'eau chaude et fosses septiques. Fourchette très variable selon l'ampleur des travaux. Sur devis après visite. Interventions d'urgence disponibles.",
  },
  {
    slug: "immo-electricite-installation",
    name: "Électricité & Installations Électriques",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Installation électrique complète ou mise aux normes : tableau électrique, câblage, prises, interrupteurs, éclairage (LED, plafonnier, applique), climatisation split et groupe électrogène. Fourchette : à partir de 500 000 FCFA pour une installation complète de villa de 100 m². Sur devis selon les plans et l'envergure des travaux.",
  },
  {
    slug: "immo-menuiserie-aluminium-bois",
    name: "Menuiserie Aluminium, Bois & PVC",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Fabrication et pose de menuiseries sur mesure : portes, fenêtres, baies vitrées, portails, volets, pergolas et meubles de rangement en aluminium, bois ou PVC. Fourchette indicative : fenêtres aluminium standard de 30 000 à 80 000 FCFA/unité, portail de 150 000 à 400 000 FCFA selon les dimensions. Sur devis.",
  },
  {
    slug: "immo-faux-plafond-cloison",
    name: "Faux Plafonds & Cloisons Sèches",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Pose de faux plafonds (plâtre, staff, PVC, dalles minérales) et cloisons sèches (placoplatre) pour restructurer ou décorer vos espaces. Fourchette indicative : 5 000 à 12 000 FCFA/m² selon le matériau et la complexité des formes. Inclut la mise en lumière intégrée si souhaitée. Sur devis après métrés.",
  },
  {
    slug: "immo-toiture-charpente",
    name: "Toiture & Charpente",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Réalisation ou réfection de toiture : charpente bois ou métallique, couverture en tôle galvanisée, tuile béton ou zinc, isolation thermique et phonique, gouttières et évacuation des eaux pluviales. Fourchette indicative : 15 000 à 40 000 FCFA/m² selon le type de toiture. Sur devis après visite et plans.",
  },
  {
    slug: "immo-climatisation-installation",
    name: "Climatisation & Ventilation",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Fourniture et installation de systèmes de climatisation : split mural, multi-split, climatisation centralisée (cassette), ventilation mécanique contrôlée (VMC) et brasseurs d'air. Fourchette : à partir de 250 000 FCFA pour un split mural monobloc installé. Maintenance et entretien annuel inclus en option. Sur devis selon le nombre de pièces.",
  },
  {
    slug: "immo-assainissement-fosse",
    name: "Assainissement & Fosse Septique",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Conception et réalisation de systèmes d'assainissement individuel : fosse septique toutes eaux, puits perdu, filtre à sable et raccordement aux réseaux publics. Fourchette indicative : 400 000 à 1 200 000 FCFA selon la taille et le système choisi. Obligatoire pour toute construction. Sur devis après étude de sol.",
  },
  {
    slug: "immo-terrassement-vrd",
    name: "Terrassement & VRD (Voirie & Réseaux Divers)",
    pricingType: "SERVICE",
    price: 0,
    rate: 8,
    siteUrl: BASE,
    description: "Travaux de préparation de terrain et de voirie : déblai/remblai, nivellement, compactage, dallage de cour, voirie intérieure, regards, réseaux d'eaux pluviales et caniveaux. Budget indicatif très variable selon la superficie et la nature du terrain. Sur devis obligatoire après visite du site.",
  },

  // ── Assistance Diaspora ────────────────────────────────────────────────
  {
    slug: "immo-assistance-diaspora",
    name: "Assistance Diaspora — Investissement Immobilier",
    pricingType: "SERVICE",
    price: 100000,
    rate: 10,
    siteUrl: BASE,
    description: "Service dédié aux Ivoiriens et Africains de la diaspora souhaitant investir dans l'immobilier en Côte d'Ivoire : recherche du bien à distance, vérification des titres, suivi des travaux, gestion locative et compte-rendu régulier. Pour la diaspora souhaitant construire ou acheter sans se déplacer. À partir de 100 000 FCFA.",
  },
  {
    slug: "immo-suivi-construction-diaspora",
    name: "Suivi de Construction pour la Diaspora",
    pricingType: "SERVICE",
    price: 75000,
    rate: 10,
    siteUrl: BASE,
    description: "Supervision mensuelle de votre chantier de construction à distance : visites régulières du chantier, rapport photographique et vidéo, contrôle de la qualité des travaux, vérification de l'avancement et alerte en cas de problème. Pour membres de la diaspora ayant un projet de construction en Côte d'Ivoire. 75 000 FCFA/mois.",
  },
  {
    slug: "immo-diaspora-achat-cle-en-main",
    name: "Pack Diaspora — Achat Clé en Main",
    pricingType: "SERVICE",
    price: 200000,
    rate: 10,
    siteUrl: BASE,
    description: "Pack complet dédié à la diaspora souhaitant acquérir un bien sans se déplacer : recherche de bien, vérification des titres, négociation du prix, suivi notarié, prise en charge jusqu'à la remise des clés et mise en location si souhaitée. Un interlocuteur unique de bout en bout. À partir de 200 000 FCFA de frais de mandat, en sus des honoraires de transaction.",
  },
  {
    slug: "immo-diaspora-construction-terrain",
    name: "Pack Diaspora — Achat Terrain & Construction",
    pricingType: "SERVICE",
    price: 300000,
    rate: 8,
    siteUrl: BASE,
    description: "Accompagnement intégral pour la diaspora souhaitant acheter un terrain et construire : identification et sécurisation du terrain, purge foncière, plans d'architecture, dépôt du permis, sélection des entreprises BTP, suivi mensuel du chantier avec rapports photos/vidéos et réception des travaux. Honoraires de coordination : à partir de 300 000 FCFA, hors coût des travaux. Sur devis.",
  },

  // ── Régularisation & Sécurisation Foncière ────────────────────────────
  {
    slug: "immo-regularisation-fonciere",
    name: "Régularisation Foncière & Obtention de Titres",
    pricingType: "SERVICE",
    price: 200000,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement pour la sécurisation foncière : constitution du dossier de demande de titre foncier, suivi auprès des services des domaines, purge des droits coutumiers, bornage et obtention de l'ACD ou du titre foncier. Pour propriétaires souhaitant sécuriser leur terrain en Côte d'Ivoire. À partir de 200 000 FCFA de frais de dossier et d'accompagnement, hors taxes et droits administratifs.",
  },
  {
    slug: "immo-bornage-officiel",
    name: "Bornage Officiel de Terrain",
    pricingType: "SERVICE",
    price: 150000,
    rate: 10,
    siteUrl: BASE,
    description: "Opération de bornage officiel par géomètre expert : délimitation des limites de votre parcelle, pose des bornes, établissement du procès-verbal de bornage contradictoire et plan de bornage. Indispensable avant toute vente, division ou construction. Fourchette : 150 000 – 400 000 FCFA selon la superficie et la localisation. Sur devis.",
  },
  {
    slug: "immo-purge-droits-coutumiers",
    name: "Purge des Droits Coutumiers",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement pour la purge des droits coutumiers sur un terrain en Côte d'Ivoire : identification des ayants droit coutumiers, négociation, rédaction du procès-verbal de purge et constitution du dossier pour la demande de titre foncier. Étape obligatoire pour sécuriser un terrain coutumier. Honoraires sur devis selon la complexité et la localisation.",
  },
  {
    slug: "immo-morcellement-lotissement",
    name: "Morcellement & Lotissement",
    pricingType: "SERVICE",
    price: 250000,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement pour le morcellement d'une grande parcelle en lots à vendre : étude technique, plan de lotissement, dossier administratif, bornage officiel et commercialisation des lots. Pour propriétaires fonciers souhaitant valoriser leur terrain en le divisant. Sur devis à partir de 250 000 FCFA de frais d'accompagnement, hors frais techniques et administratifs.",
  },
  {
    slug: "immo-changement-destination-terrain",
    name: "Changement de Destination & Usage de Terrain",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Accompagnement administratif pour le changement de destination d'un terrain (agricole vers constructible, rural vers urbain) : étude de faisabilité réglementaire, constitution du dossier et suivi des démarches auprès des services compétents (Ministère de la Construction, communes). Sur devis selon la commune et la superficie concernée.",
  },

  // ── Promotion & Commercialisation ─────────────────────────────────────
  {
    slug: "immo-commercialisation-programme",
    name: "Commercialisation de Programme Immobilier Neuf",
    pricingType: "SERVICE",
    price: 0,
    rate: 10,
    siteUrl: BASE,
    description: "Commercialisation de programmes immobiliers neufs pour le compte de promoteurs : stratégie marketing digitale et terrain, diffusion des annonces, organisation des visites, gestion des réservations et suivi jusqu'à la signature. Commission à la vente uniquement — sans frais fixes. Pour promoteurs souhaitant externaliser la vente de leurs programmes.",
  },
  {
    slug: "immo-promotion-programme",
    name: "Promotion & Marketing d'un Programme Immobilier",
    pricingType: "SERVICE",
    price: 200000,
    rate: 8,
    siteUrl: BASE,
    description: "Mise en marché complète d'un programme immobilier : branding du projet, maquette 3D de présentation, site web dédié, campagnes digitales (Meta, Google, WhatsApp), stands d'exposition, relations presse et reporting des leads. Pour promoteurs souhaitant maximiser leurs ventes sur plan. Fourchette : 200 000 – 800 000 FCFA selon le budget marketing souhaité.",
  },
];

export async function POST() {
  try {
    if (!(await isSyncAuthorized())) {
      return NextResponse.json({ error: "Non autorisé" }, { status: 403 });
    }

    const result = await syncBranchWithFeed("ibig-immo-trust", "IBIG IMMO TRUST", IMMO_PRODUCTS, { notify: true });
    if (!result.ok) {
      return NextResponse.json({ error: result.error }, { status: result.status });
    }

    const { diff, notified } = result;
    return NextResponse.json({
      ok: true,
      upserted: diff.total,
      added: diff.added.length,
      updated: diff.updated.length,
      deleted: diff.removed,
      notified,
      message: `${diff.total} produits IBIG IMMO TRUST synchronisés (${diff.added.length} nouveau(x), ${diff.updated.length} mis à jour, ${diff.removed} retiré(s)).`,
    });
  } catch (err: any) {
    console.error("sync-immo error:", err);
    return NextResponse.json({ error: err?.message ?? "Erreur serveur" }, { status: 500 });
  }
}

