import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { FaqAccordion } from "@/components/faq-accordion";
import { ScrollReveal } from "@/components/scroll-reveal";
import { HeroSlider, type HeroSlide } from "@/components/hero-slider";
import { Icon, type IconName } from "@/components/icons";
import { HeroDashboard, NetworkTree, GrowthBars } from "@/components/illustrations";
import { fcfa } from "@/lib/format";
import { STATUS_DETAILS } from "@/lib/constants";
import { LiveCalculator } from "@/components/live-calculator";
import { SocialProofBar } from "@/components/social-proof-bar";
import { StickyMobileCta } from "@/components/sticky-mobile-cta";
import { Testimonials } from "@/components/testimonials";
import { HallOfFame } from "@/components/hall-of-fame";
import { ParrainDuMois } from "@/components/parrain-du-mois";

import { SoftwareCatalog } from "@/components/software-catalog";
import { MarketingKitPacks } from "@/components/marketing-kit-packs";
import { AffiliateTraining } from "@/components/affiliate-training";
import { CommissionDetails } from "@/components/commission-details";