import FaqClient, { type FaqCategory } from "./faq-client";

export const metadata = { title: "FAQ — 500 questions & réponses IBIG PARTNERS" };

const FAQ: FaqCategory[] = [
  {
    icon: "🚀",
    title: "Inscription & Accès",
    items: [
      { q: "L'inscription à IBIG PARTNERS est-elle vraiment gratuite ?", a: "Oui, totalement gratuite. Aucun frais d'adhésion, aucun abonnement, aucune carte bancaire requise." },
      { q: "Qui peut devenir partenaire IBIG ?", a: "Toute personne majeure résidant en Afrique ou dans la diaspora africaine, sans diplôme ni expérience commerciale requis." },
      { q: "Peut-on s'inscrire depuis l'étranger ?", a: "Oui, le programme est ouvert à la diaspora mondiale avec paiement via virement SWIFT/SEPA ou partenaires de transfert." },
      { q: "J'ai oublié mon mot de passe, que faire ?", a: "Cliquez sur « Mot de passe oublié » — un email de réinitialisation arrive sous 2 minutes, vérifiez vos spams." },
      { q: "Mon compte est bloqué après trop de tentatives, comment débloquer ?", a: "Le blocage se lève automatiquement après 15 minutes ; sinon utilisez la réinitialisation de mot de passe." },
      { q: "Je ne reçois pas les emails IBIG PARTNERS, pourquoi ?", a: "Vérifiez vos spams et ajoutez noreply@mail.ibigpartners.com à vos contacts." },
      { q: "Puis-je avoir plusieurs comptes partenaires ?", a: "Non, un seul compte par personne — les doublons entraînent la suspension des deux comptes." },
      { q: "Combien de temps dure l'approbation de mon compte ?", a: "24 à 48h ouvrées après inscription ; vous recevez un email dès validation." },
      { q: "Peut-on changer son adresse email après inscription ?", a: "Oui dans Mon Profil → section contact, un email de confirmation est envoyé à la nouvelle adresse." },
      { q: "Qu'est-ce que le code partenaire (ex: AFF-KOFFI-001) ?", a: "Votre identifiant unique d'affiliation inclus dans tous vos liens de tracking — ne le partagez jamais." },
      { q: "Comment vérifier mon email après inscription ?", a: "Un lien de vérification est envoyé automatiquement ; cliquez dessus dans les 24h pour activer votre compte." },
      { q: "Puis-je utiliser un email professionnel d'entreprise ?", a: "Oui, tout email valide est accepté ; préférez un email que vous consultez régulièrement." },
      { q: "L'inscription est-elle sécurisée (HTTPS, chiffrement) ?", a: "Oui, toutes les données transitent via HTTPS/TLS et les mots de passe sont hachés en bcrypt." },
      { q: "Puis-je m'inscrire via Google ou Facebook ?", a: "Non, l'inscription se fait uniquement par email/mot de passe sur ibigpartners.com/rejoindre." },
      { q: "Y a-t-il une application mobile IBIG PARTNERS ?", a: "L'espace partenaire est optimisé pour mobile via navigateur ; une app native est en développement." },
      { q: "IBIG PARTNERS fonctionne-t-il sur tous les navigateurs ?", a: "Oui, compatible Chrome, Firefox, Safari, Edge — utilisez de préférence la version à jour de votre navigateur." },
      { q: "Comment activer la double authentification (2FA) ?", a: "La 2FA par email est active par défaut ; contactez le support pour les options d'authentificateur avancé." },
      { q: "Puis-je voir quels appareils sont connectés à mon compte ?", a: "Cette fonctionnalité est en cours de déploiement ; contactez le support si vous suspectez un accès non autorisé." },
      { q: "Mon compte peut-il être supprimé définitivement ?", a: "Oui, sur demande au support — les données sont effacées sous 30 jours conformément au RGPD." },
      { q: "Comment télécharger mes données personnelles ?", a: "Contactez le support avec la demande d'export de données ; vous recevez un fichier ZIP sous 72h." },
      { q: "Que se passe-t-il si je change de pays de résidence ?", a: "Mettez à jour votre profil et vérifiez que votre méthode de paiement est compatible avec le nouveau pays." },
      { q: "Mon profil est-il visible par les autres partenaires ?", a: "Seules les informations publiques (nom, photo, statut) sont visibles ; vos finances restent privées." },
      { q: "Comment personnaliser mon profil partenaire ?", a: "Dans Mon Profil : ajoutez photo, bio, spécialités et liens sociaux pour renforcer votre crédibilité." },
      { q: "Que signifie le badge « Vérifié » sur mon profil ?", a: "Il confirme que votre identité a été vérifiée via le processus KYC — il renforce la confiance des prospects." },
      { q: "Puis-je me connecter depuis plusieurs appareils simultanément ?", a: "Oui, plusieurs sessions actives sont permises sur téléphone, tablette et ordinateur en même temps." },
      { q: "Comment changer mon nom d'affichage ?", a: "Dans Mon Profil → Informations personnelles ; les changements de nom légal nécessitent une validation KYC." },
      { q: "Mon code partenaire est-il modifiable ?", a: "Non, il est attribué définitivement à l'inscription pour garantir la traçabilité de vos ventes." },
      { q: "Que faire si quelqu'un usurpe mon identité sur IBIG ?", a: "Contactez immédiatement le support avec les preuves — IBIG suspend le compte frauduleux sous 24h." },
      { q: "Y a-t-il une période d'essai avant l'engagement ?", a: "Non, l'accès est immédiat et gratuit dès inscription — aucun engagement ni période d'essai limitée." },
      { q: "Que se passe-t-il si je reste inactif pendant 6 mois ?", a: "Le compte reste actif mais peut passer en statut inactif ; aucune commission ne génère si aucune vente." },
      { q: "Comment réactiver un compte suspendu ?", a: "Contactez le support pour connaître le motif de suspension et les étapes de réactivation." },
      { q: "Puis-je mettre mon compte en pause sans le supprimer ?", a: "Oui, informez le support ; votre compte et vos commissions sont conservés pendant la pause." },
      { q: "Comment ajouter une photo de profil professionnelle ?", a: "Dans Mon Profil → Photo : téléchargez une image JPG/PNG carrée de moins de 2 Mo." },
      { q: "Les informations de mon profil sont-elles indexées par Google ?", a: "Votre page publique /p/CODE est indexable ; vos données privées (finances, KYC) ne le sont pas." },
      { q: "Comment accéder à l'espace partenaire depuis un téléphone ?", a: "Ouvrez ibigpartners.com dans votre navigateur mobile — l'interface est responsive et optimisée." },
      { q: "La session expire-t-elle automatiquement ?", a: "Oui après 30 jours d'inactivité ou si vous vous déconnectez manuellement via le menu profil." },
      { q: "Que faire si je ne reçois pas le SMS de vérification ?", a: "Vérifiez que le numéro est correct et réessayez ; si ça échoue, utilisez la vérification par email." },
      { q: "Comment savoir si mon compte a été piraté ?", a: "Vérifiez l'historique de connexions dans Mon Profil → Sécurité et changez immédiatement votre mot de passe." },
      { q: "Que contient l'email de bienvenue après inscription ?", a: "Votre code partenaire, le lien vers l'espace partenaire, les étapes de démarrage et le guide PDF." },
      { q: "Comment configurer mes préférences de langue (FR/EN) ?", a: "Dans Mon Profil → Préférences ; la langue s'applique à l'interface mais pas aux contenus produits." },
      { q: "Y a-t-il une FAQ d'aide disponible en anglais ?", a: "Oui, une version anglaise est accessible via /en/faq pour les partenaires de la diaspora anglophone." },
      { q: "Puis-je utiliser un pseudonyme à la place de mon vrai nom ?", a: "Non, le nom réel est obligatoire pour les raisons légales liées aux paiements et au KYC." },
      { q: "Les mineurs peuvent-ils s'inscrire ?", a: "Non, l'inscription est réservée aux personnes majeures (18 ans et plus) conformément au contrat." },
      { q: "Comment récupérer mon compte si je n'ai plus accès à mon email ?", a: "Contactez le support avec votre code partenaire et une pièce d'identité pour prouver votre identité." },
      { q: "Y a-t-il une limite d'âge maximale pour être partenaire ?", a: "Non, tout adulte majeur peut être partenaire IBIG quel que soit son âge." },
      { q: "Comment inviter un ami à rejoindre IBIG PARTNERS ?", a: "Partagez votre lien de parrainage depuis Mon Réseau — votre ami s'inscrit et devient votre filleul N1." },
      { q: "Puis-je changer mon pays de résidence déclaré ?", a: "Oui dans Mon Profil ; un changement significatif peut nécessiter une mise à jour du KYC." },
      { q: "Comment supprimer une photo de profil sans en mettre une nouvelle ?", a: "Dans Mon Profil → Photo → Supprimer ; un avatar généré automatiquement remplace la photo." },
      { q: "L'espace partenaire est-il accessible 24h/24 ?", a: "Oui, disponible en permanence avec des maintenances planifiées annoncées à l'avance." },
      { q: "Comment contacter le support IBIG PARTNERS ?", a: "Via Espace → Support : créez un ticket avec votre demande et le numéro de référence concerné." },
      { q: "Y a-t-il un numéro de téléphone IBIG pour les urgences ?", a: "Contactez via le support en ligne ou WhatsApp officiel IBIG pour les cas urgents." },
    ],
  },
  {
    icon: "📋",
    title: "Contrat & KYC",
    items: [
      { q: "Pourquoi dois-je signer un contrat pour accéder à l'espace partenaire ?", a: "Le contrat fixe les règles du partenariat et permet à IBIG de vous payer légalement — étape obligatoire." },
      { q: "Comment signer le contrat de partenariat ?", a: "Espace → Mon Contrat → Contrat digital : lisez et cochez la case de validation électronique horodatée." },
      { q: "Qu'est-ce que le KYC ?", a: "La vérification d'identité obligatoire pour recevoir vos paiements, conforme aux réglementations anti-fraude." },
      { q: "Quels documents sont acceptés pour le KYC ?", a: "CNI, passeport en cours de validité, permis de conduire ou titre de séjour — lisibles, non expirés." },
      { q: "Combien de temps prend la validation KYC ?", a: "24 à 72h ouvrées après soumission de votre dossier complet ; vous êtes notifié par email." },
      { q: "Mon KYC a été rejeté, que faire ?", a: "Corrigez ce qui est indiqué dans la note de rejet (document flou, expiré, nom différent) et soumettez à nouveau." },
      { q: "Que se passe-t-il si je ne fais pas mon KYC ?", a: "Vos commissions s'accumulent mais ne sont pas versées tant que le KYC n'est pas validé." },
      { q: "Je suis une entreprise, dois-je faire le KYC ou le KYB ?", a: "Le KYB (Know Your Business) est requis pour les entreprises — section Vérification Entreprise avec RCCM, statuts." },
      { q: "Mon contrat a-t-il une durée limitée ?", a: "À durée indéterminée, renouvelable tacitement, résiliable avec 30 jours de préavis sans pénalité." },
      { q: "Puis-je modifier mes informations personnelles après le KYC ?", a: "Oui pour les infos non vérifiées ; pour nom ou numéro de pièce, contactez le support." },
      { q: "La signature électronique est-elle juridiquement valable ?", a: "Oui, la signature électronique horodatée est juridiquement valide selon les lois OHADA et CEDEAO." },
      { q: "Puis-je imprimer le contrat pour le signer manuellement ?", a: "Non, seule la signature électronique dans la plateforme est acceptée pour des raisons de traçabilité." },
      { q: "Comment accéder à une ancienne version de mon contrat ?", a: "Dans Mon Contrat, l'historique des versions signées est accessible ; contactez le support pour les archives." },
      { q: "Y a-t-il une clause de non-concurrence dans le contrat ?", a: "Le contrat prévoit des restrictions sur la promotion de solutions directement concurrentes à IBIG SARL." },
      { q: "Le contrat est-il disponible en anglais ?", a: "Une version anglaise est disponible sur demande au support pour les partenaires anglophones." },
      { q: "Que prévoit le contrat en cas de litige ?", a: "Le contrat désigne la juridiction compétente d'Abidjan pour les litiges et encourage la résolution amiable." },
      { q: "Le KYC est-il valable indéfiniment ?", a: "Oui tant que vos documents restent valides ; IBIG peut demander une re-vérification si vos documents expirent." },
      { q: "Dois-je refaire le KYC si ma CNI expire ?", a: "Oui, soumettez le nouveau document avant l'expiration pour éviter toute interruption de paiement." },
      { q: "Le KYC est-il obligatoire pour déclarer des ventes ?", a: "Non, vous pouvez déclarer des ventes sans KYC, mais le versement est suspendu jusqu'à sa validation." },
      { q: "Mon KYC est-il partagé avec des tiers ?", a: "Non, vos données KYC sont strictement confidentielles et ne sont jamais vendues ou partagées." },
      { q: "Puis-je faire mon KYC en personne dans les bureaux IBIG ?", a: "Oui, vous pouvez vous présenter dans les bureaux IBIG à Abidjan avec vos originaux pour assistance." },
      { q: "Que faire si mon nom dans le document ne correspond pas au compte ?", a: "Contactez le support avant soumission pour aligner votre nom de compte avec votre document officiel." },
      { q: "Y a-t-il un frais pour la vérification KYC ?", a: "Non, la vérification KYC est entièrement gratuite pour tous les partenaires IBIG." },
      { q: "Comment suivre l'avancement de mon dossier KYC ?", a: "Dans Vérification de compte, un statut en temps réel (SUBMITTED, UNDER_REVIEW, VERIFIED, REJECTED) est affiché." },
      { q: "Le rejet KYC affecte-t-il mes commissions déjà validées ?", a: "Non, les commissions validées sont conservées ; seul le versement est suspendu jusqu'à la validation." },
      { q: "Puis-je opérer avec un compte non vérifié en mode limité ?", a: "Oui, vous pouvez déclarer des ventes et gérer votre réseau, mais pas recevoir de paiements." },
      { q: "Combien de tentatives KYC sont autorisées avant blocage ?", a: "Après 5 rejets consécutifs, contactez le support pour débloquer et recevoir une assistance personnalisée." },
      { q: "Comment IBIG protège mes données KYC ?", a: "Vos documents sont chiffrés AES-256 au repos et TLS en transit, stockés sur serveurs sécurisés." },
      { q: "Puis-je soumettre des documents KYC en anglais ou arabe ?", a: "Oui, les documents en français, anglais ou arabe sont acceptés s'ils sont lisibles et officiels." },
      { q: "Que faire si mon KYC a été rejeté 5 fois ?", a: "Contactez le support directement avec vos documents — une assistance manuelle est disponible pour les cas complexes." },
      { q: "Le contrat mentionne-t-il la protection de mes données ?", a: "Oui, une clause RGPD détaille comment IBIG collecte, stocke et protège vos données personnelles." },
      { q: "Puis-je accepter le contrat au nom d'une entreprise ?", a: "Oui si vous êtes représentant légal de l'entreprise ; le contrat doit mentionner la raison sociale." },
      { q: "Comment obtenir un exemplaire original de mon contrat signé ?", a: "Dans Mon Contrat → Télécharger ; vous recevez un PDF horodatée avec votre signature électronique." },
      { q: "Y a-t-il une clause de confidentialité (NDA) ?", a: "Oui, le contrat inclut une clause de confidentialité sur les informations commerciales et tarifaires d'IBIG." },
      { q: "Comment IBIG peut-il résilier mon contrat ?", a: "En cas de fraude, violation du contrat ou inactivité prolongée, avec notification préalable de 30 jours." },
      { q: "Puis-je transférer mon contrat à une entreprise que je crée ?", a: "Contactez le support — un avenant contractuel peut être établi pour transférer les droits à votre société." },
      { q: "Le contrat IBIG respecte-t-il le droit OHADA ?", a: "Oui, le contrat est rédigé conformément au droit commercial OHADA applicable en Côte d'Ivoire et en zone UEMOA." },
      { q: "Que comprend la section Obligations du Partenaire ?", a: "Respect de l'éthique commerciale, pas de fausses déclarations, utilisation correcte de la marque IBIG." },
      { q: "Comment obtenir un justificatif de partenariat officiel pour des démarches administratives ?", a: "Contactez le support en précisant l'usage — IBIG peut fournir une attestation de partenariat officielle." },
      { q: "Les délais de traitement KYC peuvent-ils être accélérés ?", a: "En cas d'urgence documentée, contactez le support pour une demande de traitement prioritaire." },
      { q: "Quels sont les délais légaux de conservation de mes données KYC ?", a: "IBIG conserve vos données KYC 5 ans conformément aux obligations légales anti-blanchiment." },
      { q: "Mon KYC validé reste-t-il valable si je déménage ?", a: "Oui, le KYC validé est lié à votre identité, pas à votre adresse ; mettez à jour votre adresse dans le profil." },
      { q: "Que signifie SUBMITTED vs UNDER_REVIEW dans le statut KYC ?", a: "SUBMITTED : documents envoyés, en attente de traitement. UNDER_REVIEW : un agent IBIG examine activement votre dossier." },
      { q: "Comment prouver ma résidence pour le KYC (justificatif de domicile) ?", a: "Facture d'eau/électricité, relevé bancaire ou attestation de domicile de moins de 3 mois." },
      { q: "Puis-je déléguer la vérification KYC à mon assistant ou comptable ?", a: "Non, le KYC est personnel — vous devez soumettre vos propres documents en votre nom." },
      { q: "Y a-t-il une vérification biométrique dans le processus KYC ?", a: "Non actuellement ; la vérification est documentaire avec analyse manuelle par l'équipe IBIG." },
      { q: "Comment signaler une erreur dans mon contrat après signature ?", a: "Contactez le support immédiatement — un avenant rectificatif peut être établi selon la nature de l'erreur." },
      { q: "Le KYC est-il requis pour les KYB également ?", a: "Oui, le représentant légal de l'entreprise doit aussi faire son KYC personnel en complément du KYB." },
      { q: "Comment savoir si mon contrat a bien été enregistré côté IBIG ?", a: "Dans Mon Contrat, la date et l'heure de signature sont affichées ; vous recevez aussi un email de confirmation." },
      { q: "Que se passe-t-il à mon contrat si IBIG SARL change ses conditions ?", a: "Vous êtes notifié 30 jours à l'avance par email et devez accepter les nouvelles conditions ou résilier." },
      { q: "Mon partenariat peut-il être suspendu sans résiliation définitive ?", a: "Oui, IBIG peut suspendre temporairement un compte en cas d'enquête, avec réactivation possible après résolution." },
    ],
  },
  {
    icon: "🧩",
    title: "Produits & Activation",
    items: [
      { q: "Comment activer un produit pour obtenir mon lien affilié ?", a: "Mes Produits → trouvez le produit → « Activer » ; votre lien est immédiatement généré dans Mes Liens." },
      { q: "Combien de produits puis-je activer ?", a: "Autant que vous voulez, sans limite ; concentrez-vous sur 3 à 5 produits que vous maîtrisez bien." },
      { q: "Quelle est la différence entre les 10 branches du groupe IBIG ?", a: "Chaque branche couvre un secteur : SOFT (SaaS), EDUFORM (formations), IMMO TRUST (immobilier), MARKET, DIGITAL, DIGITAL KITS, CONSEIL+, EMPLOI & TALENTS, MULTISERVICES, PARTNERS." },
      { q: "Quels produits génèrent les meilleures commissions ?", a: "Les SaaS mensuels (commissions récurrentes) et les formations certifiantes (montants élevés) sont les plus rentables." },
      { q: "Comment choisir le bon produit à promouvoir pour mon réseau ?", a: "Analysez votre audience : chefs d'entreprise → SaaS IBIG SOFT ; professionnels → EDUFORM ; entrepreneurs → IMMO TRUST." },
      { q: "Les prix des produits peuvent-ils changer ?", a: "Oui, les prix sont définis par IBIG SARL ; votre lien s'adapte et votre commission est calculée sur le prix réel." },
      { q: "Qu'est-ce qu'un produit 'Sur devis' ?", a: "Produits premium sans prix fixe (projets immobiliers, prestations sur mesure) — commission sur montant final validé." },
      { q: "Puis-je promouvoir des produits de toutes les branches simultanément ?", a: "Oui, votre compte donne accès à l'ensemble du catalogue — activez et promouvez librement." },
      { q: "Un client peut-il commander directement depuis ma page partenaire ?", a: "Oui, votre page /p/CODE/slug présente le produit et redirige vers la page officielle avec votre tracking." },
      { q: "Que faire si un produit que je promeuve est temporairement suspendu ?", a: "Votre lien indique la situation ; vos commissions en cours ne sont pas affectées et vous êtes notifié." },
      { q: "Comment voir la description complète d'un produit avant activation ?", a: "Dans Mes Produits, cliquez sur la carte produit pour accéder à la fiche complète avec taux, description et conditions." },
      { q: "Y a-t-il des produits exclusifs réservés aux partenaires GOLD et supérieur ?", a: "Oui, certains produits premium ou en accès anticipé sont réservés aux partenaires GOLD, MASTER et ELITE." },
      { q: "Comment désactiver un produit que je ne souhaite plus promouvoir ?", a: "Dans Mes Produits → produit actif → « Désactiver » ; vos commissions passées restent acquises." },
      { q: "Les formations EDUFORM sont-elles certifiantes ?", a: "Oui, la majorité des formations EDUFORM délivrent des certificats reconnus par les entreprises partenaires d'IBIG." },
      { q: "Les logiciels IBIG SOFT sont-ils disponibles en version démo ?", a: "Oui, des démos sont disponibles sur demande — contactez IBIG pour organiser une présentation client." },
      { q: "Quelle est la politique de remboursement sur les produits IBIG ?", a: "7 jours satisfait ou remboursé sur les formations ; consultez les conditions spécifiques de chaque produit." },
      { q: "Comment signaler un problème technique sur un produit que je vends ?", a: "Via Espace → Support : créez un ticket en précisant le produit et le problème rencontré par le client." },
      { q: "Les prix sont-ils TTC ou HT ?", a: "Les prix affichés sont TTC pour les particuliers ; des conditions HT peuvent être négociées pour les entreprises." },
      { q: "Y a-t-il des réductions volume (plusieurs licences) ?", a: "Oui, des tarifs dégressifs existent pour les achats groupés — contactez IBIG pour un devis personnalisé." },
      { q: "Qu'est-ce que la branche IBIG DIGITAL ?", a: "Elle couvre la création de sites web, identité visuelle, marketing digital et présence en ligne pour les PME." },
      { q: "Qu'est-ce que IBIG EMPLOI & TALENTS ?", a: "Elle offre des services de recrutement, placement de compétences et formation professionnelle aux entreprises." },
      { q: "Qu'est-ce que IBIG CONSEIL+ ?", a: "Elle propose des services de conseil juridique, fiscal, RH et stratégique aux TPE/PME africaines." },
      { q: "Y a-t-il des produits spécifiques pour le secteur agricole ?", a: "Oui, certains modules de gestion IBIG SOFT sont adaptés aux coopératives et exploitations agricoles." },
      { q: "Comment proposer des produits IBIG dans les universités ?", a: "Approchez les services des études, DAF ou DSI — Scolaby et les formations EDUFORM sont très adaptés." },
      { q: "Qu'est-ce que Fleet 360 et à qui s'adresse-t-il ?", a: "Fleet 360 est un SaaS de gestion de flottes de véhicules — idéal pour transporteurs, taxis, entreprises de livraison." },
      { q: "Qu'est-ce que GescomXEL ?", a: "GescomXEL est un logiciel de gestion commerciale (facturation, stocks, CRM) pour PME et commerçants." },
      { q: "Qu'est-ce que Scolaby et comment le vendre à une école ?", a: "Scolaby est un ERP scolaire (inscriptions, notes, paiements) — ciblez directement les directeurs d'établissement." },
      { q: "Comment obtenir du matériel marketing (flyers, vidéos) par produit ?", a: "Dans Kit Marketing (section Ressources), téléchargez les supports officiels par produit et branche." },
      { q: "Les produits IBIG peuvent-ils être revendus en marque blanche ?", a: "Non, les produits IBIG sont commercialisés sous la marque IBIG SARL — pas de marque blanche disponible." },
      { q: "Y a-t-il un programme de trial (essai gratuit) pour les SaaS ?", a: "Oui, certains SaaS proposent 14 jours d'essai gratuit — renseignez-vous sur chaque fiche produit." },
      { q: "Puis-je vendre des produits IBIG dans un magasin physique ?", a: "Oui, vous pouvez présenter et vendre en présentiel ; le client finalise l'achat en ligne avec votre code." },
      { q: "Comment organiser une démonstration de produit en groupe ?", a: "Contactez IBIG pour organiser un webinaire ou une démonstration en salle avec support de l'équipe commerciale." },
      { q: "Puis-je créer des bundles de plusieurs produits IBIG ?", a: "Non officiellement, mais vous pouvez conseiller plusieurs produits complémentaires à un même client." },
      { q: "Comment savoir quels produits se vendent le mieux dans ma région ?", a: "Dans Analytics, filtrez par région et produit pour identifier les best-sellers dans votre zone géographique." },
      { q: "Comment gérer un client qui veut mettre à niveau sa formule ?", a: "Orientez-le vers le support IBIG ou déclarez la vente de la formule supérieure pour toucher la différence de commission." },
      { q: "Les produits IBIG sont-ils disponibles en arabe ou en anglais ?", a: "Certains produits sont multilingues ; consultez la fiche produit pour les langues disponibles." },
      { q: "Comment vérifier si un produit est toujours actif avant de le proposer ?", a: "Dans Mes Produits, les produits actifs affichent un badge vert ; les suspendus affichent un badge rouge." },
      { q: "Comment obtenir un accès démo d'un logiciel pour montrer à un client ?", a: "Demandez via le support IBIG en précisant le produit et la date souhaitée — réponse sous 24h." },
      { q: "Puis-je vendre des formations en entreprise (intra-company) ?", a: "Oui, EDUFORM propose des formations en intra-entreprise sur mesure — soumettez la demande au support." },
      { q: "Comment proposer des formations EDUFORM à un client corporate ?", a: "Présentez le catalogue EDUFORM, identifiez les besoins en compétences et demandez un devis personnalisé à IBIG." },
      { q: "Y a-t-il des abonnements familiaux ou groupes disponibles ?", a: "Certains produits proposent des licences multi-utilisateurs — vérifiez les conditions sur chaque fiche produit." },
      { q: "Y a-t-il un catalogue en version PDF téléchargeable ?", a: "Oui, dans Ressources → Kit Marketing, téléchargez le catalogue complet en PDF actualisé chaque trimestre." },
      { q: "Puis-je demander l'ajout d'un nouveau produit au catalogue ?", a: "Oui, via le support IBIG — votre suggestion est transmise à l'équipe produit pour évaluation." },
      { q: "Les produits IBIG sont-ils certifiés par des organismes officiels ?", a: "Les formations EDUFORM sont validées par des partenaires académiques ; les logiciels SOFT sont conformes SYSCOHADA." },
      { q: "Comment accéder aux fiches techniques des produits pour les présenter ?", a: "Dans Mes Produits → fiche produit → onglet Ressources : téléchargez les documents techniques et commerciaux." },
      { q: "Y a-t-il des produits saisonniers disponibles temporairement ?", a: "Oui, IBIG propose des offres spéciales durant certaines périodes — suivez vos Notifications pour les annonces." },
      { q: "Les logiciels IBIG fonctionnent-ils sans connexion internet ?", a: "Non, les SaaS IBIG nécessitent une connexion internet ; certains modules permettent un travail hors-ligne limité." },
      { q: "Comment créer une présentation PowerPoint des produits IBIG ?", a: "Utilisez les slides officielles dans Kit Marketing → Présentations et personnalisez avec votre nom/contact." },
      { q: "Comment savoir si un client a déjà acheté un produit IBIG ?", a: "Vérifiez via la déclaration de vente — si le système signale un doublon, le client est déjà enregistré." },
      { q: "Quelle branche IBIG convient le mieux aux petits commerçants ?", a: "IBIG MARKET et MULTISERVICES avec leurs solutions de facturation, de caisse et de gestion de stocks." },
      { q: "Y a-t-il une formation obligatoire sur les produits avant de les vendre ?", a: "Non obligatoire mais fortement conseillée — des guides produits sont disponibles dans Académie IBIG." },
    ],
  },
  {
    icon: "🔗",
    title: "Liens & Tracking",
    items: [
      { q: "Comment fonctionne le tracking de mes liens affiliés ?", a: "Un cookie 30 jours est déposé au clic ; si le visiteur achète dans ce délai, la commission vous revient." },
      { q: "Combien de jours dure le cookie de tracking ?", a: "30 jours. Achat après 30 jours sans nouveau clic = commission perdue ; relancez régulièrement." },
      { q: "Que se passe-t-il si un prospect clique sur mon lien ET sur celui d'un autre partenaire ?", a: "Le dernier clic gagne — si votre prospect reclique sur un autre lien, la commission va à l'autre partenaire." },
      { q: "Comment copier rapidement mes liens ?", a: "Dans Mes Liens, la section « Copie rapide » affiche vos liens les plus cliqués avec un bouton Copier." },
      { q: "Puis-je utiliser mon code partenaire sans lien ?", a: "Oui, votre code peut être saisi manuellement par le client lors du paiement sur les plateformes qui le permettent." },
      { q: "Comment créer un lien UTM personnalisé pour suivre mes campagnes ?", a: "Dans Mes Liens → générateur UTM : ajoutez source, medium, campagne — le lien intègre votre tracking affilié." },
      { q: "Puis-je créer un QR code à partir de mes liens ?", a: "Oui, dans Mon Réseau, générez et téléchargez un QR code PNG pour vos flyers et présentations." },
      { q: "Pourquoi mon lien n'enregistre-t-il pas de clics ?", a: "Vérifiez le bon format de lien et évitez de tester depuis votre propre navigateur (auto-clics non comptabilisés)." },
      { q: "Puis-je raccourcir mes liens affiliés ?", a: "Oui, via bit.ly ou rebrand.ly — vérifiez que les redirections 301/302 transmettent bien les paramètres d'URL." },
      { q: "Ma page de vente personnalisée est-elle publique ?", a: "Oui, /p/CODE/slug est accessible sans connexion — partagez ce lien directement à vos prospects." },
      { q: "Comment tester mon lien affilié pour vérifier qu'il fonctionne ?", a: "Ouvrez le lien en navigation privée (mode incognito) — vous verrez la page produit avec votre tracking actif." },
      { q: "Mon lien est-il unique ou partagé avec d'autres partenaires ?", a: "Unique — chaque partenaire a son propre lien avec son code ; deux partenaires ne partagent jamais le même lien." },
      { q: "Comment créer un lien vers une page spécifique du site IBIG ?", a: "Dans Mes Liens, sélectionnez le produit et copiez le lien vers la page produit directement avec votre code." },
      { q: "Y a-t-il une limite au nombre de liens que je peux créer ?", a: "Non, vous pouvez créer autant de liens (avec variations UTM) que nécessaire pour vos campagnes." },
      { q: "Le tracking fonctionne-t-il si le client désactive les cookies ?", a: "Non, le tracking cookie-based est affecté ; encouragez vos clients à utiliser votre code manuellement au paiement." },
      { q: "Que se passe-t-il si un client utilise un bloqueur de publicité ?", a: "Les bloqueurs peuvent bloquer certains scripts de tracking ; utilisez votre code partenaire en backup." },
      { q: "Puis-je utiliser mes liens dans des emails commerciaux ?", a: "Oui, insérez votre lien affilié dans vos emails ; assurez-vous de respecter les règles anti-spam de votre pays." },
      { q: "Mes liens fonctionnent-ils dans des SMS ?", a: "Oui, le lien complet fonctionne dans un SMS ; pour gagner de la place, raccourcissez-le d'abord." },
      { q: "Puis-je suivre les conversions directement depuis Mes Liens ?", a: "Oui, dans Mes Liens, chaque lien affiche les clics et les ventes générées via ce lien spécifique." },
      { q: "Un lien affilié est-il valide indéfiniment ?", a: "Oui tant que le produit est actif et votre compte valide ; si le produit est retiré, le lien redirige vers une erreur." },
      { q: "Comment savoir si mon lien a généré une vente ?", a: "Dans Mes Commissions, chaque commission affiche le lien source et la date du clic ayant conduit à la vente." },
      { q: "Puis-je intégrer mon lien affilié dans un bouton sur mon site web ?", a: "Oui, créez un bouton HTML avec href=votre-lien-affilié — idéal pour un blog ou site de niche." },
      { q: "Mes concurrents peuvent-ils copier mon lien ?", a: "Ils peuvent copier l'URL mais pas votre code — si quelqu'un retire votre code du lien, la commission est perdue." },
      { q: "Que faire si je soupçonne une manipulation de mes clics ?", a: "Signalez au support avec les détails (dates, volumes anormaux) — IBIG dispose d'outils anti-fraude." },
      { q: "Comment partager mon lien en tant que code QR sur une carte de visite ?", a: "Générez le QR code dans Mon Réseau, téléchargez-le en PNG et intégrez-le dans votre carte via Canva ou Word." },
      { q: "Puis-je mettre mon lien dans une signature email automatique ?", a: "Oui, ajoutez votre lien affilié ou /p/CODE dans votre signature email — efficace pour la prospection passive." },
      { q: "Comment auditer mes liens les moins performants ?", a: "Dans Analytics, filtrez par lien et triez par taux de conversion — identifiez les liens peu cliqués ou peu convertissants." },
      { q: "Puis-je utiliser des redirecteurs comme Linktree avec mes liens IBIG ?", a: "Oui, créez une page Linktree/Beacons avec tous vos liens produits — pratique pour les réseaux sociaux." },
      { q: "Les liens fonctionnent-ils sur les réseaux sociaux (Instagram, TikTok) ?", a: "Oui, vos liens peuvent être partagés sur tous les réseaux ; Instagram bio et TikTok profil permettent 1 lien cliquable." },
      { q: "Mon lien de parrainage et mon lien affilié sont-ils différents ?", a: "Oui — lien de parrainage : recrute des partenaires. Lien affilié : dirige des clients vers les produits IBIG." },
      { q: "Le lien affilié fonctionne-t-il en navigation privée ?", a: "Oui mais le cookie ne persiste pas après fermeture de la session privée — recommandez à vos prospects d'acheter immédiatement." },
      { q: "Y a-t-il des liens interdits (sites où je ne peux pas publier) ?", a: "Oui, les sites adultes, les casinos en ligne, et les plateformes de spam sont interdits par le contrat." },
      { q: "Puis-je voir les détails de chaque clic (heure, appareil, pays) ?", a: "Dans Analytics, les données de clic incluent horodatage, type d'appareil et pays d'origine." },
      { q: "Comment créer un lien affilié pour plusieurs produits à la fois ?", a: "Créez un lien vers le catalogue general (/catalogue?ref=VOTRECODE) pour présenter tous vos produits actifs." },
      { q: "Y a-t-il une API pour générer des liens affiliés programmatiquement ?", a: "Oui via l'API Partenaire dans Ressources → API Key — consultez la documentation technique disponible." },
      { q: "Mes liens fonctionnent-ils après ma désinscription d'IBIG PARTNERS ?", a: "Non, vos liens sont désactivés à la désinscription ; assurez-vous de les remplacer avant de partir." },
      { q: "Puis-je créer un lien qui expire après une date donnée ?", a: "Non nativement, mais vous pouvez créer un lien UTM limité à une campagne et arrêter de le promouvoir manuellement." },
      { q: "Comment obtenir les statistiques de clics par pays ?", a: "Dans Analytics → Géographie, visualisez la distribution de vos clics par pays et ville." },
      { q: "Mes liens fonctionnent-ils si le produit est temporairement indisponible ?", a: "Le lien redirige vers la page produit qui indique la situation ; aucune vente n'est possible pendant l'indisponibilité." },
      { q: "Puis-je créer un lien affilié pour un produit non encore activé ?", a: "Non, vous devez d'abord activer le produit dans Mes Produits avant de pouvoir générer son lien affilié." },
      { q: "Le lien de ma page personnelle change-t-il si je mets à jour mon profil ?", a: "L'URL /p/CODE reste permanente ; seul le contenu affiché (photo, bio) se met à jour." },
      { q: "Comment archiver ou supprimer un lien obsolète ?", a: "Dans Mes Liens, vous pouvez archiver un lien — il ne génère plus de clics mais son historique est conservé." },
      { q: "Puis-je protéger mon lien avec un mot de passe ?", a: "Non, les liens affiliés sont publics par nature ; protégez plutôt votre code partenaire en ne le partageant pas." },
      { q: "Comment créer un lien affilié qui déclenche directement un panier ?", a: "Utilisez le paramètre ?add=slug dans votre lien pour pré-sélectionner un produit dans le panier du client." },
      { q: "Quel est le format standard d'un lien affilié IBIG ?", a: "Format : ibigpartners.com/aff/VOTRECODE?p=slug-produit — ou ibigpartners.com/offres/slug?ref=VOTRECODE." },
      { q: "Comment savoir si un lien a expiré ou été désactivé par IBIG ?", a: "Testez le lien en navigation privée ; s'il renvoie une erreur 404, le produit a été retiré — mettez à jour votre promotion." },
      { q: "Puis-je créer un lien direct vers ma page d'inscription (parrainage) ?", a: "Oui, dans Mon Réseau → Lien de parrainage : copiez le lien direct qui pre-remplit votre code parrain." },
      { q: "Les liens fonctionnent-ils si le site IBIG est en maintenance ?", a: "Non, pendant une maintenance planifiée les liens redirigent vers une page de maintenance temporaire." },
      { q: "Comment intégrer mes liens dans une newsletter email ?", a: "Insérez vos liens affiliés dans votre newsletter comme des hyperliens normaux — compatible avec tous les outils email." },
      { q: "Y a-t-il un rapport hebdomadaire automatique de performance de mes liens ?", a: "Oui, le score hebdomadaire du lundi inclut vos statistiques de clics et de conversions de la semaine écoulée." },
    ],
  },
  {
    icon: "💰",
    title: "Commissions & Calculs",
    items: [
      { q: "Comment sont calculées mes commissions ?", a: "Commission = Montant × Taux produit × Coefficient statut. Ex: 150 000 FCFA × 20% × 1 (STARTER) = 30 000 FCFA." },
      { q: "Qu'est-ce que les commissions sur 3 niveaux ?", a: "N1 : vous vendez directement (taux plein). N2 : votre filleul vend (% réduit). N3 : filleul du filleul (% encore réduit)." },
      { q: "Les taux de commission sont-ils les mêmes pour tous les produits ?", a: "Non, chaque produit a son propre taux (5% à 20%) — consultez la fiche produit pour le taux exact." },
      { q: "Qu'est-ce qu'une commission récurrente ?", a: "Pour les SaaS mensuels, vous touchez votre % chaque mois que le client reste abonné — revenu passif puissant." },
      { q: "Mon statut influence-t-il mes commissions ?", a: "Oui, SILVER et supérieurs ont des coefficients multiplicateurs — consultez le Plan de compensation pour les détails." },
      { q: "Quand vois-je mes commissions apparaître ?", a: "Dès qu'une vente est validée par IBIG, la commission apparaît en statut PENDING dans Mes Commissions." },
      { q: "Quelle est la différence entre PENDING, VALIDATED et PAID ?", a: "PENDING : en vérification. VALIDATED : confirmée, en attente de virement. PAID : versée sur votre compte." },
      { q: "Puis-je voir le détail de chaque commission ?", a: "Oui, cliquez sur une commission dans Mes Commissions pour voir produit, montant, taux, niveau et statut." },
      { q: "Mes commissions peuvent-elles être annulées ?", a: "Oui si la vente est annulée (remboursement, fraude) — les commissions déjà versées ne sont pas récupérées." },
      { q: "Comment obtenir mon attestation fiscale annuelle ?", a: "Dans Mes Paiements → « Attestation fiscale 2026 » : récapitulatif imprimable ou exportable en PDF." },
      { q: "Comment calculer ma commission sur un abonnement mensuel ?", a: "Commission mensuelle = Prix mensuel × Taux N1 × Coefficient statut, versée chaque mois de renouvellement." },
      { q: "Y a-t-il un plafond maximum de commissions par mois ?", a: "Non, il n'y a pas de plafond — plus vous vendez, plus vous gagnez, sans limite mensuelle." },
      { q: "Les commissions sont-elles imposables ?", a: "Oui, vos revenus IBIG sont imposables selon votre situation fiscale locale — déclarez-les à votre administration." },
      { q: "Comment les commissions N2 et N3 sont-elles calculées ?", a: "N2 = généralement la moitié du taux N1 ; N3 = la moitié du taux N2. Ex: N1=20%, N2=10%, N3=5%." },
      { q: "Puis-je cumuler des commissions N1 et N2 sur la même vente ?", a: "Non, une vente génère soit une commission N1 (vous avez vendu) soit N2 (votre filleul a vendu) — pas les deux." },
      { q: "Y a-t-il des commissions sur les renouvellements automatiques ?", a: "Oui, les renouvellements d'abonnements SaaS génèrent la même commission récurrente que la vente initiale." },
      { q: "Comment fonctionnent les commissions sur les produits 'Sur devis' ?", a: "La commission est calculée sur le montant final du devis validé et signé par le client." },
      { q: "Y a-t-il des commissions sur les essais gratuits (trials) ?", a: "Non, les trials gratuits ne génèrent pas de commission ; la commission s'active dès le premier paiement." },
      { q: "Puis-je voir un historique complet de toutes mes commissions ?", a: "Oui, dans Mes Commissions, tous les historiques depuis votre inscription sont disponibles avec filtres par date." },
      { q: "Comment vérifier que mes commissions ont été correctement calculées ?", a: "Vérifiez le taux affiché sur la commission vs la fiche produit ; signalez toute divergence au support." },
      { q: "Y a-t-il des commissions sur les ventes réalisées avant ma validation KYC ?", a: "Oui, les commissions s'accumulent pendant le KYC et sont versées dès sa validation." },
      { q: "Comment comparer mes commissions d'un mois à l'autre ?", a: "Dans Analytics → Revenus, un graphique mensuel compare vos commissions sur 12 mois glissants." },
      { q: "Y a-t-il des commissions sur le panier moyen (upsell) d'un client ?", a: "Oui, si votre client ajoute un produit additionnel lors du même parcours, la commission vous revient également." },
      { q: "Comment sont gérées les commissions en cas de fraude détectée ?", a: "Les commissions sur ventes frauduleuses sont annulées ; si vous aviez signalé la vente de bonne foi, aucune pénalité." },
      { q: "Puis-je céder mes commissions à quelqu'un d'autre ?", a: "Non, les commissions sont personnelles et versées uniquement sur votre compte de paiement déclaré." },
      { q: "Y a-t-il des commissions sur les achats répétés du même client ?", a: "Oui, chaque achat d'un client passé par votre lien dans les 30 jours génère une nouvelle commission." },
      { q: "Comment est calculé le coefficient de statut ?", a: "Le coefficient est défini dans le Plan de compensation — ex: SILVER × 1.05, GOLD × 1.10, MASTER × 1.20." },
      { q: "Les commissions sont-elles calculées sur le prix HT ou TTC ?", a: "Sur le prix HT hors TVA — vérifiez la fiche produit pour la base de calcul exacte." },
      { q: "Puis-je simuler mes revenus avant d'activer un produit ?", a: "Oui, dans Simulateur de gains, sélectionnez n'importe quel produit du catalogue pour simuler vos revenus." },
      { q: "Comment connaître le taux exact d'un produit avant activation ?", a: "Sur la fiche produit dans Mes Produits, le taux N1 est affiché avant toute activation." },
      { q: "Mes commissions changent-elles si le client obtient une réduction ?", a: "Oui, votre commission est calculée sur le montant réellement payé par le client après réduction." },
      { q: "Comment fonctionne le bonus de performance mensuelle ?", a: "Si vous dépassez un seuil de ventes défini dans les Challenges, un bonus en espèces est ajouté à vos commissions." },
      { q: "Les commissions de mes filleuls N2 et N3 sont-elles visibles dans mon tableau de bord ?", a: "Oui, dans Mes Commissions, filtrez par niveau (N1/N2/N3) pour voir vos revenus passifs réseau." },
      { q: "Comment exporter mon relevé de commissions pour mon expert-comptable ?", a: "Dans Mes Commissions → Export : téléchargez un CSV ou PDF avec toutes les commissions filtrées par période." },
      { q: "Y a-t-il une commission de bienvenue pour le premier partenaire recruté ?", a: "Des bonus de parrainage peuvent être proposés lors de campagnes spéciales — suivez vos Notifications." },
      { q: "Comment connaître le montant total gagné depuis le début de mon partenariat ?", a: "Dans Mon Portefeuille, le cumul total de commissions depuis votre inscription est affiché en haut de page." },
      { q: "Puis-je contester une commission que je juge mal calculée ?", a: "Oui, via le support IBIG avec le numéro de la commission et votre calcul attendu — délai de traitement 48h." },
      { q: "Y a-t-il des commissions sur les formations gratuites IBIG ?", a: "Non, seules les formations payantes génèrent des commissions — les sessions gratuites sont hors programme affilié." },
      { q: "Que se passe-t-il avec mes commissions en cas d'annulation partielle ?", a: "La commission est recalculée sur le montant effectivement payé après annulation partielle du bon de commande." },
      { q: "Comment les commissions challenges sont-elles imposées ?", a: "Comme des revenus ordinaires — incluez-les dans votre déclaration fiscale avec vos autres commissions IBIG." },
      { q: "Y a-t-il un relevé mensuel automatique de mes commissions ?", a: "Oui, un email récapitulatif mensuel est envoyé le 1er de chaque mois avec vos commissions du mois précédent." },
      { q: "Puis-je voir mes commissions projetées pour les prochains mois ?", a: "Le Simulateur de gains estime vos revenus futurs basés sur votre activité actuelle et vos objectifs définis." },
      { q: "Les commissions N1 sont-elles toujours plus élevées que N2 ?", a: "Oui par conception — N1 est toujours le taux le plus élevé, N2 et N3 sont des fractions décroissantes de N1." },
      { q: "Y a-t-il des commissions sur les ventes groupées ?", a: "Oui, si un client achète plusieurs produits via votre lien, chaque produit génère sa propre commission." },
      { q: "Mes commissions N2 s'arrêtent-elles si mon filleul quitte IBIG ?", a: "Oui, les commissions N2 cessent dès que le filleul est inactif ou désinscrit — encouragez-les à rester actifs." },
      { q: "Y a-t-il une commission de rétention pour les clients longue durée ?", a: "Non spécifiquement, mais les SaaS génèrent automatiquement des commissions récurrentes tant que le client reste abonné." },
      { q: "Puis-je réinvestir mes commissions IBIG dans des produits IBIG ?", a: "Non, les commissions ne peuvent pas être directement converties en achats sur la plateforme — elles sont versées en espèces." },
      { q: "Comment calculer mon revenu mensuel potentiel avec mon réseau actuel ?", a: "Utilisez le Simulateur de gains → entrez vos ventes N1, N2, N3 et votre statut pour obtenir une projection précise." },
      { q: "Y a-t-il des commissions différentes pour la diaspora ?", a: "Non, les taux de commission sont identiques pour tous les partenaires quel que soit leur pays de résidence." },
      { q: "Les commissions IBIG sont-elles en FCFA ou convertibles en euros ?", a: "En FCFA par défaut ; les virements internationaux sont convertis au taux du jour pour les partenaires diaspora." },
    ],
  },
  {
    icon: "🏦",
    title: "Paiements & Virements",
    items: [
      { q: "Comment recevoir mes paiements ?", a: "Configurez votre méthode dans Mes Paiements → Configurer : Orange Money, Wave, MTN MoMo ou virement bancaire." },
      { q: "Quel est le seuil minimum de paiement ?", a: "5 000 FCFA par défaut, ajustable de 1 000 à 50 000 FCFA selon votre préférence dans Mes Paiements." },
      { q: "Comment demander un virement ?", a: "Si solde ≥ seuil et KYC validé, cliquez sur « Demander un virement » — traité sous 48h ouvrées." },
      { q: "Les virements sont-ils automatiques ou manuels ?", a: "Manuel actuellement ; cliquez sur « Demander un virement » quand votre solde est suffisant." },
      { q: "Des frais sont-ils prélevés sur mes commissions ?", a: "Des frais de transaction peuvent s'appliquer selon la méthode (Orange Money, virement SWIFT) — visibles avant confirmation." },
      { q: "Puis-je changer de méthode de paiement ?", a: "Oui à tout moment dans Mes Paiements → Configurer ; les virements en cours utilisent encore l'ancienne méthode." },
      { q: "Combien de temps prend un virement Orange Money ou Wave ?", a: "Instantané à quelques minutes après validation IBIG ; jusqu'à 24h en cas de problème technique." },
      { q: "Comment obtenir un reçu de virement pour ma comptabilité ?", a: "Dans Mes Paiements, chaque virement a un bouton « Reçu » — PDF officiel avec référence, montant et date." },
      { q: "Je n'ai pas reçu mon virement, que faire ?", a: "Vérifiez le statut (PAID = effectué), confirmez votre numéro, puis contactez le support après 48h avec la référence." },
      { q: "Puis-je recevoir mes paiements en devises (EUR, USD) ?", a: "Oui avec un virement SWIFT international ; vos commissions FCFA sont converties au taux du jour du virement." },
      { q: "Puis-je avoir plusieurs méthodes de paiement configurées ?", a: "Oui, configurez plusieurs méthodes et choisissez la méthode active pour chaque demande de virement." },
      { q: "Y a-t-il un montant maximum par virement ?", a: "Non de limite stricte, mais des vérifications supplémentaires peuvent s'appliquer pour les montants très élevés." },
      { q: "Que faire si mon numéro mobile money a changé ?", a: "Mettez à jour votre numéro dans Mes Paiements avant de faire votre prochaine demande de virement." },
      { q: "Y a-t-il un frais de traitement pour les virements bancaires internationaux ?", a: "Oui, des frais SWIFT s'appliquent (environ 5 à 15 EUR selon les banques) — visibles avant confirmation." },
      { q: "Combien de temps les commissions restent-elles en statut PENDING ?", a: "1 à 5 jours ouvrés selon le volume de ventes à vérifier ; IBIG traite les validations par lots quotidiens." },
      { q: "Puis-je demander un virement partiel de mon solde ?", a: "Non, chaque demande porte sur la totalité du solde validé disponible au moment de la demande." },
      { q: "Y a-t-il un historique de tous mes virements reçus ?", a: "Oui, dans Mes Paiements → Historique : liste complète de tous les virements avec date, montant et référence." },
      { q: "Comment IBIG protège-t-il mes informations bancaires ?", a: "Chiffrement AES-256, accès restreint, jamais stockées en clair — conformes aux normes PCI-DSS applicables." },
      { q: "Comment faire si je n'ai pas de compte bancaire ?", a: "Utilisez Orange Money, Wave ou MTN MoMo — ces services ne nécessitent pas de compte bancaire traditionnel." },
      { q: "Y a-t-il un relevé annuel pour ma déclaration fiscale ?", a: "Oui, l'attestation fiscale dans Mes Paiements récapitule toutes les commissions et virements de l'année." },
      { q: "Mon solde de commissions expire-t-il si je ne demande pas le versement ?", a: "Non, votre solde est conservé indéfiniment — demandez un virement quand vous le souhaitez." },
      { q: "Puis-je annuler une demande de virement en cours ?", a: "Contactez le support immédiatement — si le virement n'est pas encore initié, l'annulation est possible." },
      { q: "Les virements sont-ils traités les weekends ?", a: "Non, les virements sont traités uniquement les jours ouvrés ; les demandes du weekend sont traitées le lundi." },
      { q: "Comment configurer un virement vers MTN MoMo ?", a: "Dans Mes Paiements → Configurer → Mobile Money : sélectionnez MTN MoMo et entrez votre numéro." },
      { q: "Y a-t-il des pays où les virements IBIG ne sont pas disponibles ?", a: "Les virements couvrent la majorité des pays africains et la diaspora ; contactez le support pour votre pays spécifique." },
      { q: "Que faire si mon virement a été envoyé au mauvais numéro ?", a: "Contactez le support immédiatement avec la preuve d'erreur — les corrections sont traitées au cas par cas." },
      { q: "Comment calculer mes gains nets après frais de virement ?", a: "Montant brut - frais de transaction affiché avant confirmation = montant net reçu sur votre compte." },
      { q: "Y a-t-il un système de wallet interne IBIG ?", a: "Oui, Mon Portefeuille affiche votre solde disponible ; les virements vers mobile money/banque se font depuis là." },
      { q: "Comment fonctionne le paiement via Wave ?", a: "Configurez votre numéro Wave dans Mes Paiements ; le virement arrive sur votre compte Wave directement." },
      { q: "Y a-t-il des délais spéciaux pendant les fêtes (Noël, Ramadan) ?", a: "Les délais peuvent être légèrement allongés pendant les périodes de forte activité ; planifiez vos demandes à l'avance." },
      { q: "Comment signaler un virement reçu qui semble incorrect ?", a: "Contactez le support dans les 48h avec la référence du virement et le montant attendu vs reçu." },
      { q: "Les partenaires diaspora ont-ils des conditions de paiement différentes ?", a: "Mêmes conditions mais avec options de virement international SWIFT et délais légèrement plus longs (3-5 jours)." },
      { q: "Comment vérifier le taux de change appliqué sur mon virement en devises ?", a: "Le taux est affiché avant confirmation du virement dans Mes Paiements — basé sur le taux BCEAO du jour." },
      { q: "Mon relevé de virement est-il valable comme justificatif de revenu ?", a: "Oui, le reçu officiel IBIG est accepté par de nombreux établissements financiers comme preuve de revenu." },
      { q: "Comment accéder à mes archives de virements des années précédentes ?", a: "Dans Mes Paiements → Historique, filtrez par année pour accéder à tous vos virements depuis le début." },
      { q: "Y a-t-il une limite mensuelle de virements ?", a: "Non, vous pouvez faire plusieurs demandes de virement par mois tant que votre solde est suffisant." },
      { q: "Puis-je recevoir mes paiements en crypto-monnaie ?", a: "Non actuellement — les paiements sont uniquement en FCFA via mobile money ou virement bancaire classique." },
      { q: "Y a-t-il un plafond de commissions en attente non versées ?", a: "Non, votre solde peut s'accumuler sans limite — demandez un virement à votre convenance." },
      { q: "Puis-je changer ma devise de paiement principale ?", a: "Dans Mon Profil → Préférences financières : sélectionnez FCFA ou USD/EUR pour les virements internationaux." },
      { q: "Comment obtenir une attestation de revenus de la part d'IBIG ?", a: "Contactez le support en précisant la période et l'usage — l'attestation officielle est émise sous 48h." },
      { q: "Les partenaires entreprises reçoivent-ils leurs paiements différemment ?", a: "Oui, les paiements entreprise (KYB) peuvent être faits par virement sur compte professionnel avec facture." },
      { q: "Puis-je récupérer mes commissions si je ferme mon compte ?", a: "Oui, les commissions validées sont versées avant la clôture définitive du compte — contactez le support." },
      { q: "Y a-t-il des conditions spéciales pour les partenaires avec gros volumes ?", a: "Oui, les partenaires MASTER et ELITE bénéficient de traitements prioritaires et de frais réduits sur certaines méthodes." },
      { q: "Comment éviter les erreurs lors de la configuration de mon compte de paiement ?", a: "Vérifiez deux fois votre numéro, faites un premier test avec un petit montant avant tout virement important." },
      { q: "Y a-t-il un programme de virement anticipé sur commissions futures ?", a: "Non, seules les commissions validées (VALIDATED) peuvent faire l'objet d'une demande de virement." },
      { q: "Comment sont traités les virements bancaires locaux (banques ivoiriennes) ?", a: "Virements IBAN local traités sous 24-48h ouvrées via les réseaux bancaires locaux UEMOA." },
      { q: "Puis-je configurer un virement automatique mensuel ?", a: "Pas encore en automatique — une fonctionnalité de virement récurrent mensuel est en cours de développement." },
      { q: "Comment savoir si mon virement a été initié côté IBIG ?", a: "Le statut dans Mes Paiements passe de REQUESTED à PROCESSING puis PAID — avec notification email à chaque étape." },
      { q: "Y a-t-il un numéro de référence unique pour chaque virement ?", a: "Oui, chaque virement a une référence unique REF-XXXXX — conservez-la pour toute réclamation support." },
      { q: "Mes données bancaires sont-elles visibles par d'autres partenaires ?", a: "Non, vos informations financières sont strictement privées et inaccessibles à tout autre utilisateur." },
    ],
  },
  {
    icon: "🌳",
    title: "Réseau & Parrainage",
    items: [
      { q: "Comment parrainer un nouveau partenaire ?", a: "Partagez votre lien de parrainage (Mon Réseau) — l'inscrit devient votre filleul N1 et ses ventes génèrent des N2 pour vous." },
      { q: "Combien de niveaux de parrainage sont pris en compte ?", a: "3 niveaux : N1 (vos filleuls directs), N2 (leurs filleuls), N3 (filleuls de vos N2) — au-delà, pas de commission." },
      { q: "Quel est le taux de commission sur les ventes de mon réseau ?", a: "Variable par produit — généralement N1 = taux plein, N2 = moitié, N3 = quart. Ex: 20% / 10% / 5%." },
      { q: "Comment voir la performance de mon réseau ?", a: "Dans Mon Réseau : filleuls par niveau, ventes du mois, commissions générées, et arbre visuel interactif." },
      { q: "Puis-je voir qui sont mes filleuls ?", a: "Oui, vos filleuls N1 sont listés avec prénom, statut et ventes ; N2 et N3 en chiffres agrégés (confidentialité)." },
      { q: "Un filleul peut-il changer de parrain ?", a: "Non, le parrainage est permanent et attribué définitivement lors de l'inscription via votre lien." },
      { q: "Que se passe-t-il si mon filleul se désinscrit ?", a: "Vos commissions passées restent acquises ; les ventes futures ne génèrent plus de commission." },
      { q: "Y a-t-il des bonus pour le recrutement de nouveaux partenaires ?", a: "Des bonus de parrainage ponctuels existent lors de challenges ou campagnes spéciales — suivez vos Notifications." },
      { q: "Mes messages WhatsApp modèles sont-ils personnalisables ?", a: "Copiez le texte pré-rempli avec votre code et adaptez-le à votre style — conservez votre lien de parrainage." },
      { q: "Comment accéder à l'arbre visuel de mon réseau ?", a: "Réseau → Arbre de réseau : arbre interactif sur 3 niveaux avec indicateurs de performance par nœud." },
      { q: "Puis-je voir les ventes de mes filleuls N1 en détail ?", a: "Oui, dans Mon Réseau → filleul N1 → Détails : nombre de ventes et commissions générées pour vous ce mois." },
      { q: "Comment motiver mes filleuls inactifs ?", a: "Partagez des conseils, succès stories, nouvelles campagnes IBIG et challenges en cours via WhatsApp ou appel direct." },
      { q: "Puis-je parrainer un membre de ma famille ?", a: "Oui, aucune restriction familiale — chaque membre s'inscrit individuellement avec son propre email et pièce d'identité." },
      { q: "Mon réseau peut-il opérer dans plusieurs pays ?", a: "Oui, vos filleuls peuvent être dans n'importe quel pays où IBIG est actif — commissions calculées en FCFA." },
      { q: "Y a-t-il un bonus si mon filleul monte en statut SILVER ?", a: "Il peut y avoir des bonus réseau selon les campagnes actives — consultez les Challenges pour les détails." },
      { q: "Comment organiser une réunion de réseau en ligne ?", a: "Organisez un Zoom ou Google Meet — utilisez les slides et vidéos du Kit Marketing pour présenter IBIG." },
      { q: "Comment dupliquer mon système de vente à mes filleuls ?", a: "Créez un guide personnel ou partagez votre méthode via un groupe WhatsApp réseau — IBIG fournit aussi les ressources officielles." },
      { q: "Y a-t-il un programme de mentoring partenaire ?", a: "Les partenaires MASTER et ELITE peuvent devenir mentors officiels IBIG — contactez le support pour postuler." },
      { q: "Comment identifier les filleuls à fort potentiel ?", a: "Dans Mon Réseau, filtrez par activité récente (ventes, clics) — concentrez votre accompagnement sur les plus actifs." },
      { q: "Puis-je voir combien mes filleuls ont gagné en commissions ?", a: "Non, les gains individuels de vos filleuls sont confidentiels — vous voyez seulement vos commissions N2/N3 générées." },
      { q: "Comment exporter la liste de mon réseau en CSV ?", a: "Dans Export (section Ressources), sélectionnez « Réseau » pour télécharger la liste de vos filleuls." },
      { q: "Y a-t-il un badge spécial pour les partenaires avec 100+ filleuls ?", a: "Oui, le badge « Super Recruteur » est décerné aux partenaires ayant 100+ filleuls directs actifs." },
      { q: "Comment calculer mon potentiel de revenus passifs avec mon réseau actuel ?", a: "Dans Simulateur de gains, entrez vos N2 et N3 actuels avec le produit le plus vendu dans votre réseau." },
      { q: "Comment attirer des filleuls qualifiés (professionnels du commerce) ?", a: "Ciblez des groupes professionnels LinkedIn, des réseaux d'entrepreneurs, des anciens collègues en vente ou commerce." },
      { q: "Puis-je avoir plusieurs sponsors/parrains pour différents produits ?", a: "Non, le parrainage est unique — un seul parrain par partenaire pour l'ensemble des produits IBIG." },
      { q: "Comment accéder aux outils de recrutement (flyers réseau, vidéos) ?", a: "Dans Kit Marketing → section Réseau : téléchargez les flyers, vidéos et guides pour recruter des partenaires." },
      { q: "Y a-t-il des réunions réseau organisées par IBIG chaque mois ?", a: "Oui, IBIG organise des webinaires mensuels et événements régionaux — annonces dans Événements IBIG." },
      { q: "Comment protéger mon réseau contre le débauchage par d'autres partenaires ?", a: "Le parrainage est permanent et contractuel — un filleul ne peut pas changer de parrain, il est protégé par le système." },
      { q: "Mes filleuls peuvent-ils me contacter directement via la plateforme ?", a: "Pas de messagerie directe partenaire-filleul actuellement — communiquez via WhatsApp ou téléphone." },
      { q: "Comment créer du contenu collaboratif avec mon réseau ?", a: "Organisez des posts groupés, des témoignages croisés ou des lives WhatsApp avec vos meilleurs filleuls." },
      { q: "Comment organiser un challenge interne à mon réseau ?", a: "Créez un groupe WhatsApp réseau et proposez un défi mensuel avec récompense personnelle — IBIG peut co-labelliser." },
      { q: "Puis-je recruter en dehors de mon pays de résidence ?", a: "Oui, vous pouvez recruter dans tout pays où IBIG est actif — parrainage international pleinement supporté." },
      { q: "Comment maximiser les commissions N2 et N3 ?", a: "Recrutez des filleuls actifs dans des secteurs à fort potentiel de ventes — la qualité prime sur la quantité." },
      { q: "Quelle est la taille idéale d'un réseau IBIG PARTNERS ?", a: "Qualité > quantité : 20 filleuls actifs génèrent plus que 100 inactifs — visez 10-30 filleuls solides au départ." },
      { q: "Puis-je parrainer quelqu'un qui était déjà inscrit sur IBIG sans parrain ?", a: "Non, si la personne est déjà inscrite sans parrain, elle ne peut pas être rattachée rétroactivement." },
      { q: "Y a-t-il des statistiques sur le réseau moyen d'un partenaire MASTER ?", a: "Les partenaires MASTER ont en moyenne 50+ filleuls actifs sur 3 niveaux selon les données IBIG." },
      { q: "Comment présenter le programme de parrainage à quelqu'un de sceptique ?", a: "Montrez des chiffres réels (votre attestation fiscale, vos virements reçus) plutôt que des promesses — la preuve convainc." },
      { q: "Y a-t-il un programme d'affiliation pour les agences de recrutement ?", a: "Oui, les agences peuvent devenir partenaires entreprises (KYB) et recruter des candidats pour IBIG EMPLOI & TALENTS." },
      { q: "Comment voir si mon lien de parrainage est fonctionnel ?", a: "Testez-le en navigation privée — vous verrez le formulaire d'inscription avec votre code pré-rempli." },
      { q: "Y a-t-il des ressources de formation que je peux partager à mes filleuls ?", a: "Oui, le guide démarrage, le Kit Marketing et l'Académie IBIG sont accessibles à tous les partenaires." },
      { q: "Comment faire du co-marketing avec un autre partenaire IBIG ?", a: "Collaborez librement avec d'autres partenaires — IBIG n'interdit pas la collaboration entre partenaires." },
      { q: "Mes commissions N2 et N3 s'arrêtent-elles si mon filleul change de niveau ?", a: "Non, le changement de statut d'un filleul n'affecte pas vos commissions N2/N3 qui continuent normalement." },
      { q: "Y a-t-il un système de team leader pour les gros réseaux ?", a: "Le statut MASTER et ELITE confère un rôle informel de team leader avec accès à des ressources exclusives." },
      { q: "Comment construire un réseau solide dans une ville secondaire ?", a: "Commencez par votre réseau professionnel local (chambre de commerce, associations) avant d'aller en ligne." },
      { q: "Puis-je voir le chiffre d'affaires total généré par mon réseau ?", a: "Dans Mon Réseau → Statistiques : le CA total généré par votre réseau (N1+N2+N3) sur la période sélectionnée." },
      { q: "Y a-t-il un parrainage inversé si mon filleul me surpasse ?", a: "Non, la structure de parrainage est fixe — votre filleul ne peut pas devenir votre parrain même s'il vous dépasse." },
      { q: "Comment créer un sous-programme de fidélité pour mes filleuls ?", a: "Créez votre propre système de récompense personnel (cadeaux, formations offertes) en complément du programme IBIG." },
      { q: "Y a-t-il un programme pour les partenaires qui veulent former leur équipe ?", a: "Le Kit Marketing inclut des ressources de formation réseau ; les partenaires ELITE peuvent animer des sessions officielles." },
      { q: "Comment savoir combien de filleuls actifs j'ai ce mois ?", a: "Dans Mon Réseau → Statistiques du mois : nombre de filleuls N1 ayant eu au moins une activité dans les 30 derniers jours." },
      { q: "Mes filleuls voient-ils mon nom comme parrain dans leur espace ?", a: "Oui, les filleuls voient le nom de leur parrain dans Mon Réseau → Mon Parrain." },
    ],
  },
  {
    icon: "🏆",
    title: "Statuts & Progression",
    items: [
      { q: "Quels sont les 5 statuts IBIG PARTNERS ?", a: "STARTER (débutant), SILVER (2+ ventes), GOLD (5+ ventes), MASTER (15+ ventes + réseau actif), ELITE (top partenaire)." },
      { q: "Comment passer de STARTER à SILVER ?", a: "Confirmez au moins 2 ventes et 1 filleul actif — le passage est automatique et vous êtes notifié par email." },
      { q: "Le passage de statut est-il définitif ?", a: "Non, réévalué mensuellement — maintenez une activité régulière pour conserver votre statut." },
      { q: "Comment voir ma progression vers le statut suivant ?", a: "Sur le Dashboard et dans Mes Objectifs : barre de progression avec critères détaillés du prochain statut." },
      { q: "Qu'est-ce que les challenges et comment y participer ?", a: "Défis mensuels (ex: 5 ventes/30 jours) avec bonus espèces — participation automatique dès que vous remplissez les conditions." },
      { q: "Qu'est-ce que les streaks ?", a: "Série de jours consécutifs avec activité (clic, vente, prospect) — plus la série est longue, plus vous gagnez de points bonus." },
      { q: "À quoi servent les points IBIG ?", a: "Gagnés via ventes, challenges et streaks — échangeables contre récompenses dans la Boutique (cashback, cadeaux)." },
      { q: "Comment fonctionne le classement mensuel ?", a: "Classement par CA généré, remis à zéro le 1er du mois — motivationnel, ne conditionne pas les commissions." },
      { q: "Mes badges sont-ils permanents ?", a: "Oui, une fois obtenu (« Première vente », « 10 filleuls ») le badge reste définitivement sur votre profil." },
      { q: "Qu'est-ce que le programme VIP IBIG ?", a: "Réservé aux ELITE et MASTER sélectionnés : coaching individuel, accès anticipé aux produits, commissions majorées." },
      { q: "Y a-t-il un délai minimal pour monter de statut ?", a: "Non, si vous remplissez les critères en 1 semaine, le statut change automatiquement sans délai minimal." },
      { q: "Comment contester une rétrogradation de statut ?", a: "Contactez le support avec vos données de ventes si vous pensez que la rétrogradation est une erreur — traitement 48h." },
      { q: "Y a-t-il un avantage financier immédiat quand je monte de statut ?", a: "Oui, le coefficient de commission augmente dès le changement de statut et s'applique aux ventes suivantes." },
      { q: "Les partenaires ELITE ont-ils un manager dédié ?", a: "Oui, les partenaires ELITE bénéficient d'un account manager IBIG pour les accompagner personnellement." },
      { q: "Les ventes N2 et N3 comptent-elles pour mon statut ?", a: "Non, seules vos ventes directes N1 (confirmées) sont prises en compte pour les critères de statut." },
      { q: "Y a-t-il un statut honorifique pour les vétérans 5+ ans ?", a: "Le statut ELITE inclut une reconnaissance d'ancienneté ; IBIG peut créer des distinctions spéciales pour les vétérans." },
      { q: "Mon statut est-il visible sur ma page publique ?", a: "Oui, votre badge de statut (SILVER, GOLD…) est affiché sur votre profil public et votre page /p/CODE." },
      { q: "Y a-t-il un statut Ambassadeur IBIG au-dessus d'ELITE ?", a: "Le titre d'Ambassadeur est attribué exceptionnellement par IBIG à des partenaires ELITE aux mérites extraordinaires." },
      { q: "Y a-t-il des formations obligatoires pour atteindre certains statuts ?", a: "Non obligatoires, mais certaines formations recommandées dans l'Académie accélèrent votre progression." },
      { q: "Les challenges mensuels offrent-ils des points de statut ?", a: "Non directement, mais les ventes générées grâce aux challenges comptent pour vos critères de progression de statut." },
      { q: "Y a-t-il un certificat de reconnaissance pour chaque niveau ?", a: "Oui, un certificat numérique est émis à chaque montée en statut — téléchargeable dans Mes Badges." },
      { q: "Puis-je être rétrogradé si je ne déclare aucune vente pendant 3 mois ?", a: "Oui, l'inactivité prolongée peut entraîner une rétrogradation lors de la réévaluation mensuelle." },
      { q: "Comment les entreprises (KYB) progressent-elles en statut ?", a: "Mêmes critères que les individus — les ventes déclarées par l'entreprise comptent pour le statut du compte." },
      { q: "Y a-t-il un espace communautaire réservé aux partenaires GOLD+ ?", a: "Oui, un groupe WhatsApp et un forum privé sont accessibles aux partenaires GOLD, MASTER et ELITE." },
      { q: "Comment utiliser mon statut GOLD pour convaincre un prospect ?", a: "Le statut GOLD atteste de votre sérieux et expertise — mentionnez-le pour renforcer votre crédibilité commerciale." },
      { q: "Puis-je utiliser le logo de mon statut dans mes communications ?", a: "Oui, les badges officiels IBIG par statut sont disponibles dans Kit Marketing pour vos communications." },
      { q: "Y a-t-il des événements VIP pour les partenaires MASTER et ELITE ?", a: "Oui, conférences annuelles, dîners de gala et sessions de formation exclusives sont organisés pour les top partenaires." },
      { q: "Comment le statut SILVER change-t-il concrètement mes commissions ?", a: "Le coefficient SILVER augmente vos commissions N1 d'environ 5% — consultez le Plan de compensation pour le détail." },
      { q: "Y a-t-il un programme de mentorat des ELITE vers les STARTER ?", a: "Oui, le programme Coach & Mentor IBIG met en relation des partenaires ELITE avec des STARTER volontaires." },
      { q: "Comment suivre ma progression semaine par semaine ?", a: "Le score hebdomadaire envoyé chaque lundi détaille vos ventes, points et progression vers le prochain statut." },
      { q: "Le simulateur de gains tient-il compte de mon statut actuel ?", a: "Oui, le simulateur intègre votre statut actuel et propose une simulation avec le statut suivant pour comparaison." },
      { q: "Y a-t-il un historique de mes changements de statut ?", a: "Oui, dans Mon Profil → Historique de statut : toutes les montées et rétrogradations depuis votre inscription." },
      { q: "Puis-je voir le statut de mes filleuls dans mon tableau de bord ?", a: "Oui, dans Mon Réseau, le statut de chaque filleul N1 est affiché (STARTER, SILVER, etc.)." },
      { q: "Comment le statut ELITE influence-t-il ma crédibilité auprès des clients ?", a: "Le badge ELITE signale votre expertise prouvée — utilisez-le comme argument de confiance auprès des décideurs." },
      { q: "Y a-t-il un quota de ventes par type de produit requis pour progresser ?", a: "Non, les critères portent sur le nombre total de ventes confirmées, pas sur leur type ou branche." },
      { q: "Les avantages du statut GOLD s'appliquent-ils rétroactivement ?", a: "Non, les avantages s'appliquent aux ventes futures après le changement de statut — pas aux ventes passées." },
      { q: "Y a-t-il un programme d'accélération pour les nouveaux partenaires ?", a: "Oui, le programme Boost Starter offre des challenges exclusifs aux partenaires de moins de 90 jours." },
      { q: "Puis-je accéder aux avantages d'un statut supérieur temporairement ?", a: "Non, les avantages sont strictement liés à votre statut actuel — atteignez le statut pour en bénéficier." },
      { q: "Y a-t-il une cérémonie de remise de statut pour les partenaires ELITE ?", a: "Oui, les promotions ELITE sont célébrées lors des événements IBIG avec reconnaissance officielle." },
      { q: "Comment savoir combien de partenaires sont à chaque niveau ?", a: "Les statistiques globales du réseau sont publiées périodiquement dans les annonces IBIG — pas de données en temps réel." },
      { q: "Y a-t-il des challenges différents selon mon statut ?", a: "Oui, les challenges sont calibrés par niveau — les STARTER ont des objectifs plus accessibles que les MASTER." },
      { q: "Les filleuls que je recrute comptent-ils pour mon statut ?", a: "Indirectement — avoir des filleuls actifs est un critère pour MASTER, mais le nombre de filleuls seul ne suffit pas." },
      { q: "Comment voir les critères exacts de chaque statut ?", a: "Dans Espace → Plan de compensation : tableau détaillé des critères et avantages de chaque statut." },
      { q: "Y a-t-il un bonus cash lors du passage au statut GOLD ?", a: "Des bonus peuvent être proposés lors de campagnes de promotion de statut — suivez les annonces dans Challenges." },
      { q: "Mon statut IBIG est-il reconnu en dehors du réseau IBIG PARTNERS ?", a: "Le certificat IBIG peut être présenté comme preuve d'expérience commerciale dans certains contextes professionnels." },
      { q: "Comment le programme VIP est-il accessible depuis l'espace partenaire ?", a: "Dans Compte → Programme VIP : vérifiez votre éligibilité et activez vos avantages VIP disponibles." },
      { q: "Les badges correspondent-ils aux niveaux de statut ?", a: "Oui et non — certains badges récompensent des actions spécifiques (première vente, 100 clics) indépendamment du statut." },
      { q: "Les partenaires de la diaspora ont-ils les mêmes critères de statut ?", a: "Oui, les critères sont identiques partout — seuls les délais de paiement peuvent différer." },
      { q: "Comment le statut MASTER m'aide-t-il à vendre plus ?", a: "Accès à des produits premium, coaching dédié, commissions majorées et crédibilité renforcée auprès des clients." },
      { q: "Y a-t-il un calcul de « score global » combinant statut, ventes et réseau ?", a: "Le score hebdomadaire hebdo calcule statut + ventes + prospects — il reflète votre performance globale sur 7 jours." },
    ],
  },
  {
    icon: "⚙️",
    title: "Outils & Fonctionnalités",
    items: [
      { q: "Comment déclarer une vente ?", a: "Mes Ventes → Déclarer une vente : choisissez le produit, entrez le montant, joignez une preuve et soumettez." },
      { q: "Qu'est-ce qu'une preuve de vente et est-ce obligatoire ?", a: "Capture de paiement, email de confirmation ou bon de commande signé — sans preuve, la validation est plus lente." },
      { q: "Comment ajouter un prospect dans mon CRM ?", a: "Mes Prospects → Ajouter : entrez nom, contact, produit d'intérêt, statut et notes de suivi." },
      { q: "Comment configurer un webhook ?", a: "Compte → Webhook/API : entrez votre URL endpoint, générez un secret HMAC, et IBIG envoie un POST JSON à chaque vente confirmée." },
      { q: "Comment vérifier la signature d'un webhook reçu ?", a: "Calculez HMAC-SHA256 du corps JSON avec votre secret et comparez avec le header X-IBIG-Signature : sha256=XXX." },
      { q: "Les notifications en temps réel fonctionnent-elles sur mobile ?", a: "Oui, la cloche se met à jour toutes les 30 secondes ; les notifications push fonctionnent si activées dans votre navigateur." },
      { q: "Comment accéder à mon rapport mensuel ?", a: "Ventes → Mon Rapport mensuel : récapitulatif clics, ventes, commissions et comparaison mois précédent, exportable en PDF." },
      { q: "Comment utiliser le Coach IA ?", a: "Formation → Coach IA : posez vos questions sur les ventes, les objections clients ou le développement de votre réseau." },
      { q: "Comment générer le PDF Guide partenaire ?", a: "Ressources → Guide partenaire → « Télécharger » : PDF en temps réel avec dernières infos sur branches et taux." },
      { q: "À quoi sert l'export de données ?", a: "Export → téléchargez en CSV votre liste de prospects, commissions, ventes ou réseau pour vos analyses et comptabilité." },
      { q: "Comment accéder à mes statistiques en temps réel ?", a: "Analytics (section Vue d'ensemble) : tableaux de bord avec clics, ventes, commissions en temps réel." },
      { q: "Comment configurer des alertes intelligentes ?", a: "Compte → Alertes intelligentes : configurez des notifications pour seuils de ventes, nouveaux filleuls, paiements reçus." },
      { q: "Comment utiliser le simulateur de gains avant de rencontrer un prospect ?", a: "Simulateur de gains : sélectionnez le produit cible du prospect, entrez les quantités prévues et obtenez une projection." },
      { q: "Y a-t-il un outil de prise de rendez-vous intégré ?", a: "Oui, dans Mes Rendez-vous : créez, gérez et suivez vos RDV clients avec rappels automatiques." },
      { q: "Comment enregistrer une note de visite client ?", a: "Dans la fiche prospect ou client → ajouter une note : texte libre horodaté, visible uniquement par vous." },
      { q: "La section Mon Marché m'aide-t-il à identifier mes clients potentiels ?", a: "Oui, Mon Marché affiche les opportunités commerciales dans votre région et secteur — filtrables par branche." },
      { q: "Comment accéder aux scripts de vente par produit ?", a: "Académie IBIG → Scripts de vente : argumentaires et réponses aux objections pour chaque produit du catalogue." },
      { q: "Comment accéder au kit marketing complet par produit ?", a: "Ressources → Kit Marketing → sélectionnez un produit : flyers, visuels, scripts et vidéos téléchargeables." },
      { q: "Y a-t-il des modèles d'emails de prospection ?", a: "Oui, dans Kit Marketing → Emails : modèles personnalisables par produit, branche et type de client cible." },
      { q: "Comment utiliser la boutique de points (Boutique CP) ?", a: "Boutique CP (Catalogue) : échangez vos points contre réductions, cashback ou cadeaux IBIG selon votre solde de points." },
      { q: "Y a-t-il une section pour les appels d'offres ?", a: "Oui, Missions → Appels à partenaires : opportunités d'affaires publiées par IBIG et ses partenaires institutionnels." },
      { q: "Comment utiliser IBIG CONNECT ?", a: "Réseau → IBIG CONNECT : plateforme de networking pour collaborer avec d'autres partenaires et trouver des opportunités." },
      { q: "Comment configurer les notifications push ?", a: "Dans votre navigateur, autorisez les notifications pour ibigpartners.com — confirmez dans Compte → Préf. notifications." },
      { q: "Y a-t-il des intégrations natives avec Zapier ou Make ?", a: "Via le webhook et l'API Key, connectez IBIG à Zapier ou Make pour automatiser vos workflows commerciaux." },
      { q: "Comment partager directement une fiche produit depuis la plateforme ?", a: "Dans Mes Produits → fiche → Partager : générez un lien ou QR code vers votre page produit personnalisée." },
      { q: "Comment accéder aux témoignages de partenaires pour mes présentations ?", a: "Kit Marketing → Témoignages : vidéos et citations de partenaires actifs, utilisables dans vos présentations." },
      { q: "Comment utiliser le module Ma Vitrine ?", a: "Catalogue → Ma Vitrine : personnalisez votre page de présentation partenaire avec votre bio, spécialités et produits phares." },
      { q: "Comment exporter mes données prospects vers un CRM externe ?", a: "Export → Prospects : téléchargez en CSV compatible avec HubSpot, Salesforce, Notion ou tout autre CRM." },
      { q: "Y a-t-il un historique de toutes mes activités sur la plateforme ?", a: "Dans Mon Profil → Historique d'activité : log chronologique de toutes vos actions (déclarations, clics, ajouts de prospects)." },
      { q: "Comment créer des rapports personnalisés sur mes performances ?", a: "Analytics → Rapports personnalisés : sélectionnez métriques, période et granularité pour créer votre rapport sur mesure." },
      { q: "Y a-t-il des vidéos tutoriels sur l'utilisation des outils ?", a: "Oui, Académie IBIG → Tutoriels plateforme : vidéos courtes pour maîtriser chaque section de l'espace partenaire." },
      { q: "Y a-t-il un système de ticketing pour les bugs de la plateforme ?", a: "Oui, Compte → Support → Nouveau ticket : catégorisez votre bug avec captures d'écran et description détaillée." },
      { q: "Comment accéder à l'API Partenaire ?", a: "Ressources → API Key : générez votre clé API et consultez la documentation technique pour les intégrations." },
      { q: "Comment synchroniser mes données avec mon Google Agenda ?", a: "Dans Mes Rendez-vous → Synchroniser : exportez en format iCal compatible Google Agenda, Outlook et Apple Calendar." },
      { q: "Comment créer un devis depuis la plateforme ?", a: "Mes Ventes → Nouveau devis : sélectionnez le produit, le client, ajoutez les conditions et envoyez par email directement." },
      { q: "Y a-t-il un outil de veille sur les nouvelles fonctionnalités ?", a: "Dans Notifications → Annonces IBIG : toutes les nouvelles fonctionnalités sont annoncées en temps réel." },
      { q: "Comment accéder aux rapports de ventes de mon réseau ?", a: "Mon Réseau → Statistiques réseau : CA total N1+N2+N3, commissions générées et tendances sur 12 mois." },
      { q: "Comment utiliser la section Recommandations de missions ?", a: "Missions → Missions recommandées : IBIG vous propose des missions alignées avec vos produits actifs et votre statut." },
      { q: "Y a-t-il un mode hors-ligne pour accéder aux fiches produits ?", a: "Non actuellement, une connexion internet est requise — téléchargez les PDF de fiches produits depuis Kit Marketing." },
      { q: "Comment configurer des relances automatiques pour mes prospects ?", a: "Dans Mes Prospects → Rappels : définissez une date de relance et recevez une notification le jour J." },
      { q: "Comment accéder à la section Opportunités & Annonces ?", a: "Missions → Opportunités & Annonces : liste des opportunités d'affaires et partenariats disponibles pour les partenaires actifs." },
      { q: "Y a-t-il une application iPad ou tablette optimisée ?", a: "L'interface web est responsive et optimisée pour tablette — une application native tablette est en cours de développement." },
      { q: "Comment utiliser la section Mes Besoins ?", a: "Missions → Mes Besoins : publiez vos besoins commerciaux pour qu'IBIG ou d'autres partenaires puissent vous aider." },
      { q: "Comment accéder à l'Académie IBIG ?", a: "Formation → Académie IBIG : formations sur les produits, techniques de vente, et développement personnel pour partenaires." },
      { q: "Comment suivre la performance de mes défis en cours ?", a: "Challenges : chaque défi actif affiche votre progression en temps réel avec barre de pourcentage et temps restant." },
      { q: "Y a-t-il un outil de calcul de TVA pour mes ventes ?", a: "Non intégré — utilisez votre propre outil comptable ; les montants IBIG sont généralement indiqués TTC." },
      { q: "Comment récupérer des données supprimées accidentellement ?", a: "Contactez le support immédiatement — les données sont sauvegardées 30 jours avant suppression définitive." },
      { q: "Y a-t-il une roadmap publique des nouvelles fonctionnalités ?", a: "IBIG partage sa roadmap lors des webinaires mensuels — les grandes fonctionnalités sont annoncées en avant-première aux partenaires ELITE." },
      { q: "Comment partager mon profil partenaire complet à un prospect ?", a: "Partagez le lien /p/VOTRECODE — il affiche votre profil complet avec photo, bio, statut et produits promus." },
      { q: "Comment accéder au module de classement public ?", a: "Vue d'ensemble → Classement : top 20 des partenaires du mois par CA généré — optez-in dans Classement public." },
      { q: "Y a-t-il une fonctionnalité de messagerie directe entre partenaires ?", a: "Non actuellement — IBIG CONNECT offre du networking mais pas encore de messagerie directe entre partenaires." },
    ],
  },
  {
    icon: "💡",
    title: "Stratégies & Conseils",
    items: [
      { q: "Par où commencer quand on vient de rejoindre IBIG PARTNERS ?", a: "1. Signez le contrat. 2. Faites le KYC. 3. Activez 2-3 produits. 4. Partagez à 10 contacts professionnels. 5. Ajoutez-les dans Prospects." },
      { q: "Quelle est la meilleure façon de promouvoir les logiciels SaaS ?", a: "Ciblez les chefs de PME, proposez une démo et mettez en avant le gain de temps — la commission est récurrente chaque mois." },
      { q: "Comment promouvoir efficacement sur WhatsApp sans être bloqué ?", a: "Échanges individuels ciblés, messages contextualisés dans des groupes pros — pas de masse à des inconnus." },
      { q: "Combien de temps faut-il pour faire sa première vente ?", a: "1-4 semaines avec un effort régulier — les plus rapides vendent à leur réseau professionnel existant dès la première semaine." },
      { q: "Vaut-il mieux se concentrer sur la vente directe ou sur le recrutement ?", a: "Les deux : ventes directes = revenus immédiats élevés ; filleuls = revenus passifs à long terme — combinez les deux." },
      { q: "Quels secteurs sont les plus réceptifs aux produits IBIG ?", a: "TPE/PME (SaaS gestion), établissements scolaires (Scolaby), transporteurs (Fleet 360), agences immobilières (IMMO TRUST)." },
      { q: "Comment gérer les objections des clients sceptiques ?", a: "« Trop cher » → comparez au coût d'un employé. « Pas besoin » → montrez un cas concret. Le Coach IA prépare des réponses." },
      { q: "Comment utiliser LinkedIn pour développer son réseau ?", a: "Profil avec rôle « Partenaire Commercial IBIG », publications régulières sur les problèmes résolus par les produits IBIG." },
      { q: "Comment suivre la performance de ses actions marketing ?", a: "Liens UTM différents par canal + Analytics pour les conversions — doublez les efforts sur ce qui fonctionne." },
      { q: "Quel est le profil des partenaires qui réussissent le mieux ?", a: "Ciblent un secteur précis, maintiennent un suivi hebdomadaire des prospects, maîtrisent 3-5 produits en profondeur." },
      { q: "Comment structurer son emploi du temps pour être productif ?", a: "Matin : prospection (1h). Midi : relances. Après-midi : démonstrations et déclarations de ventes. Soir : admin et réseau." },
      { q: "Vaut-il mieux se spécialiser dans une branche ou diversifier ?", a: "Spécialisation recommandée au début (maîtrise profonde) puis diversification progressive — une branche = une expertise." },
      { q: "Comment créer du contenu vidéo efficace pour promouvoir les produits IBIG ?", a: "Vidéos courtes (60-90s) montrant un problème résolu par le produit — témoignage client ou démonstration en direct." },
      { q: "Comment utiliser TikTok pour vendre des produits IBIG ?", a: "Contenus éducatifs courts sur les problèmes que résolvent les produits IBIG — évitez la publicité directe, préférez l'utilité." },
      { q: "Quelles sont les erreurs les plus courantes des nouveaux partenaires ?", a: "Activer trop de produits d'un coup, ne pas faire de suivi, chercher à vendre à tout le monde, négliger le KYC." },
      { q: "Comment fixer ses propres objectifs mensuels réalistes ?", a: "Basez-vous sur votre réseau actuel : 10 prospects = 2-3 ventes en moyenne — commencez petit et augmentez progressivement." },
      { q: "Comment préparer une présentation commerciale professionnelle ?", a: "Utilisez les slides IBIG officielles (Kit Marketing), personnalisez avec votre nom et adaptez aux besoins spécifiques du prospect." },
      { q: "Vaut-il mieux vendre à des particuliers ou à des entreprises ?", a: "Entreprises : tickets plus élevés mais cycles plus longs. Particuliers : décision rapide mais montants moindres — ciblez les deux." },
      { q: "Comment prospecter via email sans être considéré comme spam ?", a: "Personnalisez chaque email, référencez un point commun, proposez une valeur claire avant de vendre — maximum 3 relances." },
      { q: "Comment construire sa notoriété locale comme expert IBIG ?", a: "Intervenez dans les associations professionnelles, chambres de commerce, clubs d'entrepreneurs de votre ville." },
      { q: "Comment relancer efficacement un prospect qui ne répond plus ?", a: "Changez de canal (email → WhatsApp → appel), proposez une nouvelle valeur à chaque relance, espacez de 3-5 jours." },
      { q: "Combien de prospects dois-je contacter par jour ?", a: "5 à 10 nouveaux contacts/jour est un rythme efficace — qualité > quantité, ciblez des profils pertinents." },
      { q: "Comment construire un argumentaire en 2 minutes ?", a: "1. Problème du client (30s). 2. Solution IBIG (45s). 3. Preuve (témoignage/demo) (30s). 4. Appel à l'action (15s)." },
      { q: "Comment transformer un client en ambassadeur ?", a: "Assurez un excellent suivi post-vente, demandez un témoignage vidéo, proposez une petite récompense pour les recommandations." },
      { q: "Quelles plateformes sont les plus efficaces pour vendre les produits IBIG ?", a: "WhatsApp (closing), LinkedIn (B2B corporate), Facebook groupes professionnels, YouTube (démonstrations), email (prospection ciblée)." },
      { q: "Comment utiliser Instagram efficacement pour générer des leads ?", a: "Stories éducatives quotidiennes, Reels de démonstrations, lien dans bio vers votre /p/CODE — DM ciblés avec valeur." },
      { q: "Y a-t-il une méthode de vente recommandée par IBIG ?", a: "La méthode AIDA (Attention, Intérêt, Désir, Action) est recommandée — le Coach IA vous l'enseigne pas à pas." },
      { q: "Comment gérer son stress lors des périodes creuses ?", a: "Fixez-vous des micro-objectifs quotidiens (5 appels, 3 relances), célébrez chaque petite victoire et consultez votre parrain." },
      { q: "Comment maintenir sa motivation sur la durée ?", a: "Suivez vos streaks, participez aux challenges, rejoignez les groupes de partenaires actifs et relisez vos attestations fiscales." },
      { q: "Vaut-il mieux cibler des clients individuels ou des décideurs d'entreprise ?", a: "Décideurs en B2B pour les SaaS et formations corporate ; particuliers pour les services multiservices et formations courtes." },
      { q: "Comment préparer et conduire un appel de vente efficace ?", a: "Préparez 3 questions ouvertes, écoutez 70% du temps, reformulez le besoin avant de proposer la solution IBIG." },
      { q: "Comment quantifier le ROI pour un client ?", a: "Calculez le coût du problème sans solution vs coût du produit IBIG + gain de temps × valeur horaire du client." },
      { q: "Comment différencier IBIG des concurrents ?", a: "Catalogue multi-branches unique, commissions sur 3 niveaux, récurrentes pour les SaaS, support francophone — tout en un." },
      { q: "Comment vendre des abonnements SaaS à des clients réticents à la technologie ?", a: "Formation gratuite incluse, support IBIG dédié, démonstration simple de 15 min — réduisez la barrière technique perçue." },
      { q: "Comment s'organiser pour prospecter ET gérer ses clients existants ?", a: "CRM Mes Prospects + Mes Clients séparés, blocs de temps dédiés dans l'agenda, automatisez les relances par rappels." },
      { q: "Comment utiliser la preuve sociale pour convaincre les sceptiques ?", a: "Montrez votre attestation fiscale (revenus réels), des témoignages vidéo de partenaires, vos badges et statut IBIG." },
      { q: "Y a-t-il des erreurs de communication à éviter absolument ?", a: "Évitez les promesses de revenus garantis, les chiffres fantaisistes et la comparaison directe avec la concurrence IBIG." },
      { q: "Comment développer son réseau professionnel hors-ligne ?", a: "Événements entrepreneuriaux, salons professionnels, formations en présentiel — échangez votre carte avec votre /p/CODE." },
      { q: "Comment rédiger un message de prospection efficace sur WhatsApp ?", a: "Personnalisé (prénom), problème identifié, solution rapide, lien unique — maximum 3 phrases, finissez par une question." },
      { q: "Comment créer un tunnel de vente simple pour les produits IBIG ?", a: "Contenu éducatif gratuit → page /p/CODE → appel de découverte → démo → déclaration de vente — 5 étapes simples." },
      { q: "Comment analyser pourquoi une vente a échoué ?", a: "Identifiez l'étape de blocage (intérêt, budget, urgence, confiance), ajustez votre argumentaire et relancez différemment." },
      { q: "Comment bâtir sa réputation sur une niche spécifique ?", a: "Publiez régulièrement du contenu utile sur la niche, intervenez dans des groupes, et mentionnez votre expertise IBIG." },
      { q: "Quel est le meilleur moment de la journée pour contacter des prospects ?", a: "8h-9h30 et 17h-18h30 pour les professionnels ; samedi matin pour les particuliers — testez et analysez vos taux de réponse." },
      { q: "Comment construire un pipeline de vente organisé ?", a: "Mes Prospects : catégorisez par statut (Contacté, Intéressé, Devis, Négociation, Conclu) et relancez chaque étape." },
      { q: "Quels sont les 3 KPI les plus importants à suivre ?", a: "1. Taux de conversion (prospects → ventes). 2. Revenu moyen par vente. 3. Croissance du réseau actif mensuel." },
      { q: "Comment combien investir en temps par semaine pour réussir chez IBIG ?", a: "Minimum 5h/semaine pour débuter ; 15-20h/semaine pour viser 300 000+ FCFA/mois — régularité > volume ponctuel." },
      { q: "Comment utiliser le score hebdomadaire comme outil de planification ?", a: "Lisez votre score du lundi, identifiez les écarts vs la semaine précédente et planifiez vos actions correctives." },
      { q: "Comment créer une présence en ligne sans être influenceur ?", a: "Un profil LinkedIn soigné + page /p/CODE + 1-2 posts/semaine sur vos résultats suffisent pour démarrer efficacement." },
      { q: "Comment gérer les clients qui veulent négocier le prix des produits IBIG ?", a: "Les prix sont fixés par IBIG — orientez la négociation sur la valeur (ROI, gain de temps) plutôt que sur le prix." },
      { q: "Comment créer un système de parrainage interne à votre réseau ?", a: "Encouragez vos filleuls à recruter avec un coaching personnalisé — leurs filleuls deviennent vos N2 et génèrent des revenus passifs." },
      { q: "Comment éviter le burn-out tout en maintenant une activité élevée ?", a: "Planifiez des jours de repos, fixez des horaires de travail précis, déléguez à vos filleuls et célébrez chaque succès." },
    ],
  },
];

export default function FaqPage() {
  const total = FAQ.reduce((s, c) => s + c.items.length, 0);

  return (
    <div className="space-y-6 pb-10">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-black text-slate-900">FAQ Partenaire</h1>
          <p className="text-sm text-slate-500 mt-0.5">
            {total} questions essentielles pour maîtriser IBIG PARTNERS
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          {FAQ.map((c) => (
            <span key={c.title} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">
              {c.icon} {c.items.length}
            </span>
          ))}
        </div>
      </div>

      <FaqClient categories={FAQ} />
    </div>
  );
}
