import { NextResponse } from "next/server";
import { isSyncAuthorized } from "@/lib/sync-auth";
import { syncBranchCatalog } from "@/lib/catalog-sync";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const SOFT_PRODUCTS = [
  // ── SCOLABY (scolaby.com) — tarifs par cycle et taille d'établissement ──
  {
    slug: "scolaby-maternelle-primaire",
    name: "Scolaby — Maternelle/Primaire",
    pricingType: "MONTHLY_SUB",
    price: 10000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour écoles maternelles et primaires (≤300 élèves) : inscriptions en ligne, notes, bulletins automatiques, emploi du temps, SMS parents, paiement de la scolarité. 10 000 FCFA/mois. Tarif progressif selon l'effectif (300-1000 élèves : 15 000 FCFA/mois ; 1000+ : 20 000 FCFA/mois).",
  },
  {
    slug: "scolaby-maternelle-primaire-annuel",
    name: "Scolaby — Maternelle/Primaire (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 99600,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Abonnement annuel Scolaby pour maternelle/primaire (≤300 élèves), avec économie par rapport au mensuel. 99 600 FCFA/an.",
  },
  {
    slug: "scolaby-college-lycee",
    name: "Scolaby — Collège/Lycée",
    pricingType: "MONTHLY_SUB",
    price: 20000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour collèges et lycées (≤300 élèves), mêmes fonctionnalités que la formule Maternelle/Primaire adaptées au secondaire. 20 000 FCFA/mois. Tarif progressif selon l'effectif (300-1000 élèves : 35 000 FCFA/mois ; 1000+ : 50 000 FCFA/mois).",
  },
  {
    slug: "scolaby-college-lycee-annuel",
    name: "Scolaby — Collège/Lycée (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199200,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Abonnement annuel Scolaby pour collège/lycée (≤300 élèves). 199 200 FCFA/an.",
  },
  {
    slug: "scolaby-universite-bts",
    name: "Scolaby — Université/BTS",
    pricingType: "MONTHLY_SUB",
    price: 35000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour universités et BTS (≤300 étudiants), adapté à la gestion de l'enseignement supérieur. 35 000 FCFA/mois. Tarif progressif selon l'effectif (300-1000 étudiants : 60 000 FCFA/mois ; 1000+ : sur devis).",
  },
  {
    slug: "scolaby-universite-bts-annuel",
    name: "Scolaby — Université/BTS (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 348600,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Abonnement annuel Scolaby pour université/BTS (≤300 étudiants). 348 600 FCFA/an.",
  },
  {
    slug: "scolaby-multi-cycles",
    name: "Scolaby — Multi-cycles",
    pricingType: "MONTHLY_SUB",
    price: 25000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour établissements combinant plusieurs cycles (≤300 élèves tous cycles confondus). 25 000 FCFA/mois. Tarif progressif selon l'effectif (300-1000 élèves : 45 000 FCFA/mois ; 1000+ : sur devis).",
  },
  {
    slug: "scolaby-multi-cycles-annuel",
    name: "Scolaby — Multi-cycles (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 249000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Abonnement annuel Scolaby pour établissement multi-cycles (≤300 élèves). 249 000 FCFA/an.",
  },
  {
    slug: "scolaby-groupe-scolaire",
    name: "Scolaby — Groupe Scolaire",
    pricingType: "MONTHLY_SUB",
    price: 80000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour groupes scolaires gérant plusieurs établissements sous une même direction (≤1000 élèves au total), avec vue consolidée multi-sites. 80 000 FCFA/mois. Au-delà de 3000 élèves : sur devis.",
  },
  {
    slug: "scolaby-groupe-scolaire-grand",
    name: "Scolaby — Groupe Scolaire (1000-3000 élèves)",
    pricingType: "MONTHLY_SUB",
    price: 150000,
    rate: 20,
    siteUrl: "https://scolaby.com",
    description: "Scolaby pour groupes scolaires de grande taille (1000 à 3000 élèves au total), avec vue consolidée multi-sites. 150 000 FCFA/mois. Au-delà : sur devis.",
  },

  // ── IBIG FLEET 360 (ibigfleet360.com) — gestion de flotte, 4 formules ──
  {
    slug: "ibig-fleet-360-starter",
    name: "IBIG Fleet 360 — Starter",
    pricingType: "MONTHLY_SUB",
    price: 19900,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "IBIG Fleet 360 formule Starter (jusqu'à 10 véhicules) : suivi des véhicules et chauffeurs, maintenance, carburant, coûts d'exploitation. 19 900 FCFA/mois.",
  },
  {
    slug: "ibig-fleet-360-starter-annuel",
    name: "IBIG Fleet 360 — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199000,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "Abonnement annuel IBIG Fleet 360 Starter (10 véhicules), -10% par rapport au mensuel. 199 000 FCFA/an.",
  },
  {
    slug: "ibig-fleet-360-business",
    name: "IBIG Fleet 360 — Business",
    pricingType: "MONTHLY_SUB",
    price: 49900,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "IBIG Fleet 360 formule Business, pour flottes plus importantes que la formule Starter, avec fonctionnalités avancées de suivi et reporting. 49 900 FCFA/mois.",
  },
  {
    slug: "ibig-fleet-360-business-annuel",
    name: "IBIG Fleet 360 — Business (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 499000,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "Abonnement annuel IBIG Fleet 360 Business, -10% par rapport au mensuel. 499 000 FCFA/an.",
  },
  {
    slug: "ibig-fleet-360-professional",
    name: "IBIG Fleet 360 — Professional",
    pricingType: "MONTHLY_SUB",
    price: 99900,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "IBIG Fleet 360 formule Professional, pour flottes de taille importante avec besoins avancés de gestion et d'analyse. 99 900 FCFA/mois.",
  },
  {
    slug: "ibig-fleet-360-professional-annuel",
    name: "IBIG Fleet 360 — Professional (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 999000,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "Abonnement annuel IBIG Fleet 360 Professional, -10% par rapport au mensuel. 999 000 FCFA/an.",
  },
  {
    slug: "ibig-fleet-360-enterprise",
    name: "IBIG Fleet 360 — Enterprise",
    pricingType: "MONTHLY_SUB",
    price: 250000,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "IBIG Fleet 360 formule Enterprise, flotte illimitée, pour grandes entreprises de transport et logistique. À partir de 250 000 FCFA/mois — tarif sur devis au-delà.",
  },
  {
    slug: "ibig-fleet-360-enterprise-annuel",
    name: "IBIG Fleet 360 — Enterprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 2500000,
    rate: 20,
    siteUrl: "https://ibigfleet360.com",
    description: "Abonnement annuel IBIG Fleet 360 Enterprise, -10% par rapport au mensuel. À partir de 2 500 000 FCFA/an — tarif sur devis au-delà.",
  },

  // ── LOKATIVO (lokativo.com) — gestion immobilière, 3 formules ──
  {
    slug: "lokativo-starter",
    name: "Lokativo — Starter",
    pricingType: "MONTHLY_SUB",
    price: 9900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Lokativo formule Starter (jusqu'à 10 biens) : gestion des baux, loyers, charges, quittances automatiques. 9 900 FCFA/mois.",
  },
  {
    slug: "lokativo-starter-annuel",
    name: "Lokativo — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 99900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Abonnement annuel Lokativo Starter (10 biens), 2 mois offerts par rapport au mensuel. 99 900 FCFA/an.",
  },
  {
    slug: "lokativo-pro",
    name: "Lokativo — Pro",
    pricingType: "MONTHLY_SUB",
    price: 19900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Lokativo formule Pro, la plus populaire, pour agences avec un portefeuille de biens plus large que la formule Starter. 19 900 FCFA/mois.",
  },
  {
    slug: "lokativo-pro-annuel",
    name: "Lokativo — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Abonnement annuel Lokativo Pro, 2 mois offerts par rapport au mensuel. 199 900 FCFA/an.",
  },
  {
    slug: "lokativo-entreprise",
    name: "Lokativo — Entreprise",
    pricingType: "MONTHLY_SUB",
    price: 29900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Lokativo formule Entreprise, portefeuille de biens illimité, pour grandes agences et gestionnaires de patrimoine. 29 900 FCFA/mois.",
  },
  {
    slug: "lokativo-entreprise-annuel",
    name: "Lokativo — Entreprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 299900,
    rate: 20,
    siteUrl: "https://lokativo.com",
    description: "Abonnement annuel Lokativo Entreprise, 2 mois offerts par rapport au mensuel. 299 900 FCFA/an.",
  },

  // ── GESCOMXEL (ibigsoft.com/gescomxel.php) — gestion commerciale, 3 formules ──
  {
    slug: "gescomxel-starter",
    name: "GESCOMXEL — Starter",
    pricingType: "MONTHLY_SUB",
    price: 5000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "GESCOMXEL formule Starter (1 poste) : CRM, devis, factures, stocks et caisse. Idéal pour petite boutique ou pharmacie. 5 000 FCFA/mois.",
  },
  {
    slug: "gescomxel-starter-annuel",
    name: "GESCOMXEL — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 50000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "Abonnement annuel GESCOMXEL Starter (1 poste). 50 000 FCFA/an.",
  },
  {
    slug: "gescomxel-pro",
    name: "GESCOMXEL — Pro",
    pricingType: "MONTHLY_SUB",
    price: 10000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "GESCOMXEL formule Pro, la plus populaire (jusqu'à 5 postes simultanés), synchronisation temps réel. 10 000 FCFA/mois.",
  },
  {
    slug: "gescomxel-pro-annuel",
    name: "GESCOMXEL — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 90000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "Abonnement annuel GESCOMXEL Pro (5 postes). 90 000 FCFA/an.",
  },
  {
    slug: "gescomxel-business",
    name: "GESCOMXEL — Business",
    pricingType: "MONTHLY_SUB",
    price: 15000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "GESCOMXEL formule Business (jusqu'à 15 postes), gestion multi-boutique avec vue consolidée. 15 000 FCFA/mois.",
  },
  {
    slug: "gescomxel-business-annuel",
    name: "GESCOMXEL — Business (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 130000,
    rate: 20,
    siteUrl: "https://ibigsoft.com/gescomxel.php",
    description: "Abonnement annuel GESCOMXEL Business (15 postes, multi-boutique). 130 000 FCFA/an.",
  },

  // ── ZELIVRY (zelivry.com) — gestion de livraison, 4 formules ──
  {
    slug: "zelivry-starter",
    name: "Zelivry — Starter",
    pricingType: "MONTHLY_SUB",
    price: 4900,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Zelivry formule Starter (jusqu'à 2 livreurs, 150 livraisons/mois) : commandes, clients, catalogue, suivi public. 4 900 FCFA/mois.",
  },
  {
    slug: "zelivry-starter-annuel",
    name: "Zelivry — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 49000,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Abonnement annuel Zelivry Starter (2 livreurs), 2 mois offerts par rapport au mensuel. 49 000 FCFA/an.",
  },
  {
    slug: "zelivry-essentiel",
    name: "Zelivry — Essentiel",
    pricingType: "MONTHLY_SUB",
    price: 9900,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Zelivry formule Essentiel (jusqu'à 8 livreurs, 800 livraisons/mois), facturation, devis, caisse. 9 900 FCFA/mois.",
  },
  {
    slug: "zelivry-essentiel-annuel",
    name: "Zelivry — Essentiel (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 99000,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Abonnement annuel Zelivry Essentiel (8 livreurs), 2 mois offerts par rapport au mensuel. 99 000 FCFA/an.",
  },
  {
    slug: "zelivry-premium",
    name: "Zelivry — Premium",
    pricingType: "MONTHLY_SUB",
    price: 19900,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Zelivry formule Premium, la plus populaire (jusqu'à 25 livreurs, livraisons illimitées), comptabilité et rapports d'incidents. 19 900 FCFA/mois.",
  },
  {
    slug: "zelivry-premium-annuel",
    name: "Zelivry — Premium (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199000,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Abonnement annuel Zelivry Premium (25 livreurs, livraisons illimitées), 2 mois offerts par rapport au mensuel. 199 000 FCFA/an.",
  },
  {
    slug: "zelivry-expert-illimite",
    name: "Zelivry — Expert Illimité",
    pricingType: "MONTHLY_SUB",
    price: 39900,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Zelivry formule Expert Illimité, livreurs et utilisateurs illimités, multi-agences et international, marque blanche. 39 900 FCFA/mois.",
  },
  {
    slug: "zelivry-expert-illimite-annuel",
    name: "Zelivry — Expert Illimité (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 399000,
    rate: 20,
    siteUrl: "https://zelivry.com",
    description: "Abonnement annuel Zelivry Expert Illimité, 2 mois offerts par rapport au mensuel. 399 000 FCFA/an.",
  },

  // ── STOCKFLOW ERP (stockflow.ibigsoft.com) — 4 formules ──
  {
    slug: "stockflow-essentiel",
    name: "STOCKFLOW ERP — Essentiel",
    pricingType: "MONTHLY_SUB",
    price: 5000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "STOCKFLOW ERP formule Essentiel (2 utilisateurs, 300 produits) : gestion de stock, facturation. 5 000 FCFA/mois.",
  },
  {
    slug: "stockflow-essentiel-annuel",
    name: "STOCKFLOW ERP — Essentiel (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 50000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "Abonnement annuel STOCKFLOW ERP Essentiel. 50 000 FCFA/an.",
  },
  {
    slug: "stockflow-gestion-plus",
    name: "STOCKFLOW ERP — Gestion+",
    pricingType: "MONTHLY_SUB",
    price: 15000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "STOCKFLOW ERP formule Gestion+, comptabilité et tableaux de bord avancés en plus de la gestion de stock. 15 000 FCFA/mois.",
  },
  {
    slug: "stockflow-gestion-plus-annuel",
    name: "STOCKFLOW ERP — Gestion+ (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 150000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "Abonnement annuel STOCKFLOW ERP Gestion+. 150 000 FCFA/an.",
  },
  {
    slug: "stockflow-logistique",
    name: "STOCKFLOW ERP — Logistique",
    pricingType: "MONTHLY_SUB",
    price: 20000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "STOCKFLOW ERP formule Logistique, gestion multi-dépôts pour distributeurs avec plusieurs entrepôts. 20 000 FCFA/mois.",
  },
  {
    slug: "stockflow-logistique-annuel",
    name: "STOCKFLOW ERP — Logistique (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 200000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "Abonnement annuel STOCKFLOW ERP Logistique. 200 000 FCFA/an.",
  },
  {
    slug: "stockflow-entreprise-scm",
    name: "STOCKFLOW ERP — Entreprise SCM",
    pricingType: "MONTHLY_SUB",
    price: 30000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "STOCKFLOW ERP formule Entreprise SCM, capacité illimitée, 10 entrepôts, support dédié — pour grands distributeurs. 30 000 FCFA/mois.",
  },
  {
    slug: "stockflow-entreprise-scm-annuel",
    name: "STOCKFLOW ERP — Entreprise SCM (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 300000,
    rate: 20,
    siteUrl: "https://stockflow.ibigsoft.com",
    description: "Abonnement annuel STOCKFLOW ERP Entreprise SCM. 300 000 FCFA/an.",
  },

  // ── CONSTRUIRO ERP (construiro.com) — ERP BTP & Construction, 4 formules ──
  {
    slug: "construiro-solo",
    name: "CONSTRUIRO ERP — Solo",
    pricingType: "MONTHLY_SUB",
    price: 15000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "CONSTRUIRO ERP formule Solo (3 utilisateurs, 5 projets) : ERP BTP pour artisans et auto-entrepreneurs du bâtiment — gestion de projets, chantiers, devis, stock et 15+ modules métier. 15 000 FCFA/mois. Essai gratuit 14 jours.",
  },
  {
    slug: "construiro-solo-annuel",
    name: "CONSTRUIRO ERP — Solo (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 150000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "Abonnement annuel CONSTRUIRO ERP Solo (3 utilisateurs, 5 projets), 2 mois offerts par rapport au mensuel. 150 000 FCFA/an.",
  },
  {
    slug: "construiro-starter",
    name: "CONSTRUIRO ERP — Starter",
    pricingType: "MONTHLY_SUB",
    price: 39000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "CONSTRUIRO ERP formule Starter (10 utilisateurs, 20 projets), pour les PME BTP démarrant leur digitalisation. 39 000 FCFA/mois.",
  },
  {
    slug: "construiro-starter-annuel",
    name: "CONSTRUIRO ERP — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 390000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "Abonnement annuel CONSTRUIRO ERP Starter (10 utilisateurs, 20 projets), 2 mois offerts. 390 000 FCFA/an.",
  },
  {
    slug: "construiro-pro",
    name: "CONSTRUIRO ERP — Pro",
    pricingType: "MONTHLY_SUB",
    price: 89000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "CONSTRUIRO ERP formule Pro, la plus populaire (20 utilisateurs, 50 projets), pour entreprises BTP en croissance avec plusieurs chantiers simultanés. 89 000 FCFA/mois.",
  },
  {
    slug: "construiro-pro-annuel",
    name: "CONSTRUIRO ERP — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 890000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "Abonnement annuel CONSTRUIRO ERP Pro (20 utilisateurs, 50 projets), 2 mois offerts. 890 000 FCFA/an.",
  },
  {
    slug: "construiro-entreprise",
    name: "CONSTRUIRO ERP — Entreprise",
    pricingType: "MONTHLY_SUB",
    price: 189000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "CONSTRUIRO ERP formule Entreprise, utilisateurs et projets illimités, pour les groupes BTP avec accompagnement dédié. 189 000 FCFA/mois.",
  },
  {
    slug: "construiro-entreprise-annuel",
    name: "CONSTRUIRO ERP — Entreprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 1890000,
    rate: 20,
    siteUrl: "https://construiro.com",
    description: "Abonnement annuel CONSTRUIRO ERP Entreprise (illimité), 2 mois offerts. 1 890 000 FCFA/an.",
  },

  // ── SANTAREX ERP (santarex.ibigsoft.com) — gestion hospitalière, 5 formules ──
  {
    slug: "santarex-pharmacie",
    name: "SANTAREX ERP — Pharmacie autonome",
    pricingType: "MONTHLY_SUB",
    price: 12000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "SANTAREX ERP formule Pharmacie autonome (1 à 3 utilisateurs) : gestion des stocks, dispensation, alertes péremption/rupture, facturation Mobile Money. 12 000 FCFA/mois. Essai gratuit 30 jours.",
  },
  {
    slug: "santarex-pharmacie-annuel",
    name: "SANTAREX ERP — Pharmacie autonome (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 120000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "Abonnement annuel SANTAREX ERP Pharmacie autonome, 2 mois offerts. 120 000 FCFA/an.",
  },
  {
    slug: "santarex-cabinet",
    name: "SANTAREX ERP — Cabinet médical",
    pricingType: "MONTHLY_SUB",
    price: 18000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "SANTAREX ERP formule Cabinet médical (1 à 5 utilisateurs) : DME illimité, consultations CIM-10, rendez-vous, ordonnances numériques, facturation. 18 000 FCFA/mois.",
  },
  {
    slug: "santarex-cabinet-annuel",
    name: "SANTAREX ERP — Cabinet médical (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 180000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "Abonnement annuel SANTAREX ERP Cabinet médical, 2 mois offerts. 180 000 FCFA/an.",
  },
  {
    slug: "santarex-centre-sante",
    name: "SANTAREX ERP — Centre de santé",
    pricingType: "MONTHLY_SUB",
    price: 35000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "SANTAREX ERP formule Centre de santé (jusqu'à 15 utilisateurs) : pharmacie, laboratoire basique, consultations, facturation et reporting. 35 000 FCFA/mois.",
  },
  {
    slug: "santarex-centre-sante-annuel",
    name: "SANTAREX ERP — Centre de santé (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 350000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "Abonnement annuel SANTAREX ERP Centre de santé, 2 mois offerts. 350 000 FCFA/an.",
  },
  {
    slug: "santarex-clinique",
    name: "SANTAREX ERP — Clinique & polyclinique",
    pricingType: "MONTHLY_SUB",
    price: 75000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "SANTAREX ERP formule Clinique & polyclinique, la plus populaire (jusqu'à 30 utilisateurs) : pharmacie, laboratoire, hospitalisation, bloc opératoire, dashboard BI, support 7j/7. 75 000 FCFA/mois.",
  },
  {
    slug: "santarex-clinique-annuel",
    name: "SANTAREX ERP — Clinique & polyclinique (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 750000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "Abonnement annuel SANTAREX ERP Clinique & polyclinique, 2 mois offerts. 750 000 FCFA/an.",
  },
  {
    slug: "santarex-hopital",
    name: "SANTAREX ERP — Hôpital & groupe",
    pricingType: "MONTHLY_SUB",
    price: 150000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "SANTAREX ERP formule Hôpital & groupe, utilisateurs illimités : les 40 modules inclus, urgences, imagerie (PACS), RH/paie, multi-sites, SLA 99,9%. 150 000 FCFA/mois.",
  },
  {
    slug: "santarex-hopital-annuel",
    name: "SANTAREX ERP — Hôpital & groupe (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 1500000,
    rate: 20,
    siteUrl: "https://santarex.ibigsoft.com",
    description: "Abonnement annuel SANTAREX ERP Hôpital & groupe (illimité, multi-sites), 2 mois offerts. 1 500 000 FCFA/an.",
  },

  // ── AGRIFRIK (agrifrik.ibigsoft.com) — ERP agricole, 4 formules ──
  {
    slug: "agrifrik-basique",
    name: "AGRIFRIK — Basique",
    pricingType: "MONTHLY_SUB",
    price: 6500,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "AGRIFRIK formule Basique (1 à 3 utilisateurs, 5 Go) : modules cultures & planning, dashboard, application mobile, support email. ERP agricole pour l'Afrique subsaharienne. 6 500 FCFA/mois. 1 mois d'essai gratuit.",
  },
  {
    slug: "agrifrik-basique-annuel",
    name: "AGRIFRIK — Basique (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 65000,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "Abonnement annuel AGRIFRIK Basique, 2 mois offerts. 65 000 FCFA/an.",
  },
  {
    slug: "agrifrik-standard",
    name: "AGRIFRIK — Standard",
    pricingType: "MONTHLY_SUB",
    price: 14900,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "AGRIFRIK formule Standard (jusqu'à 10 utilisateurs, 20 Go) : Production + Finance + RH, comptabilité SYSCOHADA, météo 7 jours, portail coopérateur, support téléphonique. 14 900 FCFA/mois.",
  },
  {
    slug: "agrifrik-standard-annuel",
    name: "AGRIFRIK — Standard (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 149000,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "Abonnement annuel AGRIFRIK Standard, 2 mois offerts. 149 000 FCFA/an.",
  },
  {
    slug: "agrifrik-pro",
    name: "AGRIFRIK — Pro",
    pricingType: "MONTHLY_SUB",
    price: 29900,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "AGRIFRIK formule Pro, la plus populaire (jusqu'à 30 utilisateurs, 100 Go) : tous modules, IA agronomique ARIA, météo 15j, exportation, traçabilité, API REST, support prioritaire. 29 900 FCFA/mois.",
  },
  {
    slug: "agrifrik-pro-annuel",
    name: "AGRIFRIK — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 299000,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "Abonnement annuel AGRIFRIK Pro, 2 mois offerts. 299 000 FCFA/an.",
  },
  {
    slug: "agrifrik-entreprise",
    name: "AGRIFRIK — Entreprise",
    pricingType: "MONTHLY_SUB",
    price: 49900,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "AGRIFRIK formule Entreprise, utilisateurs et stockage illimités : personnalisation complète, traçabilité blockchain, cloud dédié/on-premise, account manager, SLA 99,9%. À partir de 49 900 FCFA/mois — tarif sur devis selon périmètre.",
  },
  {
    slug: "agrifrik-entreprise-annuel",
    name: "AGRIFRIK — Entreprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 499000,
    rate: 20,
    siteUrl: "https://agrifrik.ibigsoft.com",
    description: "Abonnement annuel AGRIFRIK Entreprise. À partir de 499 000 FCFA/an — tarif sur devis selon périmètre.",
  },

  // ── GESTMONEY (gestmoney.ibigsoft.com) — gestion réseaux Mobile Money, 4 formules ──
  {
    slug: "gestmoney-starter",
    name: "GESTMONEY — Starter",
    pricingType: "MONTHLY_SUB",
    price: 9900,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "GESTMONEY formule Starter (5 utilisateurs, 1 agence) : gestion des réseaux Mobile Money (Orange Money, MTN MoMo, Wave, Moov), agents de terrain, flottes, sauvegarde cloud. 9 900 FCFA/mois.",
  },
  {
    slug: "gestmoney-starter-annuel",
    name: "GESTMONEY — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 99000,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "Abonnement annuel GESTMONEY Starter, 2 mois offerts. 99 000 FCFA/an.",
  },
  {
    slug: "gestmoney-essentiel",
    name: "GESTMONEY — Essentiel",
    pricingType: "MONTHLY_SUB",
    price: 19900,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "GESTMONEY formule Essentiel (15 utilisateurs, 3 agences) : commissions automatiques, reporting BI, comptabilité OHADA de base, imports Excel, support prioritaire. 19 900 FCFA/mois.",
  },
  {
    slug: "gestmoney-essentiel-annuel",
    name: "GESTMONEY — Essentiel (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199000,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "Abonnement annuel GESTMONEY Essentiel, 2 mois offerts. 199 000 FCFA/an.",
  },
  {
    slug: "gestmoney-professional",
    name: "GESTMONEY — Professional",
    pricingType: "MONTHLY_SUB",
    price: 39900,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "GESTMONEY formule Professional, recommandée (utilisateurs illimités, 10 agences) : tous les modules métier, comptabilité OHADA complète, assistant IA SARA, API & intégrations, KYC clients. 39 900 FCFA/mois. Formule Enterprise multi-pays disponible sur devis.",
  },
  {
    slug: "gestmoney-professional-annuel",
    name: "GESTMONEY — Professional (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 399000,
    rate: 20,
    siteUrl: "https://gestmoney.ibigsoft.com",
    description: "Abonnement annuel GESTMONEY Professional, 2 mois offerts. 399 000 FCFA/an.",
  },

  // ── ANOUANZÊ ERP (anouanze.ibigsoft.com) — associations, ONG & OBNL, 4 formules ──
  {
    slug: "anouanze-essentiel",
    name: "ANOUANZÊ ERP — Essentiel",
    pricingType: "MONTHLY_SUB",
    price: 12900,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "ANOUANZÊ ERP formule Essentiel (3 utilisateurs) : membres & cotisations, trésorerie de base, comptabilité simplifiée, documents (1 Go). ERP dédié aux associations, ONG et OBNL. 12 900 FCFA/mois.",
  },
  {
    slug: "anouanze-essentiel-annuel",
    name: "ANOUANZÊ ERP — Essentiel (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 129000,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "Abonnement annuel ANOUANZÊ ERP Essentiel, 2 mois offerts. 129 000 FCFA/an.",
  },
  {
    slug: "anouanze-starter",
    name: "ANOUANZÊ ERP — Starter",
    pricingType: "MONTHLY_SUB",
    price: 29900,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "ANOUANZÊ ERP formule Starter (8 utilisateurs) : comptabilité SYCEBNL complète, budget & trésorerie, 3 projets actifs, documents (5 Go), événements. 29 900 FCFA/mois.",
  },
  {
    slug: "anouanze-starter-annuel",
    name: "ANOUANZÊ ERP — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 299000,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "Abonnement annuel ANOUANZÊ ERP Starter, 2 mois offerts. 299 000 FCFA/an.",
  },
  {
    slug: "anouanze-pro",
    name: "ANOUANZÊ ERP — Pro",
    pricingType: "MONTHLY_SUB",
    price: 59900,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "ANOUANZÊ ERP formule Pro, la plus populaire (15 utilisateurs) : tous les modules inclus, projets MEAL illimités, RH/Paie, Assistant IA, documents (20 Go). 59 900 FCFA/mois. Formule Enterprise multi-organisations disponible sur devis.",
  },
  {
    slug: "anouanze-pro-annuel",
    name: "ANOUANZÊ ERP — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 599000,
    rate: 20,
    siteUrl: "https://anouanze.ibigsoft.com",
    description: "Abonnement annuel ANOUANZÊ ERP Pro, 2 mois offerts. 599 000 FCFA/an.",
  },

  // ── FACTPRO (factpro.ibigsoft.com) — logiciel de facturation, 4 formules ──
  {
    slug: "factpro-starter",
    name: "IBIG FactPro — Starter",
    pricingType: "MONTHLY_SUB",
    price: 4900,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "IBIG FactPro formule Starter (1 utilisateur, 1 société, 50 docs/mois) : devis & factures essentiels, QR anti-falsification, export PDF professionnel. Facturation conforme OHADA, Mobile Money. 4 900 FCFA/mois. Essai gratuit 7 jours.",
  },
  {
    slug: "factpro-starter-annuel",
    name: "IBIG FactPro — Starter (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 47000,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "Abonnement annuel IBIG FactPro Starter, -20% par rapport au mensuel. 47 000 FCFA/an.",
  },
  {
    slug: "factpro-pro",
    name: "IBIG FactPro — Pro",
    pricingType: "MONTHLY_SUB",
    price: 12900,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "IBIG FactPro formule Pro, la plus populaire (5 utilisateurs, 1 société, 500 docs/mois) : documents illimités, devis/factures/BL/avoirs/acomptes, factures récurrentes automatiques. 12 900 FCFA/mois.",
  },
  {
    slug: "factpro-pro-annuel",
    name: "IBIG FactPro — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 123800,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "Abonnement annuel IBIG FactPro Pro, -20% par rapport au mensuel. 123 800 FCFA/an.",
  },
  {
    slug: "factpro-business",
    name: "IBIG FactPro — Business",
    pricingType: "MONTHLY_SUB",
    price: 24900,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "IBIG FactPro formule Business (utilisateurs illimités, 3 sociétés) : tout le plan Pro, caisse POS tactile multi-tables, impression thermique 58/80mm. Idéal commerce physique. 24 900 FCFA/mois.",
  },
  {
    slug: "factpro-business-annuel",
    name: "IBIG FactPro — Business (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 239000,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "Abonnement annuel IBIG FactPro Business, -20% par rapport au mensuel. 239 000 FCFA/an.",
  },
  {
    slug: "factpro-enterprise",
    name: "IBIG FactPro — Enterprise",
    pricingType: "MONTHLY_SUB",
    price: 59900,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "IBIG FactPro formule Enterprise (documents, utilisateurs et sociétés illimités) : tout le plan Business + White-Label revendeur à votre marque. 59 900 FCFA/mois.",
  },
  {
    slug: "factpro-enterprise-annuel",
    name: "IBIG FactPro — Enterprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 575000,
    rate: 20,
    siteUrl: "https://factpro.ibigsoft.com",
    description: "Abonnement annuel IBIG FactPro Enterprise, -20% par rapport au mensuel. 575 000 FCFA/an.",
  },

  // ── SECRETIS ERP (secretis.ibigsoft.com) — courrier & secrétariat, 4 formules ──
  {
    slug: "secretis-decouverte",
    name: "SECRETIS ERP — Découverte",
    pricingType: "MONTHLY_SUB",
    price: 4900,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "SECRETIS ERP formule Découverte (jusqu'à 3 utilisateurs, 1 Go) : courrier entrant et sortant, agenda & contacts, support email. Gestion du courrier et du secrétariat pour très petites structures. 4 900 FCFA/mois. Essai gratuit 14 jours.",
  },
  {
    slug: "secretis-decouverte-annuel",
    name: "SECRETIS ERP — Découverte (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 49000,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "Abonnement annuel SECRETIS ERP Découverte, 2 mois offerts. 49 000 FCFA/an.",
  },
  {
    slug: "secretis-essentiel",
    name: "SECRETIS ERP — Essentiel",
    pricingType: "MONTHLY_SUB",
    price: 9900,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "SECRETIS ERP formule Essentiel (jusqu'à 10 utilisateurs, 3 Go) : tout Découverte + GED complète, visiteurs & réunions, Assistante IA SARA. 9 900 FCFA/mois.",
  },
  {
    slug: "secretis-essentiel-annuel",
    name: "SECRETIS ERP — Essentiel (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 99000,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "Abonnement annuel SECRETIS ERP Essentiel, 2 mois offerts. 99 000 FCFA/an.",
  },
  {
    slug: "secretis-pro",
    name: "SECRETIS ERP — Pro",
    pricingType: "MONTHLY_SUB",
    price: 19900,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "SECRETIS ERP formule Pro, recommandée (jusqu'à 25 utilisateurs, 10 Go) : tout Essentiel + tâches & workflows, notes de frais & RH, rapports avancés, support prioritaire. 19 900 FCFA/mois.",
  },
  {
    slug: "secretis-pro-annuel",
    name: "SECRETIS ERP — Pro (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 199000,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "Abonnement annuel SECRETIS ERP Pro, 2 mois offerts. 199 000 FCFA/an.",
  },
  {
    slug: "secretis-entreprise",
    name: "SECRETIS ERP — Entreprise",
    pricingType: "MONTHLY_SUB",
    price: 39900,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "SECRETIS ERP formule Entreprise, utilisateurs illimités (30 Go) : tout Pro + multi-sites & agences, SSO/LDAP & API, accompagnement dédié. 39 900 FCFA/mois.",
  },
  {
    slug: "secretis-entreprise-annuel",
    name: "SECRETIS ERP — Entreprise (Annuel)",
    pricingType: "ANNUAL_SUB",
    price: 399000,
    rate: 20,
    siteUrl: "https://secretis.ibigsoft.com",
    description: "Abonnement annuel SECRETIS ERP Entreprise (illimité, multi-sites), 2 mois offerts. 399 000 FCFA/an.",
  },

  // ── DOCPRO (docpro.ibigsoft.com) — génération de documents à l'usage ──
  {
    slug: "docpro-generation",
    name: "IBIG DocPro — Génération de documents",
    pricingType: "SERVICE",
    price: 100,
    rate: 20,
    siteUrl: "https://docpro.ibigsoft.com",
    description: "IBIG DocPro : génération intelligente de documents professionnels conformes OHADA (CV, contrats, statuts, business plans…) — 1 200+ modèles, 15 pays africains. Paiement à l'usage dès 100 FCFA/document (niveaux Standard, Pro, Expert) ou via portefeuille de crédits avec jusqu'à +30% offerts. Sans abonnement obligatoire.",
  },
];

export async function POST() {
  try {
    if (!(await isSyncAuthorized())) {
      return NextResponse.json({ error: "Non autorisé" }, { status: 403 });
    }

    const result = await syncBranchCatalog("ibig-soft", "IBIG SOFT", SOFT_PRODUCTS, { notify: true });
    if (!result.ok) {
      return NextResponse.json({ error: result.error }, { status: result.status });
    }

    const { diff, notified } = result;
    return NextResponse.json({
      ok: true,
      upserted: diff.total,
      added: diff.added.length,
      updated: diff.updated.length,
      deleted: diff.removed,
      notified,
      message: `${diff.total} logiciels IBIG SOFT synchronisés (${diff.added.length} nouveau(x), ${diff.updated.length} mis à jour, ${diff.removed} retiré(s)).`,
    });
  } catch (err: any) {
    console.error("sync-soft error:", err);
    return NextResponse.json({ error: err?.message ?? "Erreur serveur" }, { status: 500 });
  }
}
