export type Country = { code: string; name: string; dial: string; flag: string };

/**
 * Pays + indicatifs téléphoniques. Priorité à l'Afrique (cible principale) et
 * aux principaux pays de la diaspora. Triés : Côte d'Ivoire en tête, puis
 * Afrique, puis diaspora.
 */
export const COUNTRIES: Country[] = [
  { code: "CI", name: "Côte d'Ivoire", dial: "+225", flag: "🇨🇮" },
  { code: "SN", name: "Sénégal", dial: "+221", flag: "🇸🇳" },
  { code: "ML", name: "Mali", dial: "+223", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", dial: "+226", flag: "🇧🇫" },
  { code: "BJ", name: "Bénin", dial: "+229", flag: "🇧🇯" },
  { code: "TG", name: "Togo", dial: "+228", flag: "🇹🇬" },
  { code: "NE", name: "Niger", dial: "+227", flag: "🇳🇪" },
  { code: "GN", name: "Guinée", dial: "+224", flag: "🇬🇳" },
  { code: "GW", name: "Guinée-Bissau", dial: "+245", flag: "🇬🇼" },
  { code: "GH", name: "Ghana", dial: "+233", flag: "🇬🇭" },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { code: "CM", name: "Cameroun", dial: "+237", flag: "🇨🇲" },
  { code: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦" },
  { code: "CG", name: "Congo", dial: "+242", flag: "🇨🇬" },
  { code: "CD", name: "RD Congo", dial: "+243", flag: "🇨🇩" },
  { code: "TD", name: "Tchad", dial: "+235", flag: "🇹🇩" },
  { code: "CF", name: "Centrafrique", dial: "+236", flag: "🇨🇫" },
  { code: "GQ", name: "Guinée équatoriale", dial: "+240", flag: "🇬🇶" },
  { code: "MR", name: "Mauritanie", dial: "+222", flag: "🇲🇷" },
  { code: "MA", name: "Maroc", dial: "+212", flag: "🇲🇦" },
  { code: "DZ", name: "Algérie", dial: "+213", flag: "🇩🇿" },
  { code: "TN", name: "Tunisie", dial: "+216", flag: "🇹🇳" },
  { code: "SL", name: "Sierra Leone", dial: "+232", flag: "🇸🇱" },
  { code: "LR", name: "Liberia", dial: "+231", flag: "🇱🇷" },
  { code: "GM", name: "Gambie", dial: "+220", flag: "🇬🇲" },
  { code: "CV", name: "Cap-Vert", dial: "+238", flag: "🇨🇻" },
  { code: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪" },
  { code: "CI2", name: "Rwanda", dial: "+250", flag: "🇷🇼" },
  { code: "TZ", name: "Tanzanie", dial: "+255", flag: "🇹🇿" },
  { code: "UG", name: "Ouganda", dial: "+256", flag: "🇺🇬" },
  { code: "ET", name: "Éthiopie", dial: "+251", flag: "🇪🇹" },
  { code: "ZA", name: "Afrique du Sud", dial: "+27", flag: "🇿🇦" },
  { code: "AO", name: "Angola", dial: "+244", flag: "🇦🇴" },
  { code: "MG", name: "Madagascar", dial: "+261", flag: "🇲🇬" },
  { code: "MU", name: "Maurice", dial: "+230", flag: "🇲🇺" },
  // Diaspora
  { code: "FR", name: "France", dial: "+33", flag: "🇫🇷" },
  { code: "BE", name: "Belgique", dial: "+32", flag: "🇧🇪" },
  { code: "CH", name: "Suisse", dial: "+41", flag: "🇨🇭" },
  { code: "CA", name: "Canada", dial: "+1", flag: "🇨🇦" },
  { code: "US", name: "États-Unis", dial: "+1", flag: "🇺🇸" },
  { code: "GB", name: "Royaume-Uni", dial: "+44", flag: "🇬🇧" },
  { code: "DE", name: "Allemagne", dial: "+49", flag: "🇩🇪" },
  { code: "IT", name: "Italie", dial: "+39", flag: "🇮🇹" },
  { code: "ES", name: "Espagne", dial: "+34", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", dial: "+351", flag: "🇵🇹" },
  { code: "NL", name: "Pays-Bas", dial: "+31", flag: "🇳🇱" },
  { code: "AE", name: "Émirats arabes unis", dial: "+971", flag: "🇦🇪" },
  { code: "SA", name: "Arabie saoudite", dial: "+966", flag: "🇸🇦" },
  { code: "CN", name: "Chine", dial: "+86", flag: "🇨🇳" },
  { code: "TR", name: "Turquie", dial: "+90", flag: "🇹🇷" },
];
