import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { isSyncAuthorized } from "@/lib/sync-auth";

// 291 formations scrapées depuis ibig-eduform.com — upsert sans deleteMany
const RECOVER_PRODUCTS = [
  { slug: "eduform-accueil-vip-service-excellence", name: "Accueil VIP & Excellence du Service Client", price: 115000, hours: 20 },
  { slug: "eduform-administration-personnel-dossiers-rh", name: "Administration du Personnel & Gestion des Dossiers RH", price: 140000, hours: 25 },
  { slug: "eduform-agent-immobilier-professionnel", name: "Agent Immobilier Professionnel", price: 200000, hours: 35 },
  { slug: "eduform-agribusiness-gestion-exploitation", name: "Agribusiness & Gestion d'Exploitation Agricole", price: 310000, hours: 55 },
  { slug: "eduform-analyse-performance-commerciale", name: "Analyse de Performance Commerciale & Tableaux de Bord", price: 140000, hours: 25 },
  { slug: "eduform-anglais-debutant", name: "Anglais — Les Fondamentaux pour Débutants", price: 225000, hours: 40 },
  { slug: "eduform-anglais-affaires", name: "Anglais des Affaires", price: 140000, hours: 25 },
  { slug: "eduform-anglais-avance", name: "Anglais Niveau Avancé", price: 170000, hours: 30 },
  { slug: "eduform-anglais-intermediaire", name: "Anglais Niveau Intermédiaire", price: 170000, hours: 30 },
  { slug: "eduform-anglais-professionnel", name: "Anglais Professionnel — Business English", price: 160000, hours: 28 },
  { slug: "eduform-assistant-administratif-bureautique", name: "Assistant Administratif & Bureautique", price: 200000, hours: 25 },
  { slug: "eduform-assistant-comptable-et-syscohada", name: "Assistant Comptable & SYSCOHADA", price: 120000, hours: 25 },
  { slug: "eduform-assistant-direction-bilingue", name: "Assistant de Direction Bilingue — Français/Anglais", price: 200000, hours: 35 },
  { slug: "eduform-assistant-gestion-projets", name: "Assistant en Gestion de Projets", price: 200000, hours: 25 },
  { slug: "eduform-assistant-gestion-appels-offres", name: "Assistant en Gestion des Appels d'Offres", price: 200000, hours: 30 },
  { slug: "eduform-assistant-juridique-contentieux", name: "Assistant Juridique & Contentieux", price: 200000, hours: 35 },
  { slug: "eduform-assistant-polyvalent-pme-ong", name: "Assistant Polyvalent PME/ONG", price: 200000, hours: 25 },
  { slug: "eduform-assistant-rh-outils-pratiques", name: "Assistant RH — Missions & Outils Pratiques", price: 140000, hours: 25 },
  { slug: "eduform-assistant-rh-administration-personnel", name: "Assistant RH & Administration du Personnel", price: 200000, hours: 30 },
  { slug: "eduform-assurances-sinistres-indemnisations", name: "Assurances, Sinistres & Indemnisations", price: 170000, hours: 30 },
  { slug: "eduform-audit-commissariat-comptes", name: "Audit & Commissariat aux Comptes", price: 225000, hours: 40 },
  { slug: "eduform-audit-controle-4en1", name: "Audit & Contrôle de Gestion 4 en 1", price: 365000, hours: 65 },
  { slug: "eduform-audit-controle-interne-pme", name: "Audit & Contrôle Interne dans les PME", price: 200000, hours: 35 },
  { slug: "eduform-automatisation-rh-ged", name: "Automatisation RH & Gestion Électronique des Documents (GED)", price: 170000, hours: 30 },
  { slug: "eduform-banque-digitale-fintech", name: "Banque Digitale & Fintech — Certificat Pratique", price: 170000, hours: 30 },
  { slug: "eduform-banque-credit-microfinance-3en1", name: "Banque, Crédit & Microfinance 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-blockchain-affaires", name: "Blockchain et Applications dans les Affaires", price: 170000, hours: 30 },
  { slug: "eduform-branding-positionnement-image-marque", name: "Branding, Positionnement & Image de Marque", price: 170000, hours: 30 },
  { slug: "eduform-btp-presentiel", name: "BTP & Gestion de Chantier — Présentiel", price: 85000, hours: 25 },
  { slug: "eduform-btp-gestion-chantier-3en1", name: "BTP & Gestion de Chantier 3 en 1", price: 85000, hours: 55 },
  { slug: "eduform-bureautique-microsoft-4en1", name: "Bureautique Microsoft 4 en 1", price: 85000, hours: 55 },
  { slug: "eduform-business-model-canvas-mvp", name: "Business Model Canvas & MVP", price: 140000, hours: 25 },
  { slug: "eduform-canva-pro-et-design-marketing", name: "Canva Pro & Design Marketing", price: 25000, hours: 25 },
  { slug: "eduform-canva-pro", name: "Canva Pro & Design Marketing", price: 25000, hours: 7 },
  { slug: "eduform-iso-27001-securite-information", name: "Certification ISO 27001 — Sécurité des Systèmes d'Information", price: 225000, hours: 40 },
  { slug: "eduform-iso-30414-indicateurs-rh", name: "Certification ISO 30414 — Reporting sur le Capital Humain", price: 200000, hours: 35 },
  { slug: "eduform-iso-9001-management-qualite", name: "Certification ISO 9001 — Système de Management de la Qualité", price: 200000, hours: 35 },
  { slug: "eduform-charge-accueil-relations-publiques", name: "Chargé d'Accueil & Relations Publiques", price: 200000, hours: 20 },
  { slug: "eduform-charge-clientele-bancaire", name: "Chargé de Clientèle Bancaire", price: 200000, hours: 35 },
  { slug: "eduform-gestionnaire-documentaire-archivage", name: "Chargé de Gestion Documentaire & Archivage", price: 200000, hours: 25 },
  { slug: "eduform-charge-suivi-reporting-administratif", name: "Chargé de Suivi & Reporting Administratif", price: 200000, hours: 25 },
  { slug: "eduform-charge-suivi-budgetaire-administratif", name: "Chargé de Suivi Budgétaire & Administratif", price: 200000, hours: 30 },
  { slug: "eduform-chef-comptable-et-supervision-financiere", name: "Chef Comptable & Supervision Financière", price: 135000, hours: 25 },
  { slug: "eduform-cloud-computing-aws-azure", name: "Cloud Computing — AWS & Azure Practitioner", price: 225000, hours: 40 },
  { slug: "eduform-coaching-gestion-talents", name: "Coaching & Gestion des Talents", price: 170000, hours: 30 },
  { slug: "eduform-coaching-particulier", name: "Coaching Individuel & Formation Particulier", price: 85000, hours: 25 },
  { slug: "eduform-commerce-international-douane-3en1", name: "Commerce International & Douane 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-communication-digitale-slack-chatgpt", name: "Communication & Collaboration Digitale — Slack, ChatGPT & IA", price: 40000, hours: 14 },
  { slug: "eduform-communication-ong-projets-humanitaires", name: "Communication dans les ONG & Projets Humanitaires", price: 140000, hours: 25 },
  { slug: "eduform-communication-ecrite-professionnelle", name: "Communication Écrite Professionnelle", price: 115000, hours: 20 },
  { slug: "eduform-communication-evenementielle-conferences", name: "Communication Événementielle & Organisation de Conférences", price: 170000, hours: 30 },
  { slug: "eduform-communication-interne-climat-social", name: "Communication Interne & Climat Social", price: 140000, hours: 25 },
  { slug: "eduform-communication-interne-art-oratoire", name: "Communication Interne, Engagement des Employés & Art Oratoire", price: 200000, hours: 35 },
  { slug: "eduform-communication-prise-parole", name: "Communication Professionnelle & Prise de Parole", price: 160000, hours: 28 },
  { slug: "eduform-community-manager-social-media", name: "Community Manager & Social Media Strategist", price: 200000, hours: 35 },
  { slug: "eduform-compta-finance-4en1", name: "Comptabilité & Finance 4 en 1", price: 365000, hours: 65 },
  { slug: "eduform-confiance-soi-affirmation-personnelle", name: "Confiance en Soi & Affirmation Personnelle", price: 115000, hours: 20 },
  { slug: "eduform-conformite-fiscale-controle-administratif", name: "Conformité Fiscale & Contrôle Administratif", price: 170000, hours: 30 },
  { slug: "eduform-conformite-rh-inspection-travail", name: "Conformité RH & Relations avec l'Inspection du Travail", price: 140000, hours: 25 },
  { slug: "eduform-conseiller-assurance-risques", name: "Conseiller en Assurance & Gestion des Risques", price: 200000, hours: 35 },
  { slug: "eduform-conseiller-microfinance-inclusion", name: "Conseiller en Microfinance & Inclusion Financière", price: 200000, hours: 30 },
  { slug: "eduform-conseiller-financier-gestion-patrimoine", name: "Conseiller Financier & Gestion de Patrimoine", price: 225000, hours: 40 },
  { slug: "eduform-contrats-commerciaux-risques", name: "Contrats Commerciaux & Gestion des Risques Juridiques", price: 170000, hours: 30 },
  { slug: "eduform-controle-de-gestion-et-analyse-de-performance", name: "Contrôle de Gestion & Analyse de Performance", price: 135000, hours: 25 },
  { slug: "eduform-controleur-gestion-junior", name: "Contrôleur de Gestion Junior", price: 225000, hours: 40 },
  { slug: "eduform-creation-entreprise-entrepreneuriat", name: "Création d'Entreprise & Entrepreneuriat", price: 160000, hours: 28 },
  { slug: "eduform-circuits-touristiques-locaux", name: "Création de Circuits Touristiques Locaux", price: 140000, hours: 25 },
  { slug: "eduform-wordpress-sites-professionnels", name: "Création de Sites Web Professionnels avec WordPress", price: 140000, hours: 25 },
  { slug: "eduform-creativite-initiative-innovation", name: "Créativité, Prise d'Initiative & Innovation", price: 115000, hours: 20 },
  { slug: "eduform-cybersecurite-reseaux", name: "Cybersécurité & Administration Réseaux", price: 365000, hours: 65 },
  { slug: "eduform-daf-dirigeant", name: "DAF Dirigeant", price: 405000, hours: 72 },
  { slug: "eduform-data-science-python-sql", name: "Data Science — Python, SQL & Analyse de Données", price: 365000, hours: 65 },
  { slug: "eduform-orientation-domaine-predilection", name: "Découverte de Votre Domaine de Prédilection Professionnel", price: 140000, hours: 25 },
  { slug: "eduform-deplacement-formateur-international", name: "Déplacement Formateur à l'International", price: 150000, hours: 25 },
  { slug: "eduform-marque-personnelle-personal-branding", name: "Développement d'une Marque Personnelle (Personal Branding)", price: 140000, hours: 25 },
  { slug: "eduform-developpement-carriere-employabilite", name: "Développement de la Carrière & Employabilité", price: 140000, hours: 25 },
  { slug: "eduform-developpement-competences-formation-continue", name: "Développement des Compétences & Formation Continue", price: 170000, hours: 30 },
  { slug: "eduform-rse-developpement-durable", name: "Développement Durable & Responsabilité Sociétale des Entreprises (RSE)", price: 200000, hours: 35 },
  { slug: "eduform-developpement-mobile-flutter", name: "Développement Mobile Android & iOS — Flutter/React Native", price: 310000, hours: 55 },
  { slug: "eduform-developpement-personnel-professionnel", name: "Développement Personnel & Intelligence Émotionnelle", price: 140000, hours: 14 },
  { slug: "eduform-developpement-web-html-css-javascript", name: "Développement Web — HTML, CSS & JavaScript", price: 200000, hours: 35 },
  { slug: "eduform-developpement-web-fullstack", name: "Développement Web Full-Stack — Débutant à Opérationnel", price: 450000, hours: 80 },
  { slug: "eduform-animateur-hse-niveau1", name: "Devenir Animateur HSE — Niveau 1", price: 85000, hours: 15 },
  { slug: "eduform-animateur-hse-niveau2", name: "Devenir Animateur HSE — Niveau 2", price: 85000, hours: 10 },
  { slug: "eduform-digitalisation-processus-comptables", name: "Digitalisation des Processus Comptables", price: 170000, hours: 30 },
  { slug: "eduform-direction-administrative-et-financiere-daf", name: "Direction Administrative & Financière (DAF)", price: 160000, hours: 25 },
  { slug: "eduform-distribution-merchandising-force-vente", name: "Distribution, Merchandising & Animation de la Force de Vente", price: 170000, hours: 30 },
  { slug: "eduform-droit-bancaire-fintech", name: "Droit Bancaire & Réglementation Fintech", price: 200000, hours: 35 },
  { slug: "eduform-droit-affaires-redaction-actes", name: "Droit des Affaires & Rédaction d'Actes Juridiques", price: 200000, hours: 35 },
  { slug: "eduform-droit-affaires-ohada-3en1", name: "Droit des Affaires OHADA 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-droit-travail-litiges-rh", name: "Droit du Travail & Gestion des Litiges RH", price: 170000, hours: 30 },
  { slug: "eduform-droit-du-travail-et-relations-sociales", name: "Droit du Travail & Relations Sociales", price: 120000, hours: 25 },
  { slug: "eduform-droit-fiscal-contentieux", name: "Droit Fiscal & Contentieux Fiscal", price: 200000, hours: 35 },
  { slug: "eduform-droit-immobilier-litiges-fonciers", name: "Droit Immobilier & Gestion des Litiges Fonciers", price: 170000, hours: 30 },
  { slug: "eduform-droit-penal-affaires", name: "Droit Pénal des Affaires", price: 200000, hours: 35 },
  { slug: "eduform-ecommerce-business-en-ligne", name: "E-commerce & Business en Ligne", price: 225000, hours: 40 },
  { slug: "eduform-reponses-appels-offres", name: "Élaboration d'Offres Commerciales & Réponses aux Appels d'Offres", price: 200000, hours: 35 },
  { slug: "eduform-plan-affaires-entrepreneurs", name: "Élaboration d'un Plan d'Affaires — Guide pour Entrepreneurs", price: 200000, hours: 35 },
  { slug: "eduform-politique-rh-pme", name: "Élaboration de Politique RH pour PME", price: 170000, hours: 30 },
  { slug: "eduform-elaboration-des-etats-financiers-syscohada", name: "Élaboration des États Financiers SYSCOHADA", price: 120000, hours: 25 },
  { slug: "eduform-plan-marketing-action-commerciale", name: "Élaboration du Plan Marketing & Plan d'Action Commercial", price: 170000, hours: 30 },
  { slug: "eduform-emailing-newsletter-automatisation-ventes", name: "Emailing, Newsletter & Automatisation des Ventes", price: 115000, hours: 20 },
  { slug: "eduform-energie-renouvelable-solaire", name: "Énergie Solaire & Énergies Renouvelables", price: 310000, hours: 55 },
  { slug: "eduform-enquetes-accidents-travail", name: "Enquêtes & Analyse des Accidents de Travail", price: 140000, hours: 25 },
  { slug: "eduform-entrepreneuriat-et-creation-d-entreprise", name: "Entrepreneuriat & Création d'Entreprise", price: 120000, hours: 25 },
  { slug: "eduform-entrepreneuriat-feminin", name: "Entrepreneuriat Féminin & Leadership", price: 140000, hours: 25 },
  { slug: "eduform-entrepreneuriat-social-solidaire", name: "Entrepreneuriat Social & Solidaire", price: 140000, hours: 25 },
  { slug: "eduform-odoo-erp", name: "ERP Odoo — Utilisation & Paramétrage", price: 170000, hours: 30 },
  { slug: "eduform-evaluation-expertise-immobiliere", name: "Évaluation & Expertise Immobilière", price: 200000, hours: 35 },
  { slug: "eduform-evenementiel-digital-organisation-virtuelle", name: "Événementiel Digital & Organisation d'Événements Virtuels", price: 140000, hours: 25 },
  { slug: "eduform-excel-power-query-analyse", name: "Excel Avancé — Power Query & Analyse de Données", price: 140000, hours: 25 },
  { slug: "eduform-excel-expert", name: "Excel Expert — Formules, TCD & Macros VBA", price: 85000, hours: 14 },
  { slug: "eduform-excel-debutant", name: "Excel Niveau Débutant", price: 225000, hours: 40 },
  { slug: "eduform-excel-intermediaire", name: "Excel Niveau Intermédiaire", price: 170000, hours: 30 },
  { slug: "eduform-expert-rh-3en1", name: "Expert RH 3 en 1 — RH, Paie & Data Analytics", price: 405000, hours: 55 },
  { slug: "eduform-facility-management-maintenance", name: "Facility Management & Maintenance Immobilière", price: 170000, hours: 30 },
  { slug: "eduform-fidelisation-client-sav", name: "Fidélisation Client & Service Après-Vente", price: 140000, hours: 25 },
  { slug: "eduform-finance-pour-non-financiers", name: "Finance pour Non-Financiers", price: 140000, hours: 25 },
  { slug: "eduform-fiscalite-petites-entreprises", name: "Fiscalité des Petites Entreprises & Travailleurs Indépendants", price: 140000, hours: 25 },
  { slug: "eduform-fiscalite-immobiliere", name: "Fiscalité Immobilière & Optimisation Patrimoniale", price: 170000, hours: 30 },
  { slug: "eduform-fiscalite-pratique-entreprises", name: "Fiscalité Pratique des Entreprises", price: 200000, hours: 35 },
  { slug: "eduform-foncier-urbanisme-droit-ci", name: "Foncier, Urbanisme & Droit Immobilier en Côte d'Ivoire", price: 160000, hours: 28 },
  { slug: "eduform-fondamentaux-gestion-entreprise", name: "Fondamentaux de la Gestion d'Entreprise — Stratégies pour le Succès", price: 255000, hours: 45 },
  { slug: "eduform-fondamentaux-gestion-projets", name: "Fondamentaux de la Gestion de Projets — Cycle & Outils", price: 170000, hours: 30 },
  { slug: "eduform-formation-internationale-diaspora", name: "Formation à Distance — International & Diaspora", price: 85000, hours: 25 },
  { slug: "eduform-formation-de-formateurs", name: "Formation de Formateurs & Ingénierie Pédagogique", price: 310000, hours: 55 },
  { slug: "eduform-formation-presentiel-standard", name: "Formation en Présentiel — Toutes Formations", price: 85000, hours: 25 },
  { slug: "eduform-formation-individuelle-particulier", name: "Formation Individuelle pour Particulier", price: 85000, hours: 25 },
  { slug: "eduform-intra-entreprise-presentiel", name: "Formation Intra-Entreprise en Présentiel", price: 150000, hours: 25 },
  { slug: "eduform-libre-choix-sur-mesure", name: "Formation Libre Choix & Sur Mesure — Particulier", price: 85000, hours: 25 },
  { slug: "eduform-sur-mesure-entreprise", name: "Formation Sur Mesure Entreprise", price: 150000, hours: 25 },
  { slug: "eduform-francais-professionnel-redaction", name: "Français Professionnel & Rédaction Administrative", price: 85000, hours: 14 },
  { slug: "eduform-leadership-sante", name: "Gestion & Leadership dans le Secteur de la Santé", price: 200000, hours: 35 },
  { slug: "eduform-gestion-associations-ong", name: "Gestion & Renforcement des Capacités pour Associations et ONG", price: 225000, hours: 40 },
  { slug: "eduform-gestion-etablissement-sante-3en1", name: "Gestion d'Établissement de Santé 3 en 1", price: 85000, hours: 55 },
  { slug: "eduform-gestion-cooperative-mutuelle", name: "Gestion d'une Coopérative ou d'une Mutuelle", price: 170000, hours: 30 },
  { slug: "eduform-gestion-copropriete-syndic", name: "Gestion de Copropriété & Syndic", price: 170000, hours: 30 },
  { slug: "eduform-e-reputation-communication-crise-ligne", name: "Gestion de l'E-réputation & Communication de Crise en Ligne", price: 170000, hours: 30 },
  { slug: "eduform-gestion-de-la-paie-et-administration-du-personnel", name: "Gestion de la Paie & Administration du Personnel", price: 120000, hours: 25 },
  { slug: "eduform-crm-gestion-relation-client", name: "Gestion de la Relation Client — CRM", price: 170000, hours: 30 },
  { slug: "eduform-gestion-de-projet-et-planification-strategique", name: "Gestion de Projet & Planification Stratégique", price: 120000, hours: 25 },
  { slug: "eduform-gestion-de-projet-humanitaire-et-ong", name: "Gestion de Projet Humanitaire & ONG", price: 120000, hours: 25 },
  { slug: "eduform-gestion-projets-avancee-pmi-prince2", name: "Gestion de Projets Avancée — PMI/PMBOK & Prince2", price: 225000, hours: 40 },
  { slug: "eduform-projets-humanitaires-3en1", name: "Gestion de Projets Humanitaires & ONG 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-gestion-projets-internationaux", name: "Gestion de Projets Internationaux & Coopération au Développement", price: 225000, hours: 40 },
  { slug: "eduform-gestion-projets-pmp-agile-3en1", name: "Gestion de Projets PMP, Agile & Scrum 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-gestion-tresorerie-budget", name: "Gestion de Trésorerie & Budget", price: 170000, hours: 30 },
  { slug: "eduform-gestion-vie-equilibre-personnel-professionnel", name: "Gestion de Vie & Équilibre Personnel-Professionnel", price: 115000, hours: 20 },
  { slug: "eduform-gestion-assurances-sinistres", name: "Gestion des Assurances, Sinistres & Indemnisations", price: 170000, hours: 30 },
  { slug: "eduform-gestion-conflits-climat-social", name: "Gestion des Conflits & Climat Social en Entreprise", price: 140000, hours: 25 },
  { slug: "eduform-credits-recouvrement-bancaire", name: "Gestion des Crédits & Recouvrement Bancaire", price: 200000, hours: 35 },
  { slug: "eduform-gestion-dechets-environnement", name: "Gestion des Déchets & Protection de l'Environnement", price: 140000, hours: 25 },
  { slug: "eduform-partenariats-relations-bailleurs", name: "Gestion des Partenariats & Relations avec les Bailleurs de Fonds", price: 170000, hours: 30 },
  { slug: "eduform-gestion-projets-btp", name: "Gestion des Projets BTP — Budget, Délais & Qualité", price: 200000, hours: 35 },
  { slug: "eduform-gestion-risques-qualite-projets", name: "Gestion des Risques & Qualité dans les Projets", price: 170000, hours: 30 },
  { slug: "eduform-gestion-risques-financiers-climat", name: "Gestion des Risques Financiers & Climatiques dans les Banques", price: 225000, hours: 40 },
  { slug: "eduform-gestion-risques-qhse-entreprise", name: "Gestion des Risques QHSE en Entreprise", price: 170000, hours: 30 },
  { slug: "eduform-gestion-stocks", name: "Gestion des Stocks", price: 225000, hours: 40 },
  { slug: "eduform-gestion-stress-emotions", name: "Gestion du Stress & des Émotions en Milieu Professionnel", price: 115000, hours: 20 },
  { slug: "eduform-gestion-financiere-comptable-ong", name: "Gestion Financière & Comptable des ONG", price: 200000, hours: 35 },
  { slug: "eduform-gestion-financiere-non-financiers", name: "Gestion Financière pour Non-Financiers", price: 140000, hours: 25 },
  { slug: "eduform-gestion-hoteliere-tourisme", name: "Gestion Hôtelière & Tourisme", price: 310000, hours: 55 },
  { slug: "eduform-gestion-immobiliere-professionnelle", name: "Gestion Immobilière Professionnelle", price: 135000, hours: 25 },
  { slug: "eduform-gestion-juridique-pme-startups", name: "Gestion Juridique des PME & Startups", price: 170000, hours: 30 },
  { slug: "eduform-gestion-agence-bancaire", name: "Gestion Opérationnelle d'une Agence Bancaire", price: 200000, hours: 35 },
  { slug: "eduform-gestionnaire-administratif-logistique", name: "Gestionnaire Administratif & Logistique", price: 200000, hours: 30 },
  { slug: "eduform-gestionnaire-comptable", name: "Gestionnaire Comptable", price: 140000, hours: 50 },
  { slug: "eduform-gestionnaire-bureau-secretariat-general", name: "Gestionnaire de Bureau & Secrétariat Général", price: 200000, hours: 30 },
  { slug: "eduform-gestionnaire-dossiers-archives-numeriques", name: "Gestionnaire de Dossiers & Archives Numériques", price: 200000, hours: 25 },
  { slug: "eduform-gestionnaire-microcredit-finance-inclusive", name: "Gestionnaire de Microcrédit & Finance Inclusive", price: 200000, hours: 35 },
  { slug: "eduform-gestionnaire-paie-administration-personnel", name: "Gestionnaire de Paie & Administration du Personnel", price: 200000, hours: 35 },
  { slug: "eduform-gestionnaire-personnel", name: "Gestionnaire de Personnel", price: 200000, hours: 35 },
  { slug: "eduform-google-workspace-pme", name: "Google Workspace pour PME — Outils Collaboratifs", price: 85000, hours: 15 },
  { slug: "eduform-gouvernance-microfinance", name: "Gouvernance & Management des Institutions de Microfinance", price: 170000, hours: 30 },
  { slug: "eduform-gpec", name: "GPEC — Gestion Prévisionnelle des Emplois et des Compétences", price: 170000, hours: 30 },
  { slug: "eduform-haccp-securite-alimentaire", name: "HACCP & Sécurité Alimentaire", price: 170000, hours: 30 },
  { slug: "eduform-hse-chantiers-btp", name: "HSE dans les Chantiers BTP", price: 170000, hours: 30 },
  { slug: "eduform-hygiene-hospitaliere-infections", name: "Hygiène Hospitalière & Prévention des Infections", price: 140000, hours: 25 },
  { slug: "eduform-ifrs-banques-assurances", name: "IFRS Avancé pour Banques & Assurances", price: 225000, hours: 40 },
  { slug: "eduform-branding-identite-visuelle", name: "Image de Marque, Identité Visuelle & Branding", price: 170000, hours: 30 },
  { slug: "eduform-immobilier-durable-eco-construction", name: "Immobilier Durable & Éco-construction", price: 200000, hours: 35 },
  { slug: "eduform-immobilier-3en1", name: "Immobilier Professionnel 3 en 1", price: 405000, hours: 65 },
  { slug: "eduform-immobilier-social-logement-abordable", name: "Immobilier Social & Logement Abordable", price: 170000, hours: 30 },
  { slug: "eduform-initiation-informatique-debutants", name: "Initiation à l'Informatique pour Adultes Débutants", price: 115000, hours: 20 },
  { slug: "eduform-innovation-creativite-entreprise", name: "Innovation & Créativité en Entreprise", price: 140000, hours: 25 },
  { slug: "eduform-propriete-intellectuelle-startups", name: "Innovation & Propriété Intellectuelle pour Startups", price: 140000, hours: 25 },
  { slug: "eduform-ia-machine-learning-affaires", name: "Intelligence Artificielle & Machine Learning pour les Affaires", price: 255000, hours: 45 },
  { slug: "eduform-intelligence-artificielle-pour-professionnels", name: "Intelligence Artificielle pour Professionnels", price: 25000, hours: 25 },
  { slug: "eduform-ia-professionnels", name: "Intelligence Artificielle pour Professionnels", price: 25000, hours: 7 },
  { slug: "eduform-intelligence-economique-veille", name: "Intelligence Économique & Veille Concurrentielle", price: 170000, hours: 30 },
  { slug: "eduform-intelligence-emotionnelle-travail", name: "Intelligence Émotionnelle au Travail", price: 140000, hours: 25 },
  { slug: "eduform-introduction-ia-concepts-outils", name: "Introduction à l'Intelligence Artificielle — Concepts, Outils & Applications", price: 140000, hours: 25 },
  { slug: "eduform-bim-building-information-modeling", name: "Introduction au BIM — Building Information Modeling", price: 200000, hours: 35 },
  { slug: "eduform-introduction-metiers-banque-assurance", name: "Introduction aux Métiers de la Banque & de l'Assurance", price: 115000, hours: 20 },
  { slug: "eduform-journalisme-production-media", name: "Journalisme & Production Média Digitale", price: 225000, hours: 40 },
  { slug: "eduform-kobotoolbox", name: "KoBoToolbox & Collecte de Données", price: 25000, hours: 14 },
  { slug: "eduform-leadership-et-management-d-equipe", name: "Leadership & Management d'Équipe", price: 135000, hours: 25 },
  { slug: "eduform-leadership-management-equipes-projet", name: "Leadership & Management d'Équipes Projet", price: 170000, hours: 30 },
  { slug: "eduform-leadership-transformation-digitale-ia", name: "Leadership & Transformation Digitale — IA & Big Data au Service du Management", price: 225000, hours: 40 },
  { slug: "eduform-leadership-feminin", name: "Leadership Féminin & Empowerment", price: 140000, hours: 25 },
  { slug: "eduform-leadership-feminin-soft-skills", name: "Leadership Féminin & Soft Skills au Travail", price: 140000, hours: 25 },
  { slug: "eduform-leadership-humanitaire-coordination-crise", name: "Leadership Humanitaire & Coordination de Crise", price: 200000, hours: 35 },
  { slug: "eduform-leadership-transformationnel", name: "Leadership Transformationnel & Management du Changement", price: 170000, hours: 30 },
  { slug: "eduform-logistique-supply-chain-4en1", name: "Logistique & Supply Chain Management 4 en 1", price: 365000, hours: 65 },
  { slug: "eduform-logistique-humanitaire-urgence", name: "Logistique Humanitaire & Gestion des Urgences", price: 170000, hours: 30 },
  { slug: "eduform-logistique-petroliere-produits-dangereux", name: "Logistique Pétrolière & Transport de Produits Dangereux", price: 225000, hours: 40 },
  { slug: "eduform-lbc-ft-blanchiment-capitaux", name: "Lutte contre le Blanchiment de Capitaux & Financement du Terrorisme (LBC-FT)", price: 170000, hours: 30 },
  { slug: "eduform-art-oratoire-impact", name: "Maîtrise de l'Art Oratoire — Communiquer avec Impact", price: 170000, hours: 30 },
  { slug: "eduform-gestion-commerciale-ventes", name: "Maîtriser la Gestion Commerciale — Stratégies pour Accroître les Ventes", price: 200000, hours: 35 },
  { slug: "eduform-management-leadership-4en1", name: "Management & Leadership 4 en 1", price: 365000, hours: 65 },
  { slug: "eduform-management-equipe-commerciale", name: "Management d'Équipe Commerciale", price: 200000, hours: 35 },
  { slug: "eduform-management-environnemental-developpement-durable", name: "Management Environnemental & Développement Durable", price: 170000, hours: 30 },
  { slug: "eduform-management-interculturel", name: "Management Interculturel & International", price: 200000, hours: 35 },
  { slug: "eduform-management-rh-agile-strategique", name: "Management RH Agile & Stratégique", price: 200000, hours: 35 },
  { slug: "eduform-manager-coach-techniques", name: "Manager Coach — Techniques de Coaching pour Cadres", price: 170000, hours: 30 },
  { slug: "eduform-marches-publics-3en1", name: "Marchés Publics & Gestion des Achats 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-marketing-influence-contenu", name: "Marketing d'Influence & Stratégie de Contenu", price: 140000, hours: 25 },
  { slug: "eduform-marketing-reseaux-sociaux", name: "Marketing des Réseaux Sociaux", price: 170000, hours: 30 },
  { slug: "eduform-marketing-digital-3en1", name: "Marketing Digital 3 en 1", price: 310000, hours: 55 },
  { slug: "eduform-whatsapp-business-marketing-mobile", name: "Marketing Mobile — WhatsApp Business & SMS Pro", price: 115000, hours: 20 },
  { slug: "eduform-lean-startup-pitch", name: "Méthodologie Lean Startup & Pitch", price: 140000, hours: 25 },
  { slug: "eduform-microsoft-365-outils-collaboratifs", name: "Microsoft 365 — Suite Collaborative Complète", price: 115000, hours: 20 },
  { slug: "eduform-power-bi", name: "Microsoft Power BI", price: 25000, hours: 14 },
  { slug: "eduform-microsoft-project", name: "Microsoft Project", price: 25000, hours: 25 },
  { slug: "eduform-mindset-entrepreneurial-mentalite-gagnante", name: "Mindset Entrepreneurial & Mentalité Gagnante", price: 115000, hours: 20 },
  { slug: "eduform-monetique-systemes-paiement", name: "Monétique, Systèmes de Paiement & Sécurité", price: 170000, hours: 30 },
  { slug: "eduform-motivation-discipline-productivite", name: "Motivation, Discipline & Productivité Personnelle", price: 115000, hours: 20 },
  { slug: "eduform-negociation-internationale-diplomatie", name: "Négociation Internationale & Diplomatie d'Entreprise", price: 200000, hours: 35 },
  { slug: "eduform-outils-gestion-projet-digital", name: "Outils de Gestion de Projet Digital — Trello, Asana, Monday, Notion", price: 85000, hours: 14 },
  { slug: "eduform-outils-numeriques-gestion-projets", name: "Outils Numériques de Gestion de Projets — MS Project, Jira, Trello, Asana", price: 170000, hours: 30 },
  { slug: "eduform-pilotage-performance-tableaux-bord", name: "Pilotage de la Performance par les Tableaux de Bord Stratégiques", price: 170000, hours: 30 },
  { slug: "eduform-plaidoyer-communication-ong", name: "Plaidoyer & Communication Institutionnelle pour ONG", price: 170000, hours: 30 },
  { slug: "eduform-planification-logistique-stock", name: "Planification Logistique & Gestion de Stock", price: 170000, hours: 30 },
  { slug: "eduform-planification-suivi-evaluation-se", name: "Planification, Suivi & Évaluation (S&E / Monitoring & Evaluation)", price: 200000, hours: 35 },
  { slug: "eduform-media-training-porte-parole", name: "Porte-Parole & Média Training", price: 170000, hours: 30 },
  { slug: "eduform-veille-legale-reglementaire", name: "Pratique de la Veille Légale & Réglementaire", price: 140000, hours: 25 },
  { slug: "eduform-certification-amf-preparation", name: "Préparation à la Certification AMF — Marchés Financiers", price: 200000, hours: 35 },
  { slug: "eduform-preparation-concours-professionnels", name: "Préparation Concours & Certifications Professionnelles", price: 85000, hours: 25 },
  { slug: "eduform-prise-de-parole-et-communication-manageriale", name: "Prise de Parole & Communication Managériale", price: 135000, hours: 25 },
  { slug: "eduform-promotion-immobiliere", name: "Promotion Immobilière — de l'Idée à la Commercialisation", price: 225000, hours: 40 },
  { slug: "eduform-python-analyse-donnees", name: "Python pour l'Analyse de Données", price: 200000, hours: 35 },
  { slug: "eduform-qhse-4en1", name: "QHSE Expert 4 en 1", price: 365000, hours: 65 },
  { slug: "eduform-recrutement-integration-fidelisation", name: "Recrutement, Intégration & Fidélisation du Personnel", price: 170000, hours: 30 },
  { slug: "eduform-copywriting-contenu-corporate", name: "Rédaction de Contenus Corporate & Copywriting", price: 140000, hours: 25 },
  { slug: "eduform-redaction-propositions-financement-ong", name: "Rédaction de Propositions de Financement pour ONG & Associations", price: 170000, hours: 30 },
  { slug: "eduform-relations-presse-communiques-medias", name: "Relations Presse & Communiqués Médias", price: 170000, hours: 30 },
  { slug: "eduform-resilience-adaptabilite-changement", name: "Résilience & Adaptabilité face au Changement", price: 115000, hours: 20 },
  { slug: "eduform-resolution-problemes-design-thinking", name: "Résolution de Problèmes Complexes — Design Thinking & Méthodes Agiles", price: 170000, hours: 30 },
  { slug: "eduform-rse-responsabilite-societale", name: "Responsabilité Sociétale des Entreprises (RSE)", price: 170000, hours: 30 },
  { slug: "eduform-responsable-achats-approvisionnement", name: "Responsable Achats & Approvisionnement", price: 200000, hours: 35 },
  { slug: "eduform-responsable-achats-internationaux-supply-chain", name: "Responsable Achats Internationaux & Supply Chain", price: 225000, hours: 40 },
  { slug: "eduform-responsable-administratif-operationnel", name: "Responsable Administratif & Opérationnel", price: 200000, hours: 35 },
  { slug: "eduform-responsable-administration-generale", name: "Responsable Administration Générale", price: 225000, hours: 40 },
  { slug: "eduform-responsable-audit-interne", name: "Responsable Audit Interne", price: 225000, hours: 40 },
  { slug: "eduform-responsable-centre-appels", name: "Responsable Centre d'Appels & Relation Client", price: 200000, hours: 35 },
  { slug: "eduform-responsable-commercial-business-developer", name: "Responsable Commercial & Business Developer", price: 225000, hours: 40 },
  { slug: "eduform-responsable-commercial-et-marketing-operationnel", name: "Responsable Commercial & Marketing Opérationnel", price: 135000, hours: 25 },
  { slug: "eduform-relations-publiques-communication-institutionnelle", name: "Responsable Communication & Relations Publiques", price: 200000, hours: 35 },
  { slug: "eduform-responsable-coordination-administrative-projets", name: "Responsable Coordination Administrative de Projets", price: 200000, hours: 35 },
  { slug: "eduform-responsable-services-generaux", name: "Responsable des Services Généraux", price: 200000, hours: 30 },
  { slug: "eduform-responsable-developpement-durable-rse", name: "Responsable Développement Durable & RSE", price: 200000, hours: 35 },
  { slug: "eduform-responsable-developpement-touristique", name: "Responsable Développement Touristique & Hôtelier", price: 200000, hours: 35 },
  { slug: "eduform-responsable-export-developpement-international", name: "Responsable Export & Développement International", price: 225000, hours: 40 },
  { slug: "eduform-responsable-formation-developpement-rh", name: "Responsable Formation & Développement RH", price: 200000, hours: 35 },
  { slug: "eduform-responsable-logistique-transport-maritime", name: "Responsable Logistique & Transport Maritime", price: 225000, hours: 40 },
  { slug: "eduform-responsable-marketing-digital-ecommerce", name: "Responsable Marketing Digital & E-commerce", price: 225000, hours: 40 },
  { slug: "eduform-responsable-pilotage-reporting-administratif", name: "Responsable Pilotage & Reporting Administratif", price: 200000, hours: 35 },
  { slug: "eduform-responsable-qhse", name: "Responsable QHSE", price: 135000, hours: 25 },
  { slug: "eduform-responsable-qse", name: "Responsable Qualité, Sécurité & Environnement (QSE)", price: 200000, hours: 35 },
  { slug: "eduform-responsable-transformation-digitale", name: "Responsable Transformation Digitale", price: 225000, hours: 40 },
  { slug: "eduform-rgpd-afrique-protection-donnees", name: "RGPD Afrique — Protection des Données Personnelles", price: 170000, hours: 30 },
  { slug: "eduform-sage100-comptabilite", name: "Sage 100 Comptabilité", price: 25000, hours: 25 },
  { slug: "eduform-sage-100-gescom", name: "Sage 100 GESCOM", price: 25000, hours: 25 },
  { slug: "eduform-sage100-gescom", name: "Sage 100 GESCOM", price: 25000, hours: 25 },
  { slug: "eduform-sage-100-gestion-de-caisse", name: "Sage 100 Gestion de Caisse", price: 25000, hours: 25 },
  { slug: "eduform-sage100-paie-rh", name: "Sage 100 Paie & RH", price: 170000, hours: 30 },
  { slug: "eduform-sage-etats-comptables-et-fiscaux", name: "Sage États Comptables & Fiscaux", price: 25000, hours: 25 },
  { slug: "eduform-sage-etats-fiscaux", name: "Sage États Comptables & Fiscaux", price: 25000, hours: 7 },
  { slug: "eduform-iso-45001-sante-securite-travail", name: "Santé Sécurité au Travail — ISO 45001", price: 200000, hours: 35 },
  { slug: "eduform-sap-fi-comptabilite-financiere", name: "SAP FI – Comptabilité Financière", price: 35000, hours: 25 },
  { slug: "eduform-sap-fi", name: "SAP FI — Comptabilité Financière", price: 25000, hours: 14 },
  { slug: "eduform-secretaire-assistant-direction", name: "Secrétaire / Assistant(e) de Direction", price: 200000, hours: 30 },
  { slug: "eduform-secretaire-comptable", name: "Secrétaire Comptable", price: 200000, hours: 30 },
  { slug: "eduform-secretaire-juridique", name: "Secrétaire Juridique", price: 200000, hours: 30 },
  { slug: "eduform-secretaire-medical-administratif", name: "Secrétaire Médical & Administratif", price: 200000, hours: 30 },
  { slug: "eduform-securite-informatique-protection-donnees", name: "Sécurité Informatique & Protection des Données", price: 170000, hours: 30 },
  { slug: "eduform-soft-skills-assistantes-direction", name: "Soft Skills pour Assistantes & Secrétaires de Direction", price: 115000, hours: 20 },
  { slug: "eduform-specialiste-portefeuille-immobilier", name: "Spécialiste en Gestion de Portefeuille Immobilier", price: 225000, hours: 40 },
  { slug: "eduform-specialiste-gestion-projets-agricoles", name: "Spécialiste en Gestion de Projets Agricoles & Agro-business", price: 225000, hours: 40 },
  { slug: "eduform-specialiste-rh-40", name: "Spécialiste en Gestion des Ressources Humaines 4.0", price: 225000, hours: 40 },
  { slug: "eduform-specialiste-passation-marches", name: "Spécialiste en Passation de Marchés Publics & Privés", price: 225000, hours: 40 },
  { slug: "eduform-startup-tech-incubation", name: "Startup Tech — Incubation, Levée de Fonds & Scalabilité", price: 200000, hours: 35 },
  { slug: "eduform-strategie-croissance-pme-startups", name: "Stratégie de Croissance pour PME & Startups", price: 170000, hours: 30 },
  { slug: "eduform-strategie-digitale-transformation", name: "Stratégie Digitale & Transformation Numérique", price: 200000, hours: 35 },
  { slug: "eduform-meal-suivi-evaluation-projets", name: "Suivi-Évaluation de Projets Humanitaires — MEAL", price: 170000, hours: 30 },
  { slug: "eduform-sycebnl-comptabilite-ong", name: "SYCEBNL — Comptabilité des ONG & Associations", price: 200000, hours: 35 },
  { slug: "eduform-tableaux-de-bord-performance", name: "Tableaux de Bord — Outils & Techniques de Suivi de Performance", price: 200000, hours: 35 },
  { slug: "eduform-tableaux-bord-rh-indicateurs-performance", name: "Tableaux de Bord RH & Indicateurs de Performance", price: 140000, hours: 25 },
  { slug: "eduform-tarif-groupe-5plus", name: "Tarif Groupe — 5 Personnes et Plus", price: 85000, hours: 25 },
  { slug: "eduform-technicien-energies-renouvelables", name: "Technicien en Énergies Renouvelables — Solaire & Éolien", price: 225000, hours: 40 },
  { slug: "eduform-technicien-gestion-logistique-transit", name: "Technicien en Gestion Logistique & Transit Douanier", price: 200000, hours: 35 },
  { slug: "eduform-technicien-securite-incendie", name: "Technicien en Sécurité Incendie", price: 140000, hours: 25 },
  { slug: "eduform-negociation-avancee", name: "Techniques Avancées de Négociation", price: 140000, hours: 25 },
  { slug: "eduform-techniques-vente-negociation-commerciale", name: "Techniques de Vente & Négociation Commerciale", price: 170000, hours: 30 },
  { slug: "eduform-vente-relation-client-banque-assurance", name: "Techniques de Vente & Relation Client dans la Banque & l'Assurance", price: 170000, hours: 30 },
  { slug: "eduform-time-management-priorites", name: "Time Management & Gestion des Priorités", price: 115000, hours: 20 },
  { slug: "eduform-cloud-drive-stockage-partage", name: "Transformation Digitale par le Cloud — Drive, OneDrive, Dropbox", price: 40000, hours: 14 },
  { slug: "eduform-transport-logistique-et-supply-chain-management", name: "Transport, Logistique & Supply Chain Management", price: 135000, hours: 25 },
  { slug: "eduform-vente-b2b-prospection-grands-comptes", name: "Vente B2B & Prospection Grands Comptes", price: 170000, hours: 30 },
  { slug: "eduform-video-corporate-pitch-video", name: "Vidéos Corporate, Pitch Vidéo & Formats Réseaux", price: 140000, hours: 25 },
];

export async function POST(req: NextRequest) {
  const auth = await isSyncAuthorized(req);
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const branch = await prisma.branch.findUnique({ where: { slug: "ibig-eduform" } });
  if (!branch) return NextResponse.json({ error: "Branche ibig-eduform introuvable" }, { status: 404 });

  const BATCH = 5;
  let upserted = 0;
  const errors: string[] = [];

  for (let i = 0; i < RECOVER_PRODUCTS.length; i += BATCH) {
    const batch = RECOVER_PRODUCTS.slice(i, i + BATCH);
    await Promise.all(
      batch.map(async (p) => {
        try {
          const siteUrl = `https://ibig-eduform.com/formation-detail.php?slug=${p.slug}`;
          await prisma.product.upsert({
            where: { slug: p.slug },
            update: { name: p.name, price: p.price, branchId: branch.id, active: true, siteUrl },
            create: {
              slug: p.slug,
              name: p.name,
              pricingType: "FIXED",
              price: p.price,
              rate: 0,
              siteUrl,
              branchId: branch.id,
              active: true,
            },
          });
          upserted++;
        } catch (e: unknown) {
          errors.push(`${p.slug}: ${e instanceof Error ? e.message : String(e)}`);
        }
      })
    );
  }

  const total = await prisma.product.count({ where: { branchId: branch.id, active: true } });
  return NextResponse.json({ ok: true, upserted, errors, totalInBranch: total });
}
